import Link from 'next/link';
import {notFound} from 'next/navigation';
import {platform} from '../../lib/platform';
import {adminUser} from '../../lib/admin';
export const dynamic='force-dynamic';
export const metadata={title:'Administration',robots:{index:false,follow:false}};
export default async function AdminPage(){const env=await platform();if(!await adminUser(env))notFound();const [recruiters,tickets,runs,sources,price]=await Promise.all([
 env.DB.prepare(`SELECT r.*,u.email FROM recruiter_accounts r JOIN users u ON u.id=r.user_id ORDER BY r.created_at DESC LIMIT 100`).bind().all<{user_id:string;company:string;website:string;status:string;email:string}>(),
 env.DB.prepare(`SELECT t.*,u.email,EXISTS(SELECT 1 FROM employer_listings l WHERE l.user_id=t.user_id AND l.support=1 AND l.expires_at>?) premium FROM support_requests t JOIN users u ON u.id=t.user_id ORDER BY premium DESC,t.created_at DESC LIMIT 100`).bind(new Date().toISOString()).all<{id:string;email:string;subject:string;message:string;status:string;reply:string|null;premium:number}>(),
 env.DB.prepare('SELECT source,started_at,ok,stats_json FROM crawl_runs ORDER BY started_at DESC LIMIT 30').bind().all<{source:string;started_at:string;ok:number;stats_json:string}>(),
 env.DB.prepare('SELECT name,career_url,ats_type FROM companies WHERE career_url IS NOT NULL ORDER BY name LIMIT 500').bind().all<{name:string;career_url:string;ats_type:string|null}>(),
 env.DB.prepare("SELECT value FROM marketplace_settings WHERE key='recruiter_price_cents'").bind().first<string>('value')]);
 return <main className="container container--content stack"><p><Link href="/admin/advertising">Advertising network</Link> · <Link href="/admin/operations">Payments and notifications</Link></p><h1>Administration</h1><h2>Recruiter pricing</h2><form className="commerce-form" action="/api/admin" method="post"><input type="hidden" name="action" value="price"/><label>Price in USD for 30 days<input name="price" type="number" required min={1} max={100000} defaultValue={Number(price)/100||''}/></label><button>Save price</button></form><h2>Recruiter verification</h2>{recruiters.results.map(r=><article className="panel" key={r.user_id}><h3>{r.company}</h3><p>{r.email} · {r.status}</p><a href={r.website} target="_blank" rel="noopener">Company website</a><form action="/api/admin" method="post"><input type="hidden" name="action" value="recruiter"/><input type="hidden" name="id" value={r.user_id}/><button name="status" value="verified">Verify company</button><button name="status" value="rejected">Reject or revoke access</button></form></article>)}<h2>Support inbox</h2>{tickets.results.map(t=><article className="panel" key={t.id}><h3>{t.premium?'Priority · ':''}{t.subject}</h3><p>{t.email} · {t.status}</p><p>{t.message}</p><form className="commerce-form" method="post" action="/api/admin"><input type="hidden" name="action" value="support"/><input type="hidden" name="id" value={t.id}/><label>Reply<textarea name="reply" required maxLength={10000} defaultValue={t.reply??''}/></label><button>Publish reply to customer</button></form></article>)}<h2>Career sources</h2><a href="/admin/sources">Discovery catalog and source health</a><form className="commerce-form" action="/api/admin" method="post"><input type="hidden" name="action" value="source"/><label>Company name<input name="name" required maxLength={160}/></label><label>Careers or ATS board URL<input name="url" type="url" required/></label><button>Add or update source</button></form><p>Configured sources are scanned on the crawler schedule.</p>{sources.results.map((s,i)=><p key={i}>{s.name} · {s.ats_type||'JobPosting JSON-LD'} · <a href={s.career_url} target="_blank" rel="noopener">Careers</a></p>)}<h2>Recent crawl runs</h2>{runs.results.map((r,i)=><article key={i}><strong>{r.source} · {r.ok?'Succeeded':'Failed'}</strong><p>{r.started_at}</p><pre style={{whiteSpace:'pre-wrap'}}>{r.stats_json}</pre></article>)}</main>;
}
