import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {beforeEach,it,expect,vi} from 'vitest';
const mocks=vi.hoisted(()=>({user:vi.fn(),first:vi.fn(),bind:vi.fn()}));
vi.stubGlobal('React',React);
vi.mock('../../lib/platform',()=>({currentUser:mocks.user,platform:async()=>({DB:{prepare:()=>({bind:(id:string)=>{mocks.bind(id);return {first:mocks.first};}})}})}));
vi.mock('../../lib/profile/completeness',()=>({loadProfileDetails:async()=>({display_name:'Ada'}),loadProfileCompleteness:async()=>80}));
vi.mock('next/navigation',()=>({redirect:(url:string)=>{throw new Error(url);}}));
beforeEach(()=>{vi.clearAllMocks();mocks.user.mockResolvedValue({id:'candidate-1'});mocks.first.mockResolvedValue(3);});
it('requires an authenticated candidate',async()=>{mocks.user.mockResolvedValue(null);const {default:Page}=await import('./page');await expect(Page()).rejects.toThrow('/login?next=/dashboard');expect(mocks.bind).not.toHaveBeenCalled();});
it('shows own saved jobs, alerts and profile without a paid application quota',async()=>{const {default:Page}=await import('./page');const html=renderToStaticMarkup(await Page());expect(html).toContain('Hi Ada');expect(html).toContain('80%');expect(html).toContain('3 saved');expect(html).toContain('3 active');expect(html).toContain('href="/alerts"');expect(html).toContain('href="/saved-jobs"');expect(html).toContain('apply to jobs for free');expect(html).not.toMatch(/unlocks|Not available yet|Paid plan/i);expect(mocks.bind.mock.calls).toEqual([['candidate-1'],['candidate-1']]);});
