import Link from 'next/link';
import {notFound} from 'next/navigation';
import {platform} from '../../../lib/platform';
import {adminUser} from '../../../lib/admin';
export const dynamic='force-dynamic';
export const metadata={title:'Operations',robots:{index:false,follow:false}};
export default async function Operations({searchParams}:{searchParams:Promise<{reconciled?:string;after?:string;q?:string}>}){const env=await platform();if(!await adminUser(env))notFound();const f=await searchParams;
 const [orders,notifications,jobs]=await Promise.all([
 env.DB.prepare("SELECT id,kind,status,created_at FROM employer_orders UNION ALL SELECT id,kind,status,created_at FROM marketplace_orders ORDER BY created_at DESC LIMIT 100").bind().all<{id:string;kind:string;status:string;created_at:string}>(),
 env.DB.prepare('SELECT id,subject,attempts,last_error FROM notification_outbox WHERE sent_at IS NULL ORDER BY created_at LIMIT 100').bind().all<{id:string;subject:string;attempts:number;last_error:string|null}>(),
 env.DB.prepare("SELECT id,title,listed,moderation_hidden FROM jobs WHERE title LIKE ? ESCAPE '\\' ORDER BY created_at DESC LIMIT 50").bind('%'+(f.q||'').slice(0,100).replace(/[\\%_]/g,'\\$&')+'%').all<{id:string;title:string;listed:number;moderation_hidden:number}>()]);
 return <main className="container stack"><h1>Payments, delivery and moderation</h1><Link href="/admin">Administration</Link>{f.reconciled?<p role="status">Reconciliation completed for {f.reconciled}.{f.after?' Older invoices remain: continue below.':''}</p>:null}{f.after?<form method="post" action="/api/admin/operations"><input name="action" type="hidden" value="reconcile"/><input name="id" type="hidden" value={f.reconciled}/><input name="after" type="hidden" value={f.after}/><button>Reconcile next invoice page</button></form>:null}
 <h2>Recent orders</h2><p>Reconciliation checks Stripe and recovers confirmed payments or refunds. It never creates a charge or issues a refund.</p>{orders.results.map(o=><form key={o.id} method="post" action="/api/admin/operations"><input type="hidden" name="id" value={o.id}/><input type="hidden" name="action" value="reconcile"/><span>{o.kind} · {o.status} · {o.id} </span><button>Reconcile with Stripe</button></form>)}<form method="post" action="/api/admin/operations"><input name="action" type="hidden" value="recover-sponsors"/><button>Check abandoned sponsor reservations</button></form>
 <h2>Pending notifications</h2>{notifications.results.map(n=><form key={n.id} method="post" action="/api/admin/operations"><input type="hidden" name="id" value={n.id}/><input type="hidden" name="action" value="retry-email"/><span>{n.subject} · {n.attempts} attempts · {n.last_error||'Waiting'} </span><button>Retry delivery</button></form>)}
 <h2>Moderate jobs</h2><form method="get"><label>Title<input name="q" defaultValue={f.q}/></label><button>Search</button></form><p>Hiding an ad removes it from search. It does not cancel or refund billing; resolve the payment with the customer separately.</p>{jobs.results.map(j=><form key={j.id} method="post" action="/api/admin/operations"><input name="id" type="hidden" value={j.id}/><input name="q" type="hidden" value={f.q??''}/><span>{j.title} · {j.listed?'Visible':'Hidden'} </span><button name="action" value={j.moderation_hidden?'unhide-job':'hide-job'}>{j.moderation_hidden?'Remove moderation hold':'Hide job'}</button></form>)}</main>;
}
