import {redirect} from 'next/navigation';
import {platform,currentUser} from '../../../lib/platform';
import {JOB_ACCESS_SQL} from '../../../lib/product/job-access';
import {companyPlan} from '../../../lib/product/company-plans';
import {pricing} from '@gaming/shared';
import {EmployerShell} from '../../_components/employer-shell';
export const dynamic='force-dynamic';
export const metadata={title:'Job analytics',robots:{index:false,follow:false}};
export default async function Page({searchParams}:{searchParams:Promise<{job?:string}>}){const env=await platform(),user=await currentUser(env);if(!user)redirect('/employer/login?next=/employer/analytics');const id=(await searchParams).job??'',job=await env.DB.prepare(`SELECT j.company_id,j.title FROM jobs j JOIN employer_listings l ON l.job_id=j.id WHERE j.id=? AND j.commercial_origin IN ('native','native_ats') AND ${JOB_ACCESS_SQL}`).bind(id,user.id,user.id).first<{company_id:string;title:string}>(),plan=job?await companyPlan(env.DB,job.company_id):null;if(!job||!plan)return <EmployerShell title="Job analytics"><p>Select your own native job. An active annual company plan is required.</p></EmployerShell>;const counts=await env.DB.prepare("SELECT type,COUNT(DISTINCT CASE WHEN type='view' THEN substr(created_at,1,10)||COALESCE(session_hash,id) ELSE id END) n FROM job_events WHERE job_id=? AND created_at>=? GROUP BY type").bind(id,new Date(Date.now()-30*86400000).toISOString()).all<{type:string;n:number}>(),sources=await env.DB.prepare("SELECT COALESCE(referrer_group,'direct') source,COUNT(DISTINCT substr(created_at,1,10)||COALESCE(session_hash,id)) n FROM job_events WHERE job_id=? AND type='view' AND created_at>=? GROUP BY referrer_group").bind(id,new Date(Date.now()-30*86400000).toISOString()).all<{source:string;n:number}>();const daily=await env.DB.prepare("SELECT substr(created_at,1,10) day,COUNT(DISTINCT CASE WHEN type='view' THEN session_hash END) views,SUM(type='application') applications FROM job_events WHERE job_id=? AND created_at>=? GROUP BY day ORDER BY day").bind(id,new Date(Date.now()-30*86400000).toISOString()).all<{day:string;views:number;applications:number}>();const count=(type:string)=>counts.results.find(r=>r.type===type)?.n??0;return <EmployerShell title={'Analytics: '+job.title}><p>Last 30 days · Native listing activity</p><p>{count('view')} daily unique views · {count('application')} applications</p>{pricing.plans[plan.tier].analytics?<><p>{count('apply_click')} apply clicks</p><p>View-to-application conversion: {count('view')?((count('application')/count('view'))*100).toFixed(1):'0'}%</p><ul>{sources.results.map(r=><li key={r.source}>{r.source}: {r.n}</li>)}</ul><table><caption>Daily activity over the last 30 days</caption><thead><tr><th>Day</th><th>Unique views</th><th>Applications</th></tr></thead><tbody>{daily.results.map(d=><tr key={d.day}><td>{d.day}</td><td>{d.views} <meter min={0} max={Math.max(1,...daily.results.map(r=>r.views))} value={d.views}/></td><td>{d.applications}</td></tr>)}</tbody></table></>:<p>Growth and above include daily breakdowns, clicks and traffic sources.</p>}</EmployerShell>;}
