import {requireTenantId} from '../../../lib/tenant';
import {normalizeCompanyName} from '@gaming/shared';
import {platform,sameOrigin,httpUrl} from '../../../lib/platform';
import {adminUser} from '../../../lib/admin';
export async function POST(request:Request){if(!sameOrigin(request))return new Response('Forbidden',{status:403});const env=await platform();if(!await adminUser(env,request))return new Response('Forbidden',{status:403});const f=await request.formData(),action=String(f.get('action')||'');
 if(action==='recruiter'){const status=String(f.get('status'));if(!['verified','rejected'].includes(status))return new Response('Invalid status',{status:400});await env.DB.prepare('UPDATE recruiter_accounts SET status=? WHERE user_id=?').bind(status,String(f.get('id'))).run();}
 else if(action==='price'){const price=Number(f.get('price'));if(!Number.isInteger(price)||price<1||price>100000)return new Response('Invalid USD price',{status:400});await env.DB.prepare("UPDATE marketplace_settings SET value=? WHERE key='recruiter_price_cents'").bind(String(price*100)).run();}
 else if(action==='support'){const reply=String(f.get('reply')??'').trim();if(!reply||reply.length>10000)return new Response('Invalid reply',{status:400});await env.DB.prepare("UPDATE support_requests SET reply=?,status='answered' WHERE id=?").bind(reply,String(f.get('id'))).run();await env.DB.prepare("INSERT OR IGNORE INTO notification_outbox(id,user_id,kind,subject,body,destination_path,created_at) SELECT ?,user_id,'support_reply','Your support request has a reply','Sign in to read our reply to your support request.','/support',? FROM support_requests WHERE id=?").bind('support:'+String(f.get('id'))+':'+crypto.randomUUID(),new Date().toISOString(),String(f.get('id'))).run();}
 else if(action==='source'){const name=String(f.get('name')??'').trim(),url=httpUrl(f.get('url'));if(name.length<2||name.length>160||!url)return new Response('Invalid source',{status:400});const u=new URL(url);if(u.protocol!=='https:'||u.hostname==='localhost'||!u.hostname.includes('.')||/^[\d.:\[\]]+$/.test(u.hostname))return new Response('Use a public HTTPS career page',{status:400});let ats:string|null=null,slug:string|null=null;const bits=u.pathname.split('/').filter(Boolean);if(['boards.greenhouse.io','job-boards.greenhouse.io'].includes(u.hostname)){ats='greenhouse';slug=bits[0]??null;}else if(u.hostname==='jobs.lever.co'){ats='lever';slug=bits[0]??null;}else if(u.hostname==='jobs.ashbyhq.com'){ats='ashby';slug=bits[0]??null;}if(ats&&!slug)return new Response('Include the company board name',{status:400});const tenant=await requireTenantId(env.DB);if(!tenant)return new Response('Tenant unavailable',{status:503});await env.DB.prepare(`INSERT INTO companies(id,tenant_id,name,name_norm,domain,career_url,ats_type,ats_slug,created_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(tenant_id,name_norm) DO UPDATE SET career_url=excluded.career_url,ats_type=excluded.ats_type,ats_slug=excluded.ats_slug`).bind(crypto.randomUUID(),tenant,name,normalizeCompanyName(name),u.hostname,url,ats,slug,new Date().toISOString()).run();}
 else return new Response('Invalid action',{status:400});
 return Response.redirect(new URL('/admin',request.url),303);
}
