import {slugTitle} from '@gaming/shared';
import {platform,sameOrigin} from '../../../../lib/platform';
import {adminUser} from '../../../../lib/admin';
import {requireTenantId} from '../../../../lib/tenant';
export async function POST(request:Request){if(!sameOrigin(request))return new Response('Forbidden',{status:403});const env=await platform(),admin=await adminUser(env,request);if(!admin)return new Response('Not found',{status:404});const f=await request.formData(),id=String(f.get('id')??''),action=String(f.get('action')),name=String(f.get('name')??'').trim(),slug=slugTitle(name),reason=String(f.get('reason')??'').trim(),aliases=String(f.get('aliases')??'').split('\n').map(s=>s.trim()).filter(Boolean),at=new Date().toISOString();try{if(reason.length<10||reason.length>2000)throw Error('Record your reason.');
 if(action==='merge'){const target=String(f.get('target')),source=await env.DB.prepare('SELECT name,aliases_json FROM skills WHERE id=?').bind(id).first<{name:string;aliases_json:string}>(),destination=await env.DB.prepare("SELECT name,aliases_json FROM skills WHERE id=? AND status='active'").bind(target).first<{name:string;aliases_json:string}>();if(!source||!destination||target===id)throw Error('Choose distinct existing source and active destination skills');const merged=[...new Set([...JSON.parse(destination.aliases_json),source.name,...JSON.parse(source.aliases_json)])];await env.DB.batch([
 env.DB.prepare('INSERT OR IGNORE INTO candidate_skills SELECT user_id,? FROM candidate_skills WHERE skill_id=?').bind(target,id),env.DB.prepare('DELETE FROM candidate_skills WHERE skill_id=?').bind(id),env.DB.prepare("INSERT INTO job_skills SELECT job_id,?,kind FROM job_skills WHERE skill_id=? ON CONFLICT(job_id,skill_id) DO UPDATE SET kind=CASE WHEN job_skills.kind='required' OR excluded.kind='required' THEN 'required' ELSE 'preferred' END").bind(target,id),env.DB.prepare('DELETE FROM job_skills WHERE skill_id=?').bind(id),env.DB.prepare("UPDATE native_listing_details SET input_json=json_set(input_json,'$.requiredSkillIds',json((SELECT json_group_array(DISTINCT CASE WHEN value=? THEN ? ELSE value END) FROM json_each(input_json,'$.requiredSkillIds'))),'$.preferredSkillIds',json((SELECT json_group_array(DISTINCT CASE WHEN value=? THEN ? ELSE value END) FROM json_each(input_json,'$.preferredSkillIds')))) WHERE EXISTS(SELECT 1 FROM json_each(input_json,'$.requiredSkillIds') WHERE value=?) OR EXISTS(SELECT 1 FROM json_each(input_json,'$.preferredSkillIds') WHERE value=?)").bind(id,target,id,target,id,id),env.DB.prepare("UPDATE native_listing_details SET input_json=json_set(input_json,'$.preferredSkillIds',json((SELECT json_group_array(value) FROM json_each(input_json,'$.preferredSkillIds') WHERE value NOT IN(SELECT value FROM json_each(input_json,'$.requiredSkillIds'))))) WHERE EXISTS(SELECT 1 FROM json_each(input_json,'$.requiredSkillIds') WHERE value=?)").bind(target),env.DB.prepare("UPDATE skills SET status='rejected' WHERE id=?").bind(id),env.DB.prepare('UPDATE skills SET aliases_json=? WHERE id=?').bind(JSON.stringify(merged),target)]);}
 else if(action==='reject')await env.DB.prepare("UPDATE skills SET status='rejected' WHERE id=?").bind(id).run();
 else if(action==='skill'||action==='benefit'){if(name.length<2||name.length>100||aliases.length>100||aliases.some(a=>a.length>100))throw Error('Check the name and aliases.');const others=action==='skill'?await env.DB.prepare('SELECT label AS name,aliases_json FROM benefits').bind().all<{name:string;aliases_json:string}>():await env.DB.prepare('SELECT name,aliases_json FROM skills').bind().all<{name:string;aliases_json:string}>(),names=new Set([name,...aliases].map(n=>slugTitle(n)));if(others.results.some(o=>[o.name,...JSON.parse(o.aliases_json)].some(n=>names.has(slugTitle(n)))))throw Error('Skills and benefits cannot overlap, including aliases.');if(action==='skill')await env.DB.prepare("INSERT INTO skills(id,slug,name,category,aliases_json,status,created_at) VALUES(?,?,?,?,?,'active',?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,category=excluded.category,aliases_json=excluded.aliases_json,status='active'").bind(id||'skill:'+slug,slug,name,String(f.get('category')??'other').slice(0,80),JSON.stringify(aliases),at).run();else await env.DB.prepare('INSERT INTO benefits(slug,label,aliases_json) VALUES(?,?,?) ON CONFLICT(slug) DO UPDATE SET label=excluded.label,aliases_json=excluded.aliases_json').bind(id||slug,name,JSON.stringify(aliases)).run();}
 else throw Error('Unknown action');await env.DB.prepare('INSERT INTO product_admin_audit VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),await requireTenantId(env.DB),admin.id,'taxonomy:'+action,id||slug,reason,at).run();return Response.redirect(new URL('/admin/references',request.url),303);}catch(error){return new Response(error instanceof Error?error.message:'Update failed',{status:400});}}
