import {talentReadAllowance} from '../../../lib/product/operations';
import {talentCompany,talentProfileAccess} from '../../../lib/product/talent';
import {ProfileViewTracker} from '../../_components/product/view-tracker';
import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {platform,currentUser} from '../../../lib/platform';
import {candidateDetails,candidatePremium,publicCandidate} from '../../../lib/product/candidates';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{id:string}>}){const {id}=await params,env=await platform(),p=await env.DB.prepare('SELECT public_profile,handle FROM profiles WHERE handle=? OR user_id=?').bind(id,id).first<{public_profile:number;handle:string|null}>();return {title:'Candidate profile',robots:{index:!!p?.public_profile,follow:!!p?.public_profile},alternates:{canonical:'/talent/'+(p?.handle??id)}};}
export default async function TalentPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params,env=await platform(),user=await currentUser(env),row=await env.DB.prepare('SELECT user_id,handle FROM profiles WHERE (handle=? OR user_id=?)').bind(id,id).first<{user_id:string;handle:string|null}>();if(!row||!await talentProfileAccess(env.DB,user?.id??'',row.user_id))notFound();if(row.handle&&id!==row.handle)redirect('/talent/'+row.handle);
 if(user&&user.id!==row.user_id&&await talentCompany(env.DB,user.id)&&!await talentReadAllowance(env.DB,user.id,'profile',row.user_id))return <main className="container"><h1>Profile access limit reached</h1><p>Please pause and try again later.</p></main>;
 const details=await candidateDetails(env.DB,row.user_id),p=publicCandidate(details)!;
 const premium=await candidatePremium(env.DB,row.user_id);const featured=details.profile?.public_profile&&details.profile?.featured_opt_in&&!!await env.DB.prepare("SELECT user_id FROM featured_members WHERE user_id=? AND date=date('now')").bind(row.user_id).first();
 return <main className="container container--content stack"><ProfileViewTracker candidateId={row.user_id}/><h1>{p.name||'Web3 candidate'}</h1>{p.photo?<img src={p.photo} alt="Profile photo" width={96} height={96}/>:null}<p>{p.headline}</p><p>{p.location} · {p.availability.replaceAll('_',' ')}</p><p>{featured?'Featured member today · ':''}{premium?'Premium · ':''}{p.verified?'Verified':''}{p.openToCrypto?' · Open to crypto pay':''}</p><p style={{whiteSpace:'pre-wrap'}}>{p.bio}</p><h2>Skills</h2><p>{p.skills.map(s=>s.name).join(' · ')}</p><h2>Languages</h2><p>{p.languages.map(l=>l.name+' '+l.level).join(' · ')}</p><h2>Experience</h2>{p.experience.map(e=><article key={e.id}><h3>{e.title} · {e.company}</h3><p>{e.start_date} — {e.end_date||'Present'}</p><p>{e.description}</p></article>)}<h2>Links</h2>{p.links.map(l=><a key={l.kind} href={l.url} rel="nofollow noopener noreferrer" target="_blank">{l.kind}</a>)}<p><Link href={'/dashboard/talent?candidate='+encodeURIComponent(row.user_id)}>Invite this candidate to apply</Link></p>{details.profile?.public_profile?<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Person',name:p.name,description:p.headline,url:(env.SITE_URL??'')+'/talent/'+p.handle,sameAs:p.links.map(l=>l.url)}).replace(/</g,'\\u003c')}}/>:null}</main>;
}
