import Link from 'next/link';
import {redirect} from 'next/navigation';
import {money} from '@gaming/shared';
import {platform,currentUser} from '../../../lib/platform';
import {productOrder,reconcileProductOrder,type ProductOrder} from '../../../lib/product/billing';
import {BillingAction} from './purchase-button';
export async function ProductBillingPage({employer,orderId}:{employer:boolean;orderId?:string}){
 const env=await platform(),user=await currentUser(env);if(!user)redirect((employer?'/employer/login':'/login')+'?next='+encodeURIComponent(employer?'/employer/billing':'/account/billing'));
 let notice='';if(orderId){const order=await productOrder(env.DB,orderId);if(order?.user_id===user.id&&order.status==='pending'&&order.stripe_session_id)try{await reconcileProductOrder(env,order);}catch{notice='Payment confirmation is still pending. Use Check payment to retry.';}}
 const orders=await env.DB.prepare(`SELECT * FROM product_orders WHERE user_id=? AND ${employer?"kind IN ('company_plan','invite_pack','extension')":"kind IN ('candidate_premium','verification')"} ORDER BY created_at DESC LIMIT 100`).bind(user.id).all<ProductOrder>();
 const subscriptions=await env.DB.prepare(`SELECT status,renews_at,cancel_at_period_end FROM ${employer?'company_plans WHERE owner_user_id':'candidate_subscriptions WHERE user_id'}=?`).bind(user.id).all<{status:string;renews_at:string;cancel_at_period_end:number}>();
 const invoices=await env.DB.prepare('SELECT i.id,i.hosted_url,i.period_start,i.period_end,i.amount_paid FROM product_subscription_invoices i JOIN product_orders o ON o.id=i.order_id WHERE o.user_id=? ORDER BY i.period_start DESC LIMIT 100').bind(user.id).all<{id:string;hosted_url:string|null;period_start:string;period_end:string;amount_paid:number}>();
 const jobOrders=employer?(await env.DB.prepare("SELECT id,kind,status,total_cents,stripe_customer_id FROM employer_orders WHERE user_id=? ORDER BY created_at DESC LIMIT 100").bind(user.id).all<{id:string;kind:string;status:string;total_cents:number;stripe_customer_id:string|null}>()).results:[];
 const claims=employer?(await env.DB.prepare('SELECT o.id,o.status,o.total_cents,c.name FROM company_claim_orders o JOIN companies c ON c.id=o.company_id WHERE o.user_id=? ORDER BY o.created_at DESC LIMIT 100').bind(user.id).all<{id:string;status:string;total_cents:number;name:string}>()).results:[];
 return <main className="container container--content stack"><h1>{employer?'Company billing':'Your billing'}</h1><p><Link href="/pricing">Plans and prices</Link> · <Link href={employer?'/employer':'/account/profile'}>Dashboard</Link></p>{subscriptions.results.map((s,i)=><p key={i}>Subscription {s.status} · {s.cancel_at_period_end?'Ends':'Renews'} {s.renews_at.slice(0,10)}</p>)}{notice?<p role="status">{notice}</p>:null}{!orders.results.length?<p>No purchases yet.</p>:orders.results.map(order=><article key={order.id} className="panel"><h2>{order.kind.replaceAll('_',' ')} · {order.choice}</h2><p>{money(order.total_cents)} · {order.status}</p>{order.status==='pending'?<BillingAction id={order.id} action="resume" label="Resume checkout"/>:null}{order.status==='pending'&&order.stripe_session_id?<BillingAction id={order.id} action="reconcile" label="Check payment"/>:null}{order.stripe_customer_id?<BillingAction id={order.id} action="portal" label="Payment methods and invoices"/>:null}{order.stripe_subscription_id?<BillingAction id={order.id} action="cancel" label="Cancel renewal"/>:null}{order.kind==='verification'&&order.status==='paid'?<Link href="/account/verification">Submit verification evidence</Link>:null}</article>)}{employer?<section><h2>Job posts and page claims</h2>{jobOrders.map(o=><article key={o.id}><p>{o.kind} · {money(o.total_cents)} · {o.status}</p><Link href={'/employer/purchase?order='+o.id}>Order details</Link>{o.stripe_customer_id?<form action="/api/employer/manage" method="post"><input name="id" type="hidden" value={o.id}/><button name="action" value="billing">Invoice and billing portal</button></form>:null}</article>)}{claims.map(o=><p key={o.id}>Page claim: {o.name} · {money(o.total_cents)} · {o.status}</p>)}</section>:null}<h2>Subscription invoices</h2>{invoices.results.map(i=><p key={i.id}>{i.period_start.slice(0,10)} — {i.period_end.slice(0,10)} · {money(i.amount_paid)} {i.hosted_url?.startsWith('https://invoice.stripe.com/')?<a href={i.hosted_url} rel="noopener noreferrer">Invoice</a>:null}</p>)}</main>;
}
