'use client';
import {useState,type FormEvent} from 'react';
import {LANGUAGE_LEVELS,UTC_OFFSETS,formatUtcOffset} from '@gaming/shared';
import type {CandidateDetails} from '../../../lib/product/candidates';
import {ReferencePicker,type ReferenceChoice} from './reference-picker';
export function CandidateProfileForm({details,countries,name}:{details:CandidateDetails;countries:{code:string;name:string}[];name:string}){
 const p=details.profile,[skills,setSkills]=useState<ReferenceChoice[]>(details.skills),[city,setCity]=useState<ReferenceChoice[]>(details.city?[details.city]:[]),[languages,setLanguages]=useState(details.languages),[remote,setRemote]=useState(!details.city),[experiences,setExperiences]=useState(details.experience.map(e=>({company:e.company,title:e.title,startDate:e.start_date??'',endDate:e.end_date??'',description:e.description??''}))),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(saving)return;setSaving(true);setMessage('');const f=new FormData(event.currentTarget),value=(key:string)=>String(f.get(key)??'');
  try{const response=await fetch('/api/product/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({handle:value('handle'),displayName:value('displayName'),headline:value('headline'),bio:value('bio'),cityId:remote?null:city[0]?.id??null,countryCode:value('countryCode'),utcOffset:value('utcOffset')===''?null:Number(value('utcOffset')),availability:value('availability'),workArrangement:value('workArrangement'),openToCrypto:f.has('openToCrypto'),publicProfile:f.has('publicProfile'),discoverable:f.has('discoverable'),featuredOptIn:f.has('featuredOptIn'),skillIds:skills.map(s=>s.id),languages:languages.map(l=>({code:l.code,level:l.level})),links:['github','x','linkedin','portfolio'].filter(kind=>value(kind)).map(kind=>({kind,url:value(kind)})),experience:experiences})});const data=await response.json();if(!response.ok)throw Error(data.error);setMessage(`Profile saved. ${data.completeness}% complete.`);}catch(error){setMessage(error instanceof Error?error.message:'Could not save profile.');}finally{setSaving(false);}}
 return <form className="stack" onSubmit={submit}>
  <label>Name<input name="displayName" required maxLength={100} defaultValue={p?.display_name??name}/></label>
  <label>Profile handle<input name="handle" required pattern="[a-z][a-z0-9-]{2,39}" minLength={3} maxLength={40} defaultValue={p?.handle??''}/></label>
  <label>Headline<input name="headline" required maxLength={80} defaultValue={p?.headline??p?.target_role??''}/></label>
  <label>About you<textarea name="bio" maxLength={3000} defaultValue={p?.bio??''}/></label>
  <p>Social profiles and portfolio links are welcome. Keep email, phone numbers and direct contact details out of your public text.</p>
  <label><input type="checkbox" checked={remote} onChange={e=>setRemote(e.target.checked)}/>Remote from a country</label>
  {remote?<label>Country<select name="countryCode" required defaultValue={p?.country_code??''}><option value="">Choose country</option>{countries.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label>:<ReferencePicker label="City" kind="cities" value={city} onChange={setCity} required/>}
  <label>Time zone<select name="utcOffset" defaultValue={p?.utc_offset??''}><option value="">Choose UTC offset</option>{UTC_OFFSETS.map(o=><option key={o} value={o}>{formatUtcOffset(o)}</option>)}</select></label>
  <label>Availability<select name="availability" defaultValue={p?.availability??'open_to_work'}><option value="open_to_work">Open to work</option><option value="open_to_contracts">Open to contracts</option><option value="not_looking">Not looking</option></select></label>
  <label>Preferred work arrangement<select name="workArrangement" defaultValue={p?.remote_pref??'remote'}><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="onsite">On-site</option></select></label>
  <label><input name="openToCrypto" type="checkbox" defaultChecked={!!p?.open_to_crypto}/>Open to being paid in crypto</label>
  <ReferencePicker label="Skills (up to 30)" kind="skills" value={skills} onChange={setSkills} max={30}/>
  <ReferencePicker label="Languages" kind="languages" value={languages.map(l=>({id:l.code,name:l.name}))} onChange={items=>setLanguages(items.map(item=>languages.find(l=>l.code===item.id)??{code:String(item.id),name:item.name,level:'B2'}))} max={20}/>
  {languages.map(l=><label key={l.code}>{l.name} level<select value={l.level} onChange={e=>setLanguages(items=>items.map(i=>i.code===l.code?{...i,level:e.target.value}:i))}>{LANGUAGE_LEVELS.map(level=><option key={level}>{level}</option>)}</select></label>)}
  <fieldset><legend>Experience</legend>{experiences.map((entry,index)=><div className="panel stack" key={index}>{(['company','title','startDate','endDate','description'] as const).map(key=><label key={key}>{({company:'Company',title:'Role',startDate:'Start month',endDate:'End month (leave empty for current role)',description:'Description'})[key]}<input type={key.endsWith('Date')?'month':'text'} maxLength={key==='description'?1200:160} required={key==='company'||key==='title'} value={entry[key]} onChange={e=>setExperiences(items=>items.map((item,i)=>i===index?{...item,[key]:e.target.value}:item))}/></label>)}<button type="button" onClick={()=>setExperiences(items=>items.filter((_,i)=>i!==index))}>Remove experience</button></div>)}<button type="button" disabled={experiences.length>=30} onClick={()=>setExperiences(items=>[...items,{company:'',title:'',startDate:'',endDate:'',description:''}])}>Add experience</button></fieldset>
  {['github','x','linkedin','portfolio'].map(kind=><label key={kind}>{kind==='x'?'X':kind[0].toUpperCase()+kind.slice(1)}<input name={kind} type="url" placeholder="https://" defaultValue={details.links.find(l=>l.kind===kind)?.url??''}/></label>)}
  <fieldset><legend>Privacy and visibility</legend><label><input name="publicProfile" type="checkbox" defaultChecked={p?!!p.public_profile:true}/>Public profile (search engines can index it)</label><label><input name="discoverable" type="checkbox" defaultChecked={p?!!p.talent_pool_opt_in:true}/>Discoverable by recruiters</label><label><input name="featuredOptIn" type="checkbox" defaultChecked={p?!!p.featured_opt_in:true}/>Eligible for Featured Member of the Day when Premium</label></fieldset>
  <button disabled={saving}>{saving?'Saving…':'Save profile'}</button><p role="status">{message}</p>
 </form>;
}
