import Link from 'next/link';
import {platform,currentUser} from '../../../lib/platform';
import {requireTenantId} from '../../../lib/tenant';
import {loadProductFlags} from '../../../lib/product/flags';
import {companyReviewSummary,readableCompanyReviews,reviewReadAccess} from '../../../lib/product/reviews';
import {canManageCompany,companyIsClaimed,companyAccountActive} from '../../../lib/product/company-claims';
import {companyMembership} from '../../../lib/product/company-plans';
import {candidatePremium} from '../../../lib/product/candidates';
import {publicCandidateText} from '@gaming/shared';
export async function CompanyReviews({companyId}:{companyId:string}){const env=await platform(),tenant=await requireTenantId(env.DB);if(!(await loadProductFlags(env.DB,tenant,env)).PRODUCT_REVIEWS)return null;const user=await currentUser(env),read=await reviewReadAccess(env.DB,tenant,user?.id??null),summary=await companyReviewSummary(env.DB,companyId),reviews=await readableCompanyReviews(env.DB,companyId,read),reply=user?(await canManageCompany(env.DB,tenant,user.id,companyId)||!!await companyMembership(env.DB,user.id,companyId)):false,claimed=await companyIsClaimed(env.DB,tenant,companyId),canReview=user&&claimed&&await candidatePremium(env.DB,user.id)&&!await companyAccountActive(env.DB,tenant,user.id);
 return <section className="stack"><h2>Company reviews</h2><p>{summary.count?`${summary.overall?.toFixed(1)} / 5 · ${summary.count} reviews`:'No published reviews yet.'}</p>{summary.count?<p>Paid on time: {summary.paidOnTime?.toFixed(1)} · Transparent process: {summary.transparentProcess?.toFixed(1)} · Would work again: {summary.wouldWorkAgain?.toFixed(1)}</p>:null}<ul>{summary.distribution.map(r=><li key={r.overall}>{r.overall} stars: {r.count}</li>)}</ul>{reviews.map(r=><article className="panel" key={r.id}><p>{r.overall} / 5 · {r.created_at.slice(0,10)}</p>{read?<><p>{publicCandidateText(r.author)}</p><p>{r.body}</p>{r.response?<blockquote><strong>Company response</strong><p>{r.response}</p></blockquote>:null}</>:<p><Link href="/account/premium">Go Premium to read reviews</Link>. Company accounts can also read review text.</p>}{reply?<form method="post" action="/api/product/reviews"><input type="hidden" name="reviewId" value={r.id}/><label>Company response<textarea name="body" minLength={10} maxLength={2000} required defaultValue={r.response??''}/></label><button name="action" value="respond">Publish response</button></form>:null}{user?<details><summary>Report this review</summary><form method="post" action="/api/product/reviews"><input type="hidden" name="reviewId" value={r.id}/><label>Reason<textarea name="reason" minLength={10} maxLength={2000} required/></label><button name="action" value="report">Send report to moderators</button></form></details>:null}</article>)}{canReview?<ReviewForm companyId={companyId}/>:<p>{claimed?'Only Premium candidates can submit a review, after their work evidence is verified.':'This company must claim its page before candidates can review it.'}</p>}</section>;
}
export function ReviewForm({companyId,review}:{companyId:string;review?:Record<string,any>}){return <form action="/api/product/reviews" method="post" encType="multipart/form-data" className="stack"><h3>{review?'Edit review':'Review this company'}</h3><input type="hidden" name="companyId" value={companyId}/>{review?<input type="hidden" name="reviewId" value={review.id}/>:null}{[['overall','Overall'],['paid_on_time','Paid on time'],['transparent_process','Transparent process'],['would_work_again','Would work with them again']].map(([key,label])=><label key={key}>{label}<select name={key} required defaultValue={review?.[key]??''}><option value="">Choose rating</option>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label>)}<label>Work relationship<select name="relationship" defaultValue={review?.relationship??'employee'}><option value="employee">Employee</option><option value="contract">Contractor</option><option value="bounty_grant">Bounty or grant work</option></select></label><label>Your review<textarea name="body" minLength={50} maxLength={1500} required defaultValue={review?.body??''}/></label><label><input type="checkbox" name="anonymous" value="1" defaultChecked={!!review?.is_anonymous}/>Publish anonymously</label>{!review?<><label>Private proof of employment or completed work<input name="evidence" type="file" accept="application/pdf,image/jpeg,image/png" required/></label><p>Only you and moderators can access this evidence. Your review will stay private until a moderator verifies that you worked for this company.</p></>:<p>Edits require moderation before they become public.</p>}<button name="action" value="submit">Submit for review</button></form>;}
