import {JOB_ACCESS_SQL} from '../../../lib/product/job-access';
import Link from 'next/link';
import {pricing,money} from '@gaming/shared';
import type {PlatformEnv} from '../../../lib/platform';
import {companyQuoteContext} from '../../../lib/product/company-plans';
import {PurchaseButton} from './purchase-button';
import {EmployerShell} from '../employer-shell';
export async function ProductEmployerDashboard({env,userId}:{env:PlatformEnv;userId:string}){
 const companies=await env.DB.prepare(`SELECT DISTINCT c.id,c.name FROM companies c WHERE EXISTS(SELECT 1 FROM company_purchase_entitlements e WHERE e.company_id=c.id AND e.user_id=? AND e.status='active') OR EXISTS(SELECT 1 FROM company_members m WHERE m.company_id=c.id AND m.user_id=?)`).bind(userId,userId).all<{id:string;name:string}>();
 const jobs=await env.DB.prepare(`SELECT j.*,l.closed_at,l.expires_at FROM jobs j JOIN employer_listings l ON l.job_id=j.id WHERE ${JOB_ACCESS_SQL} ORDER BY j.created_at DESC LIMIT 100`).bind(userId,userId).all<Record<string,any>>();
 const orders=await env.DB.prepare("SELECT id,status,total_cents FROM employer_orders WHERE user_id=? AND status IN ('pending','cancelled') ORDER BY created_at DESC LIMIT 30").bind(userId).all<{id:string;status:string;total_cents:number}>();
 const social=await env.DB.prepare(`SELECT s.job_id,s.channel,s.status,s.provider_id FROM social_outbox s JOIN jobs j ON j.id=s.job_id JOIN employer_listings l ON l.job_id=j.id WHERE ${JOB_ACCESS_SQL} ORDER BY s.created_at DESC LIMIT 300`).bind(userId,userId).all<{job_id:string;channel:string;status:string;provider_id:string|null}>();
 const allowances=await Promise.all(companies.results.map(async c=>({...c,...await companyQuoteContext(env.DB,userId,c.id,false)})));
 return <EmployerShell><p><Link href="/pricing">Annual plans</Link> · <Link href="/employer/claims">Company ownership and claim status</Link></p>{allowances.map(c=><section className="panel" key={c.id}><h2>{c.name}</h2><p>{c.context.plan?`${c.context.plan} · ${c.context.plan==='platinum'?Math.max(0,pricing.platinumFairUse.perYear-c.context.postsPublishedInPeriod)+' included posts remaining this year':c.context.availableCredits+' credits'} · ${c.context.activePosts} active or reserved posts`:'Pay as you go'}</p>{c.context.plan?<p>Extra posts: {money(pricing.plans[c.context.plan].extraPost)}. Unused credits expire at renewal.</p>:null}{c.context.plan==='platinum'?<Link href="/account/support">Priority support · 24 weekday hours</Link>:null}</section>)}<h2>Jobs</h2>{!jobs.results.length?<p>No published jobs yet.</p>:jobs.results.map(j=>{const active=j.listed&&!j.closed_at&&j.expires_at>new Date().toISOString(),early=active&&j.early_access_until>new Date().toISOString();return <article className="panel" key={j.id}><h3><Link href={j.confidential?'/private-jobs/'+encodeURIComponent(j.id):'/jobs/'+j.slug}>{j.title}</Link></h3><p>{j.confidential?'Confidential · ':''}{active?early?'Early Access':'Active':j.closed_at?'Closed':'Expired'} · Expires {j.expires_at?.slice(0,10)}</p>{j.pinned_until&&j.pinned_until>new Date().toISOString()?<p>Pinned until {j.pinned_until}</p>:null}<p><Link href={'/employer/jobs/'+encodeURIComponent(j.id)+'/edit'}>Edit</Link> · <Link href={'/employer/applications?job='+encodeURIComponent(j.id)}>Applications</Link> · <Link href={'/employer/analytics?job='+encodeURIComponent(j.id)}>Analytics</Link> · <Link href={'/employer/shortlist?job='+encodeURIComponent(j.id)}>Suggested candidates</Link> · <Link href={'/post-web3-job?repost='+encodeURIComponent(j.id)}>Repost</Link></p><ul>{social.results.filter(s=>s.job_id===j.id).map(s=>{const link=s.status==='sent'&&s.provider_id&&/^\d+$/.test(s.provider_id)?s.channel==='x'?'https://x.com/i/status/'+s.provider_id:s.channel==='telegram'&&/^@[A-Za-z0-9_]+$/.test(env.TELEGRAM_CHAT_ID??'')?'https://t.me/'+env.TELEGRAM_CHAT_ID!.slice(1)+'/'+s.provider_id:null:s.channel==='linkedin'&&s.provider_id?.startsWith('urn:li:')?'https://www.linkedin.com/feed/update/'+encodeURIComponent(s.provider_id):null;return <li key={s.channel}>{s.channel}: {link?<a href={link} rel="noopener noreferrer" target="_blank">View shared post</a>:s.status}</li>;})}</ul>{active?<form method="post" action="/api/product/company"><input type="hidden" name="jobId" value={j.id}/><button name="action" value="close">Close job</button>{j.plan_tier&&!j.bumps_used?<button name="action" value="bump">Use free bump</button>:null}</form>:null}{active?<PurchaseButton kind="extension" choice="30-days" payload={{jobId:j.id}} label="Extend 30 days"/>:null}</article>;})}<h2>Pending purchases</h2>{orders.results.map(o=><p key={o.id}><Link href={'/employer/purchase?order='+o.id}>{o.status} · {money(o.total_cents)}</Link></p>)}</EmployerShell>;
}
