import Link from 'next/link';
import type {PlatformEnv} from '../../../lib/platform';
import {JOB_ACCESS_SQL} from '../../../lib/product/job-access';
import {APPLICATION_STATUSES} from '../../../lib/jobs/candidate-applications';
import {EmployerShell} from '../employer-shell';
export async function ProductEmployerApplications({env,userId,filters}:{env:PlatformEnv;userId:string;filters:{job?:string;status?:string;score?:string;sort?:string}}){
 const clauses=[JOB_ACCESS_SQL,"a.status!='withdrawn'"],values:unknown[]=[userId,userId];if(filters.job){clauses.push('j.id=?');values.push(filters.job);}if(filters.status){clauses.push('a.status=?');values.push(filters.status);}
 const scoreAccess="EXISTS(SELECT 1 FROM company_plans p WHERE p.company_id=j.company_id AND p.status='active' AND p.renews_at>strftime('%Y-%m-%dT%H:%M:%fZ','now'))";
 if(filters.score){clauses.push(`(${scoreAccess} AND a.match_score>=?)`);values.push(Math.max(0,Math.min(100,Number(filters.score)||0)));}
 const premium="EXISTS(SELECT 1 FROM candidate_subscriptions s WHERE s.user_id=a.user_id AND s.status='active' AND s.renews_at>strftime('%Y-%m-%dT%H:%M:%fZ','now'))";
 const rows=await env.DB.prepare(`SELECT a.*,j.title,${premium} AS premium,${scoreAccess} AS score_access,(SELECT verified_at FROM profiles WHERE user_id=a.user_id) AS verified_at FROM job_applications a JOIN employer_listings l ON l.job_id=a.job_id JOIN jobs j ON j.id=a.job_id WHERE ${clauses.join(' AND ')} ORDER BY ${filters.sort==='score'?`CASE WHEN ${scoreAccess} THEN a.match_score ELSE 0 END DESC,${premium} DESC,`:''} a.created_at DESC LIMIT 200`).bind(...values).all<Record<string,any>>();
 return <EmployerShell title="Applications"><form><label>Job ID<input name="job" defaultValue={filters.job}/></label><label>Status<select name="status" defaultValue={filters.status}><option value="">All</option>{APPLICATION_STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><label>Minimum match score<input name="score" type="number" min={0} max={100} defaultValue={filters.score}/></label><label>Sort<select name="sort" defaultValue={filters.sort??'recent'}><option value="recent">Recent</option><option value="score">Match score</option></select></label><button>Filter</button></form>{filters.job?<a href={'/api/product/applications/export?job='+encodeURIComponent(filters.job)}>Export this job’s applications as CSV (annual plans)</a>:null}<form id="bulk-stage" action="/api/product/applications" method="post"><label>Update selected applications<select name="status">{APPLICATION_STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><button name="action" value="bulk">Update stage</button></form>{!rows.results.length?<p>No matching applications.</p>:rows.results.map(a=>{const snapshot=a.profile_snapshot_json?JSON.parse(a.profile_snapshot_json):null,breakdown=a.score_breakdown_json?JSON.parse(a.score_breakdown_json):null;return <article className="panel stack" key={a.id}><label><input type="checkbox" name="ids" value={a.id} form="bulk-stage"/>Select {a.name}</label><h2>{a.name} · {a.title}</h2><p>{a.premium?'Premium · ':''}{a.verified_at?'Verified · ':''}{a.status}</p>{a.score_access&&a.match_score!==null?<p>Match {a.match_score}% · {breakdown?.required}/{breakdown?.requiredTotal} required skills · {breakdown?.eligible?'Eligible':'Outside eligible countries/time zone'}</p>:null}<a href={'mailto:'+a.email}>{a.email}</a><p>{a.note}</p>{snapshot?<details><summary>Profile at application time</summary><p>{snapshot.headline} · {snapshot.location}</p><p>{snapshot.skills?.map((s:{name:string})=>s.name).join(', ')}</p><p>{snapshot.languages?.map((l:{name:string;level:string})=>l.name+' '+l.level).join(', ')}</p></details>:null}{a.cv_r2_key?<a href={'/api/applications/'+a.id+'/cv'}>Submitted CV</a>:null}<form action="/api/product/applications" method="post"><input type="hidden" name="ids" value={a.id}/><label>Stage<select name="status" defaultValue={a.status}>{APPLICATION_STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><label>Internal notes<textarea name="note" maxLength={4000} defaultValue={a.employer_note}/></label><button name="action" value="single">Save</button></form></article>;})}<Link href="/employer">Back to jobs</Link></EmployerShell>;
}
