import Link from 'next/link';
import {platform,currentUser} from '../../../lib/platform';
import {requireTenantId} from '../../../lib/tenant';
import {applicationState} from '../../../lib/product/applications';
import {loadProductFlags} from '../../../lib/product/flags';
import {companyReviewSummary} from '../../../lib/product/reviews';
import {EarlyAccessAction} from './early-countdown';
import {annualUsdSalarySql} from '../../../lib/product/job-projection';
import type {SalaryInsight} from '@gaming/shared';
export async function ProductApplyAction({jobId,href}:{jobId:string;href:string}){const env=await platform(),user=await currentUser(env),state=await applicationState(env.DB,await requireTenantId(env.DB),jobId,user?.id??null);if(!state||state.closed)return <button disabled>Job closed</button>;if(!state.native)return <Link className="button button--primary" href={href}>Apply now</Link>;if(state.application)return <Link href="/account/applications">Applied · View application</Link>;if(state.locked)return <EarlyAccessAction until={state.job.early_access_until!} jobId={jobId} loggedIn={!!user} next={href}/>;return <div>{!state.eligible?<p>Your profile is outside the listed eligibility; you can still apply.</p>:null}<Link className="button button--primary" href={href}>Apply now</Link></div>;}
export async function JobProductDetails({jobId}:{jobId:string}){const env=await platform(),tenant=await requireTenantId(env.DB),flags=await loadProductFlags(env.DB,tenant,env);const job=await env.DB.prepare(`SELECT j.company_id,j.hide_salary,j.commercial_origin,r.slug AS role_slug,${annualUsdSalarySql('min')} AS annual_min,${annualUsdSalarySql('max')} AS annual_max FROM jobs j LEFT JOIN job_roles r ON r.id=j.job_role_id WHERE j.id=? AND j.tenant_id=? AND j.confidential=0`).bind(jobId,tenant).first<{company_id:string;hide_salary:number;commercial_origin:string;role_slug:string|null;annual_min:number|null;annual_max:number|null}>();if(!job)return null;const review=flags.PRODUCT_REVIEWS?await companyReviewSummary(env.DB,job.company_id):null,stats=flags.PRODUCT_SALARY_INSIGHTS&&job.role_slug?(await env.DB.prepare("SELECT stats_json FROM salary_stats WHERE role_slug=? AND location_slug='all' AND as_of>=? ORDER BY as_of DESC LIMIT 1").bind(job.role_slug,new Date(Date.now()-2*86400000).toISOString().slice(0,10)).first<string>('stats_json')):null;const salary=stats?JSON.parse(stats) as SalaryInsight:null;return <section>{review?.count?<p>Company reviews: {review.overall?.toFixed(1)} / 5 ({review.count})</p>:null}{salary&&job.commercial_origin!=='aggregated'&&!job.hide_salary&&job.annual_min!==null&&job.annual_max!==null?<p>Salary midpoint is {((job.annual_min+job.annual_max)/2)>=salary.median?'at or above':'below'} the external market median of ${salary.median.toLocaleString('en-US')} annually. <Link href={'/salaries/'+job.role_slug}>View {salary.count} external salary observations</Link>.</p>:null}</section>;}
