import Link from 'next/link';
import {pricing,money} from '@gaming/shared';
import {platform} from '../../lib/platform';
import {requireTenantId} from '../../lib/tenant';
import {loadProductFlags} from '../../lib/product/flags';
import {CompanyPlanForm} from '../_components/product/company-plan-form';
export const dynamic='force-dynamic';
export const metadata={title:'Plans and job posting prices',description:'Web3 hiring plans, individual job posts and candidate Premium.',alternates:{canonical:'/pricing'}};
export default async function PricingPage(){const env=await platform(),flags=await loadProductFlags(env.DB,await requireTenantId(env.DB),env);if(!flags.PRODUCT_POSTING_V2)return <main className="container"><h1>Post a Web3 job</h1><p>Listings from {money(pricing.legacy.jobBase)}.</p><Link href="/post-web3-job">Configure a listing</Link></main>;return <main className="container container--content stack"><h1>Plans and pricing</h1><p>Job search is free. All prices below are in USD. Payments currently use Stripe sandbox.</p><h2>Single job · {money(pricing.jobPost.base)}</h2><p>{pricing.jobPost.durationDays} days online, company account and company claim included. Ownership is verified separately.</p><ul><li>Hide salary: {money(pricing.addons.hideSalary)}</li><li>Early Access for {pricing.addons.earlyAccess.hours} hours: {money(pricing.addons.earlyAccess.price)}</li>{Object.entries(pricing.addons.pin).map(([days,price])=><li key={days}>Pin {days} days: {money(price)}</li>)}</ul><Link href="/post-web3-job">Post a job</Link><p><Link href="/claim-company">Claim a company page</Link> without a job: {money(pricing.companyClaim)} once. Claim is included with a job or annual plan.</p>{flags.PRODUCT_COMPANY_PLANS?<><h2>Annual company plans</h2><table><thead><tr><th>Plan</th><th>Annual price</th><th>Posts</th><th>Extra post</th><th>Duration</th><th>Seats</th><th>Included pin</th></tr></thead><tbody>{Object.entries(pricing.plans).map(([tier,p])=><tr key={tier}><td>{tier}</td><td>{money(p.price)}</td><td>{p.posts??`${pricing.platinumFairUse.perYear}/year, ${pricing.platinumFairUse.maxActive} active`}</td><td>{money(p.extraPost)}</td><td>{p.durationDays} days</td><td>{p.seats??'Unlimited'}</td><td>{p.pinDays} days</td></tr>)}</tbody></table><p>Every plan includes a company badge, candidate match scores, CSV export and one bump per post. Growth adds hidden salaries and analytics. Scale adds 20 shortlist invitations per job, Hiring Now placement and one newsletter feature per month. Platinum adds Talent Search with 100 monthly invitations, ATS import, confidential jobs ({money(pricing.addons.confidential)} per job), priority support and newsletter inclusion for every public post.</p><p>Extra invitations: {pricing.talentExtraPack.invites} for {money(pricing.talentExtraPack.price)}. ATS overages stay in draft until you explicitly pay; they are never charged automatically.</p><CompanyPlanForm/></>:null}{flags.PRODUCT_CANDIDATE_PREMIUM?<><h2>Candidate Premium</h2><p>{money(pricing.candidate.premiumMonthly)}/month or {money(pricing.candidate.premiumAnnual)}/year. Early Access, company reviews, application updates, profile views and eligibility for Featured Member.</p><Link href="/account/premium">Get Premium</Link><p>Optional identity verification review: {money(pricing.candidate.verifiedBadge)} once. Verification requires manual approval and does not require Premium.</p></>:null}</main>;}
