import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {expect,it,vi} from 'vitest';
import Page from './page';
vi.mock('../../lib/platform',()=>({platform:async()=>({DB:{}})}));
vi.mock('../../lib/tenant',()=>({requireTenantId:async()=> 'tenant:gaming'}));
vi.mock('../../lib/product/flags',()=>({loadProductFlags:async()=>({PRODUCT_POSTING_V2:true,PRODUCT_COMPANY_PLANS:true,PRODUCT_CANDIDATE_PREMIUM:true})}));
vi.mock('../_components/product/company-plan-form',()=>({CompanyPlanForm:()=>null}));
vi.stubGlobal('React',React);
it('keeps search free and presents all current USD offers with explicit ATS overage consent',async()=>{const html=renderToStaticMarkup(await Page());expect(html).toContain('Job search is free');for(const price of ['$129','$150','$360','$575','$880','$1,500','$9.99','$79'])expect(html).toContain(price);expect(html).toContain('/post-web3-job');expect(html).toContain('never charged automatically');expect(html).toContain('sandbox');});
