"use client";
import {useEffect,useRef,useState} from 'react';
import {canRequestAds,type AdvertisingConfig,type TcfConsent} from '../../lib/advertising';
type AdWindow=Window&{adsbygoogle?:unknown[];__gpp?:(command:string,callback:(data:{eventName?:string;listenerId?:number;data?:unknown},success:boolean)=>void,parameter?:number)=>void;__tcfapi?:(command:string,version:number,callback:(data:TcfConsent&{listenerId?:number},success:boolean)=>void,parameter?:number)=>void;googlefc?:{callbackQueue:Array<Record<string,()=>void>>;showRevocationMessage?:()=>void;usstatesoptout?:{getInitialUsStatesOptOutStatus?:()=>number;openConfirmationDialog?:(callback:(confirmed:boolean)=>void)=>void}}};
let configPromise:Promise<AdvertisingConfig>|undefined;
export function NetworkAd(){const [config,setConfig]=useState<AdvertisingConfig>(),[allowed,setAllowed]=useState(false),[usAllowed,setUsAllowed]=useState(false),[failed,setFailed]=useState(false),[consentChanged,setConsentChanged]=useState(false),node=useRef<HTMLModElement>(null);
 useEffect(()=>{let active=true;configPromise??=fetch('/api/advertising').then(r=>r.json());configPromise.then(c=>{if(active&&c.mode!=='off')setConfig(c);}).catch(()=>{configPromise=undefined;});return()=>{active=false;};},[]);
 useEffect(()=>{if(!config)return;let active=true,listener:number|undefined,gppListener:number|undefined;const win=window as AdWindow;
  function subscribe(){win.__tcfapi?.('addEventListener',2,(data,success)=>{listener=data.listenerId;if(active)setAllowed(success&&canRequestAds(data,(navigator as Navigator&{globalPrivacyControl?:boolean}).globalPrivacyControl===true));});}
  win.googlefc??={callbackQueue:[]};win.googlefc.callbackQueue??=[];win.googlefc.callbackQueue.push({CONSENT_API_READY:subscribe});win.googlefc.callbackQueue.push({INITIAL_US_STATES_OPT_OUT_DATA_READY:()=>{const status=win.googlefc?.usstatesoptout?.getInitialUsStatesOptOutStatus?.();if(active)setUsAllowed(status===1||status===2);win.__gpp?.('addEventListener',(data,success)=>{gppListener=data.listenerId;if(active&&(!success||data.eventName==='sectionChange'||data.eventName==='error'||data.eventName==='signalStatus'&&data.data!=='ready')){setUsAllowed(false);setConsentChanged(true);}});}});
  if(!document.getElementById('nodework-cmp')){const script=document.createElement('script');script.id='nodework-cmp';script.async=true;script.src=config.cmpUrl;script.onerror=()=>setFailed(true);document.head.appendChild(script);}
  return()=>{active=false;if(gppListener!==undefined)win.__gpp?.('removeEventListener',()=>{},gppListener);if(listener!==undefined)win.__tcfapi?.('removeEventListener',2,()=>{},listener);};
 },[config]);
 useEffect(()=>{if(!allowed||!usAllowed||!config||!node.current)return;const win=window as AdWindow,element=node.current;
  const push=()=>{if(element.isConnected&&!element.dataset.adsbygoogleStatus){try{(win.adsbygoogle??=[]).push({});}catch{setFailed(true);}}};
  let script=document.getElementById('nodework-adsense') as HTMLScriptElement|null;
  if(!script){script=document.createElement('script');script.id='nodework-adsense';script.async=true;script.crossOrigin='anonymous';script.src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client='+config.publisher;script.addEventListener('load',push,{once:true});script.onerror=()=>setFailed(true);document.head.appendChild(script);}else push();
 },[allowed,usAllowed,config]);
 if(!config||failed)return null;
 return <aside aria-label="Advertisement">{consentChanged?<button type="button" onClick={()=>window.location.reload()}>Apply updated advertising preferences</button>:null}{allowed&&usAllowed?<><small>Advertisement</small><ins ref={node} className="adsbygoogle" style={{display:'block'}} data-ad-client={config.publisher} data-ad-slot={config.slot} data-ad-format="auto" data-full-width-responsive="true" data-adtest={config.mode==='test'?'on':undefined}/></>:null}<button type="button" onClick={()=>{setAllowed(false);const win=window as AdWindow;win.googlefc?.callbackQueue.push({CONSENT_DATA_READY:()=>win.googlefc?.showRevocationMessage?.()});}}>Advertising privacy choices</button><button type="button" onClick={()=>{setAllowed(false);setUsAllowed(false);const win=window as AdWindow;win.googlefc?.callbackQueue.push({CONSENT_DATA_READY:()=>win.googlefc?.usstatesoptout?.openConfirmationDialog?.(()=>window.location.reload())});}}>Do not sell or share</button></aside>;
}
