import {TalentExport} from '../_components/talent-export';
import Link from 'next/link';
import {EmployerShell} from '../_components/employer-shell';
import {redirect} from 'next/navigation';
import {platform,currentUser} from '../../lib/platform';
import {hasRecruiterAccess} from '../../lib/billing/marketplace';
import {MarketplaceForm} from '../_components/marketplace-form';
export const dynamic='force-dynamic';
export const metadata={title:'Recruiter access',robots:{index:false,follow:false}};
export default async function RecruiterPage(){const env=await platform(),user=await currentUser(env);if(!user)redirect('/employer/login?next=/recruiter');const account=await env.DB.prepare('SELECT company,website,status FROM recruiter_accounts WHERE user_id=?').bind(user.id).first<{company:string;website:string;status:string}>();const price=Number(await env.DB.prepare("SELECT value FROM marketplace_settings WHERE key='recruiter_price_cents'").bind().first<string>('value'));const access=await hasRecruiterAccess(env.DB,user.id);return <EmployerShell title="Recruiter access"><p>Search candidates by skill and location. Contact details and CVs are available for candidates who chose to share them with verified recruiters.</p><Link href="/hire">Browse talent</Link>{access?<p>Your access is active. <Link href="/hire">Find candidates</Link></p>:account?.status==='verified'?<>{price>=100?<MarketplaceForm kind="recruiter" price={price}/>:<p>Contact support to arrange access.</p>}</>:<><p>{account?`Verification: ${account.status}`:'Tell us about your company to request verification.'}</p><form className="commerce-form" method="post" action="/api/recruiter/register"><label>Company<input name="company" required maxLength={160} defaultValue={account?.company}/></label><label>Company website<input name="website" type="url" required defaultValue={account?.website}/></label><button>Request verification</button></form></>}{access?<><p><Link href="/recruiter/shortlist">Your shortlist</Link></p><TalentExport/></>:null}<Link href="/support">Contact support</Link></EmployerShell>;}
