ALTER TABLE product_invitations ADD COLUMN quota_period TEXT;
ALTER TABLE product_invitations ADD COLUMN pack_id TEXT REFERENCES talent_invite_packs(id);
CREATE INDEX idx_invitation_allowance ON product_invitations(company_id,source,quota_period);
CREATE TABLE social_outbox(id TEXT PRIMARY KEY,job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,channel TEXT NOT NULL CHECK(channel IN ('x','linkedin','telegram')),status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,retry_at TEXT,lease_token TEXT,lease_until TEXT,provider_id TEXT,last_error TEXT,created_at TEXT NOT NULL,sent_at TEXT,UNIQUE(job_id,channel));
CREATE TABLE newsletter_subscribers(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id) ON DELETE CASCADE,email TEXT NOT NULL UNIQUE,active INTEGER NOT NULL DEFAULT 1,unsubscribe_token TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL);
CREATE TABLE newsletter_editions(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id),week_start TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(tenant_id,week_start));
CREATE TABLE newsletter_jobs(edition_id TEXT NOT NULL REFERENCES newsletter_editions(id),job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,company_id TEXT NOT NULL REFERENCES companies(id),benefit_month TEXT,PRIMARY KEY(edition_id,job_id));
CREATE UNIQUE INDEX idx_monthly_newsletter_benefit ON newsletter_jobs(company_id,benefit_month) WHERE benefit_month IS NOT NULL;
CREATE TABLE newsletter_deliveries(edition_id TEXT NOT NULL REFERENCES newsletter_editions(id),subscriber_id TEXT NOT NULL REFERENCES newsletter_subscribers(id) ON DELETE CASCADE,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,retry_at TEXT,lease_token TEXT,lease_until TEXT,sent_at TEXT,last_error TEXT,PRIMARY KEY(edition_id,subscriber_id));
CREATE TABLE company_ats_integrations(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id),company_id TEXT NOT NULL UNIQUE REFERENCES companies(id),provider TEXT NOT NULL CHECK(provider IN ('greenhouse','lever','ashby')),board TEXT NOT NULL,mapping_json TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,confidential INTEGER NOT NULL DEFAULT 0,last_attempt_at TEXT,last_success_at TEXT,last_error TEXT,lease_token TEXT,lease_until TEXT,created_at TEXT NOT NULL);
CREATE TABLE company_ats_jobs(id TEXT PRIMARY KEY,integration_id TEXT NOT NULL REFERENCES company_ats_integrations(id),external_id TEXT NOT NULL,title TEXT NOT NULL,source_url TEXT NOT NULL,raw_json TEXT NOT NULL,posting_json TEXT,validation_error TEXT,status TEXT NOT NULL DEFAULT 'draft',job_id TEXT REFERENCES jobs(id),order_id TEXT REFERENCES employer_orders(id),seen_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(integration_id,external_id));
CREATE TABLE support_tickets(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id),user_id TEXT REFERENCES users(id) ON DELETE SET NULL,company_id TEXT REFERENCES companies(id),subject TEXT NOT NULL,body TEXT NOT NULL,priority INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'open',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE support_replies(id TEXT PRIMARY KEY,ticket_id TEXT NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,user_id TEXT REFERENCES users(id) ON DELETE SET NULL,body TEXT NOT NULL,created_at TEXT NOT NULL);

CREATE TABLE candidate_shortlists(job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,candidate_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,date TEXT NOT NULL,score INTEGER NOT NULL,rank INTEGER NOT NULL,PRIMARY KEY(job_id,candidate_id,date));
