import Link from 'next/link';
import {redirect} from 'next/navigation';
import {platform,currentUser} from '../../../lib/platform';
import {talentCompany} from '../../../lib/product/talent';
import {EmployerShell} from '../../_components/employer-shell';
import {AtsSettingsForm,SyncAtsButton} from '../../_components/product/ats-settings-form';
export const dynamic='force-dynamic';
export const metadata={title:'Company ATS integration',robots:{index:false,follow:false}};
export default async function Integrations({searchParams}:{searchParams:Promise<{company?:string}>}){const env=await platform(),user=await currentUser(env);if(!user)redirect('/employer/login');const company=await talentCompany(env.DB,user.id,(await searchParams).company);if(company?.tier!=='platinum')return <EmployerShell title="Careers integration"><p>Daily Greenhouse, Lever and Ashby imports are available with Platinum after company ownership is verified.</p><Link href="/pricing">View plans</Link></EmployerShell>;
 const integration=await env.DB.prepare('SELECT * FROM company_ats_integrations WHERE company_id=?').bind(company.company_id).first<Record<string,any>>(),m=integration?JSON.parse(integration.mapping_json):{};
 const [skills,regions,cities,languages]=await Promise.all([env.DB.prepare('SELECT id,name FROM skills WHERE id IN(SELECT value FROM json_each(?))').bind(JSON.stringify(m.requiredSkillIds??[])).all<{id:string;name:string}>(),env.DB.prepare('SELECT id,name FROM regions WHERE id IN(SELECT value FROM json_each(?))').bind(JSON.stringify(m.eligibility?.regionIds??[])).all<{id:string;name:string}>(),env.DB.prepare('SELECT id,name,region,country_code FROM reference_cities WHERE id IN(SELECT value FROM json_each(?))').bind(JSON.stringify(m.cityIds??[])).all<{id:number;name:string;region:string;country_code:string}>(),env.DB.prepare('SELECT code AS id,name FROM reference_languages WHERE code IN(SELECT value FROM json_each(?))').bind(JSON.stringify((m.languages??[]).map((l:{code:string})=>l.code))).all<{id:string;name:string}>()]);
 const jobs=integration?(await env.DB.prepare('SELECT id,title,status,validation_error,job_id FROM company_ats_jobs WHERE integration_id=? ORDER BY updated_at DESC LIMIT 200').bind(integration.id).all<{id:string;title:string;status:string;validation_error:string|null;job_id:string|null}>()).results:[];
 return <EmployerShell title={'Careers integration · '+company.name}><AtsSettingsForm companyId={company.company_id} initial={integration} choices={{skills:skills.results,regions:regions.results,cities:cities.results,languages:languages.results}}/>{integration?<><p>Last successful sync: {integration.last_success_at??'Not synced yet'}</p><p>{integration.last_error}</p><SyncAtsButton companyId={company.company_id}/></>:null}<h2>Imported jobs</h2>{jobs.map(j=><article key={j.id}><h3>{j.title}</h3><p>{j.status} · {j.validation_error}</p>{j.job_id?<Link href={'/employer/jobs/'+encodeURIComponent(j.job_id)+'/edit'}>Manage published job</Link>:<Link href={'/employer/integrations/drafts/'+j.id}>Complete fields and review publication</Link>}</article>)}</EmployerShell>;}
