import { FilterXSS, type IWhiteList } from "xss";

const jobDescriptionAllowList: IWhiteList = {
  a: ["href", "title", "target", "rel"],
  abbr: ["title"],
  address: [],
  article: [],
  aside: [],
  b: [],
  blockquote: ["cite"],
  br: [],
  caption: [],
  cite: [],
  code: [],
  col: ["span"],
  colgroup: ["span"],
  dd: [],
  del: ["datetime"],
  details: ["open"],
  div: [],
  dl: [],
  dt: [],
  em: [],
  figcaption: [],
  figure: [],
  footer: [],
  h1: [],
  h2: [],
  h3: [],
  h4: [],
  h5: [],
  h6: [],
  header: [],
  hr: [],
  i: [],
  img: ["src", "alt", "title", "width", "height", "loading"],
  ins: ["datetime"],
  kbd: [],
  li: [],
  mark: [],
  ol: [],
  p: [],
  pre: [],
  s: [],
  section: [],
  small: [],
  span: [],
  strong: [],
  sub: [],
  summary: [],
  sup: [],
  table: [],
  tbody: [],
  td: ["rowspan", "colspan"],
  tfoot: [],
  th: ["rowspan", "colspan", "scope"],
  thead: [],
  tr: [],
  u: [],
  ul: [],
};

const sanitizer = new FilterXSS({
  allowList: jobDescriptionAllowList,
  stripIgnoreTag: true,
  stripIgnoreTagBody: [
    "script",
    "style",
    "iframe",
    "object",
    "embed",
    "template",
  ],
  css: false,
});

export function sanitizeJobDescriptionHtml(descriptionHtml: string) {
  return sanitizer.process(descriptionHtml);
}
