import {publicCandidateText} from './candidates';
import type {ProductDatabase} from './notifications';
export type DistributionEnv={DB:ProductDatabase;SITE_URL?:string;SOCIAL_DELIVERY_ENABLED?:string;NEWSLETTER_DELIVERY_ENABLED?:string;X_USER_ACCESS_TOKEN?:string;LINKEDIN_ACCESS_TOKEN?:string;LINKEDIN_AUTHOR_URN?:string;LINKEDIN_VERSION?:string;TELEGRAM_BOT_TOKEN?:string;TELEGRAM_CHAT_ID?:string;EMAIL_FROM?:string;EMAIL:{send(message:{to:string;from:string;subject:string;text:string}):Promise<unknown>}};
const publicNative="j.confidential=0 AND j.listed=1 AND j.commercial_origin IN ('native','native_ats') AND j.expires_at>? AND c.listed=1";
export async function enqueueSocialPosts(db:ProductDatabase,tenantId:string,now=new Date()){
 if(!await db.prepare("SELECT name FROM feature_flags WHERE tenant_id=? AND name='PRODUCT_SOCIAL_SHARING' AND enabled=1").bind(tenantId).first())return;
 for(const channel of ['x','linkedin','telegram'])await db.prepare(`INSERT OR IGNORE INTO social_outbox(id,job_id,channel,created_at) SELECT j.id||':'||?,j.id,?,? FROM jobs j JOIN companies c ON c.id=j.company_id WHERE j.tenant_id=? AND ${publicNative} AND j.published_at>=?`).bind(channel,channel,now.toISOString(),tenantId,now.toISOString(),new Date(now.getTime()-7*86400000).toISOString()).run();
}
/** Every send is leased. A timeout after dispatch is marked uncertain for manual review, never blindly retried. */
export async function deliverSocialPosts(env:DistributionEnv,now=new Date()){
 if(env.SOCIAL_DELIVERY_ENABLED!=='true'||!env.SITE_URL)return;
 const at=now.toISOString(),rows=await env.DB.prepare("SELECT id,job_id,channel,attempts FROM social_outbox WHERE status IN ('pending','retry','unconfigured') AND (retry_at IS NULL OR retry_at<=?) AND (lease_until IS NULL OR lease_until<=?) AND attempts<8 ORDER BY created_at LIMIT 5").bind(at,at).all<{id:string;job_id:string;channel:string;attempts:number}>();
 for(const row of rows.results){const job=await env.DB.prepare(`SELECT j.title,j.slug,j.remote,CASE WHEN j.hide_salary=0 THEN j.salary_text ELSE NULL END salary,j.crypto_payment_available crypto,c.name FROM jobs j JOIN companies c ON c.id=j.company_id WHERE j.id=? AND ${publicNative}`).bind(row.job_id,at).first<{title:string;slug:string;name:string;remote:string;salary:string|null;crypto:number}>();if(!job){await env.DB.prepare("UPDATE social_outbox SET status='canceled' WHERE id=?").bind(row.id).run();continue;}
 const link=new URL('/jobs/'+job.slug,env.SITE_URL).href,text=`${job.title.slice(0,75)} at ${job.name.slice(0,35)}\n${job.remote}${job.salary?' · '+job.salary.slice(0,35):''}${job.crypto?' · Crypto pay':''}\n${link}\n#Web3Jobs`;
 let url='',body:unknown,headers:Record<string,string>={'Content-Type':'application/json'};
 if(row.channel==='x'&&env.X_USER_ACCESS_TOKEN){url='https://api.x.com/2/tweets';headers.Authorization='Bearer '+env.X_USER_ACCESS_TOKEN;body={text};}
 if(row.channel==='linkedin'&&env.LINKEDIN_ACCESS_TOKEN&&env.LINKEDIN_AUTHOR_URN&&/^urn:li:(organization|person):[\w-]+$/.test(env.LINKEDIN_AUTHOR_URN)&&/^\d{6}$/.test(env.LINKEDIN_VERSION??'')){url='https://api.linkedin.com/rest/posts';headers={...headers,Authorization:'Bearer '+env.LINKEDIN_ACCESS_TOKEN,'LinkedIn-Version':env.LINKEDIN_VERSION!,'X-Restli-Protocol-Version':'2.0.0'};body={author:env.LINKEDIN_AUTHOR_URN,commentary:text,visibility:'PUBLIC',distribution:{feedDistribution:'MAIN_FEED',targetEntities:[],thirdPartyDistributionChannels:[]},lifecycleState:'PUBLISHED',isReshareDisabledByAuthor:false};}
 if(row.channel==='telegram'&&env.TELEGRAM_BOT_TOKEN&&env.TELEGRAM_CHAT_ID){url='https://api.telegram.org/bot'+env.TELEGRAM_BOT_TOKEN+'/sendMessage';body={chat_id:env.TELEGRAM_CHAT_ID,text,link_preview_options:{is_disabled:true}};}
 if(!url){await env.DB.prepare("UPDATE social_outbox SET status='unconfigured',last_error='Provider credentials or API version are missing',retry_at=? WHERE id=?").bind(new Date(now.getTime()+3600000).toISOString(),row.id).run();continue;}
 const token=crypto.randomUUID(),claim=await env.DB.prepare("UPDATE social_outbox SET lease_token=?,lease_until=?,status='sending',attempts=attempts+1 WHERE id=? AND status IN ('pending','retry','unconfigured') AND (lease_until IS NULL OR lease_until<=?)").bind(token,new Date(now.getTime()+120000).toISOString(),row.id,at).run();if(!(claim as {meta?:{changes?:number}}).meta?.changes)continue;
 try{const response=await fetch(url,{method:'POST',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(20000),redirect:'error'});if(!response.ok){await env.DB.prepare("UPDATE social_outbox SET status=?,last_error=?,retry_at=?,lease_until=NULL WHERE id=? AND lease_token=?").bind(response.status===429?'retry':response.status>=500?'uncertain':'failed','Provider HTTP '+response.status,new Date(now.getTime()+Math.min(86400000,300000*2**row.attempts)).toISOString(),row.id,token).run();continue;}
 const data=await response.json().catch(()=>({})) as {data?:{id:string};result?:{message_id:number};ok?:boolean};if(data.ok===false)throw Error('Provider response needs review');const providerId=data.data?.id??String(data.result?.message_id??response.headers.get('x-restli-id')??'accepted');await env.DB.prepare("UPDATE social_outbox SET status='sent',provider_id=?,sent_at=?,lease_until=NULL,last_error=NULL WHERE id=? AND lease_token=?").bind(providerId,at,row.id,token).run();
 }catch{await env.DB.prepare("UPDATE social_outbox SET status='uncertain',last_error='Delivery outcome unknown; inspect the provider before resubmitting',lease_until=NULL WHERE id=? AND lease_token=?").bind(row.id,token).run();}}
 await env.DB.prepare("UPDATE social_outbox SET status='uncertain',last_error='Worker stopped after dispatch; verify provider before retry',lease_until=NULL WHERE status='sending' AND lease_until<=?").bind(at).run();
}
export async function prepareWeeklyNewsletter(db:ProductDatabase,tenantId:string,now=new Date()){
 if(!await db.prepare("SELECT name FROM feature_flags WHERE tenant_id=? AND name='PRODUCT_NEWSLETTER' AND enabled=1").bind(tenantId).first())return;
 const monday=new Date(now);monday.setUTCDate(monday.getUTCDate()-(monday.getUTCDay()+6)%7);const week=monday.toISOString().slice(0,10),edition='newsletter:'+tenantId+':'+week,at=now.toISOString(),month=at.slice(0,7);
 if(await db.prepare('SELECT id FROM newsletter_editions WHERE id=?').bind(edition).first())return;
 // Oldest unfeatured Platinum posts are carried forward; Scale consumes one slot per month.
 await db.batch([
 db.prepare('INSERT OR IGNORE INTO newsletter_editions VALUES(?,?,?,?)').bind(edition,tenantId,week,at),
 db.prepare(`INSERT OR IGNORE INTO newsletter_jobs(edition_id,job_id,company_id,benefit_month) SELECT ?,j.id,j.company_id,CASE WHEN p.tier='scale' THEN ? ELSE NULL END FROM jobs j JOIN companies c ON c.id=j.company_id JOIN company_plans p ON p.company_id=j.company_id WHERE j.tenant_id=? AND ${publicNative} AND p.tier IN ('scale','platinum') AND p.status IN ('active','trialing') AND p.renews_at>? AND NOT EXISTS(SELECT 1 FROM newsletter_jobs n WHERE n.job_id=j.id) ORDER BY j.created_at,j.id LIMIT 100`).bind(edition,month,tenantId,at,at),
 db.prepare("INSERT OR IGNORE INTO newsletter_deliveries(edition_id,subscriber_id) SELECT ?,id FROM newsletter_subscribers WHERE active=1 AND (user_id IS NULL OR EXISTS(SELECT 1 FROM users u WHERE u.id=newsletter_subscribers.user_id AND u.tenant_id=?))").bind(edition,tenantId),
 ]);
}
export async function deliverWeeklyNewsletter(env:DistributionEnv,now=new Date()){
 if(env.NEWSLETTER_DELIVERY_ENABLED!=='true'||!env.EMAIL_FROM||!env.SITE_URL)return;const at=now.toISOString();
 const rows=await env.DB.prepare("SELECT d.edition_id,d.subscriber_id,s.email,s.unsubscribe_token FROM newsletter_deliveries d JOIN newsletter_subscribers s ON s.id=d.subscriber_id WHERE d.status='pending' AND s.active=1 AND (d.lease_until IS NULL OR d.lease_until<=?) ORDER BY d.edition_id LIMIT 10").bind(at).all<{edition_id:string;subscriber_id:string;email:string;unsubscribe_token:string}>();
 const contents=new Map<string,string>();
 for(const row of rows.results){let content=contents.get(row.edition_id);if(content===undefined){content=await newsletterContent(env.DB,row.edition_id,env.SITE_URL,now);contents.set(row.edition_id,content);}if(!content){await env.DB.prepare("UPDATE newsletter_deliveries SET status='empty' WHERE edition_id=? AND subscriber_id=?").bind(row.edition_id,row.subscriber_id).run();continue;}
 const token=crypto.randomUUID(),claim=await env.DB.prepare("UPDATE newsletter_deliveries SET status='sending',lease_token=?,lease_until=?,attempts=attempts+1 WHERE edition_id=? AND subscriber_id=? AND status='pending'").bind(token,new Date(now.getTime()+120000).toISOString(),row.edition_id,row.subscriber_id).run();if(!(claim as {meta?:{changes?:number}}).meta?.changes)continue;
 try{await env.EMAIL.send({to:row.email,from:env.EMAIL_FROM,subject:'This week’s Web3 opportunities',text:content+'\n\nUnsubscribe: '+new URL('/newsletter/unsubscribe?token='+row.unsubscribe_token,env.SITE_URL).href});await env.DB.prepare("UPDATE newsletter_deliveries SET status='sent',sent_at=?,lease_until=NULL WHERE edition_id=? AND subscriber_id=? AND lease_token=?").bind(at,row.edition_id,row.subscriber_id,token).run();}catch{await env.DB.prepare("UPDATE newsletter_deliveries SET status='uncertain',last_error='Delivery outcome needs review',lease_until=NULL WHERE edition_id=? AND subscriber_id=? AND lease_token=?").bind(row.edition_id,row.subscriber_id,token).run();}}
 await env.DB.prepare("UPDATE newsletter_deliveries SET status='uncertain',last_error='Worker stopped during delivery' WHERE status='sending' AND lease_until<=?").bind(at).run();
}

/** Assemble only currently public content; paid placements and editorial sections are separate. */
export async function newsletterContent(db:ProductDatabase,editionId:string,origin:string,now=new Date()){
 const edition=await db.prepare('SELECT tenant_id,created_at FROM newsletter_editions WHERE id=?').bind(editionId).first<{tenant_id:string;created_at:string}>();if(!edition)return '';
 const at=now.toISOString(),since=new Date(Date.parse(edition.created_at)-7*86400000).toISOString();
 const featured=await db.prepare(`SELECT j.title,j.slug,c.name FROM newsletter_jobs n JOIN jobs j ON j.id=n.job_id JOIN companies c ON c.id=j.company_id WHERE n.edition_id=? AND ${publicNative} ORDER BY j.created_at LIMIT 100`).bind(editionId,at).all<{title:string;slug:string;name:string}>();
 const latest=await db.prepare(`SELECT j.title,j.slug,c.name FROM jobs j JOIN companies c ON c.id=j.company_id WHERE j.tenant_id=? AND ${publicNative} AND j.published_at>=? AND j.published_at<=? AND NOT EXISTS(SELECT 1 FROM newsletter_jobs n WHERE n.edition_id=? AND n.job_id=j.id) ORDER BY j.published_at DESC LIMIT 20`).bind(edition.tenant_id,at,since,edition.created_at,editionId).all<{title:string;slug:string;name:string}>();
 const member=await db.prepare("SELECT p.handle,p.display_name,p.headline,f.date FROM featured_members f JOIN profiles p ON p.user_id=f.user_id JOIN users u ON u.id=p.user_id WHERE u.tenant_id=? AND f.date BETWEEN ? AND ? AND p.public_profile=1 AND p.talent_pool_opt_in=1 AND p.featured_opt_in=1 ORDER BY f.date DESC LIMIT 1").bind(edition.tenant_id,since.slice(0,10),edition.created_at.slice(0,10)).first<{handle:string;display_name:string;headline:string;date:string}>();
 const salary=await db.prepare("SELECT s.role_slug,r.name,s.as_of,s.stats_json FROM salary_stats s JOIN job_roles r ON r.slug=s.role_slug WHERE s.location_slug='all' AND s.as_of>=? AND s.as_of<=? AND json_extract(s.stats_json,'$.count')>=5 ORDER BY s.as_of DESC,json_extract(s.stats_json,'$.count') DESC LIMIT 1").bind(edition.created_at.slice(0,7)+'-01',edition.created_at.slice(0,10)).first<{role_slug:string;name:string;as_of:string;stats_json:string}>();
 const jobs=(rows:typeof latest.results)=>rows.map(j=>`${j.title} at ${j.name}\n${new URL('/jobs/'+j.slug+'?utm_source=newsletter',origin).href}`).join('\n\n'),sections:string[]=[];
 if(featured.results.length)sections.push('Featured opportunities\n'+jobs(featured.results));if(latest.results.length)sections.push('Jobs of the week\n'+jobs(latest.results));
 if(member?.handle)sections.push(`Featured member of the week\n${publicCandidateText(member.display_name)} — ${publicCandidateText(member.headline)}\n${new URL('/talent/'+member.handle,origin).href}`);
 if(salary){const stats=JSON.parse(salary.stats_json);sections.push(`Salary insight of the month: ${salary.name}\nMedian $${Math.round(stats.median).toLocaleString('en-US')} USD/year from ${stats.count} external advertised salaries (as of ${salary.as_of}).\n${new URL('/salaries/'+salary.role_slug,origin).href}`);}
 return sections.join('\n\n');
}
