import {talentReadAllowance} from '../../../lib/product/operations';
import {TalentSkillFilters} from '../../_components/product/talent-skill-filters';
import Link from 'next/link';
import {redirect} from 'next/navigation';
import {publicCandidateText,pricing,money,UTC_OFFSETS,formatUtcOffset} from '@gaming/shared';
import {platform,currentUser} from '../../../lib/platform';
import {requireTenantId} from '../../../lib/tenant';
import {loadProductFlags} from '../../../lib/product/flags';
import {talentCompany,talentSearch,refreshJobShortlist} from '../../../lib/product/talent';
import {PurchaseButton} from '../../_components/product/purchase-button';
import {EmployerShell} from '../../_components/employer-shell';
export const dynamic='force-dynamic';
export const metadata={title:'Talent Search',robots:{index:false,follow:false}};
export default async function Talent({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const env=await platform(),user=await currentUser(env),f=await searchParams;if(!user)redirect('/employer/login?next=/dashboard/talent');const company=await talentCompany(env.DB,user.id,f.company);
 if(!(await loadProductFlags(env.DB,await requireTenantId(env.DB),env)).PRODUCT_TALENT_SEARCH||!company)return <EmployerShell title="Talent Search"><p>Activate an annual company plan and verify your company claim to use talent tools.</p><Link href="/pricing">View plans</Link></EmployerShell>;
 if(!await talentReadAllowance(env.DB,user.id,'search'))return <EmployerShell title="Talent Search"><p>Search limit reached. Please pause and try again later.</p></EmployerShell>;
 if(f.shortlist==='1'&&f.job){await refreshJobShortlist(env.DB,f.job);f.snapshot='1';}
 let result;try{result=await talentSearch(env.DB,{companyId:company.company_id,userId:user.id,jobId:f.job??f.match,filters:f});}catch(error){return <EmployerShell title="Talent Search"><p>{error instanceof Error?error.message:'Unavailable'}</p><fieldset disabled><legend>Platinum search preview</legend><label>Skills<input placeholder="Search canonical skills"/></label><label>Location<input placeholder="Country, region or timezone"/></label><label>Language<input placeholder="Language and proficiency"/></label><label>Match score<input type="range" min={0} max={100}/></label><button>Search candidates</button></fieldset><Link href="/pricing">View Platinum</Link><Link href="/employer">Choose a job for your shortlist</Link></EmployerShell>;}
 const jobs=await env.DB.prepare("SELECT id,title FROM jobs WHERE company_id=? AND listed=1 AND commercial_origin IN ('native','native_ats') AND expires_at>? ORDER BY created_at DESC").bind(company.company_id,new Date().toISOString()).all<{id:string;title:string}>();
 const invites=await env.DB.prepare('SELECT candidate_id,job_id,status,sent_at FROM product_invitations WHERE company_id=? ORDER BY sent_at DESC LIMIT 100').bind(company.company_id).all<{candidate_id:string;job_id:string;status:string;sent_at:string}>();
 const used=await env.DB.prepare("SELECT COUNT(*) n FROM product_invitations WHERE company_id=? AND source='talent_search' AND quota_period=? AND pack_id IS NULL").bind(company.company_id,new Date().toISOString().slice(0,7)).first<number>('n')??0;
 const extra=await env.DB.prepare('SELECT COALESCE(SUM(quantity-used),0) n FROM talent_invite_packs WHERE company_id=? AND revoked=0').bind(company.company_id).first<number>('n')??0;
 const selectedSkills=await env.DB.prepare('SELECT id,name FROM skills WHERE id IN(SELECT value FROM json_each(?))').bind(JSON.stringify((f.skills??'').split(','))).all<{id:string;name:string}>();
 const languages=await env.DB.prepare('SELECT code,name FROM reference_languages ORDER BY name').bind().all<{code:string;name:string}>(),countries=await env.DB.prepare('SELECT code,name FROM reference_countries ORDER BY name').bind().all<{code:string;name:string}>();
 const regions=await env.DB.prepare("SELECT id,name FROM regions WHERE type!='country' ORDER BY name").all<{id:string;name:string}>();
 const path=(page:number)=>'/dashboard/talent?'+new URLSearchParams({...Object.fromEntries(Object.entries(f).filter((e):e is [string,string]=>typeof e[1]==='string')),company:company.company_id,page:String(page)});
 return <EmployerShell title={f.shortlist==='1'?'Candidate shortlist':'Talent Search'}><p>{company.name} · {f.job?`${pricing.plans[result.plan].shortlistInvites} shortlist invitations per post`:`${Math.max(0,pricing.plans.platinum.talentInvites-used)} monthly invitations and ${extra} extra invitations remaining`}</p>{f.sent?<p role="status">Invitation sent or already present. No duplicate charge.</p>:null}{company.tier==='platinum'?<PurchaseButton kind="invite_pack" choice="50" payload={{companyId:company.company_id}} label={`Add ${pricing.talentExtraPack.invites} invitations · ${money(pricing.talentExtraPack.price)}`}/>:null}
 <form className="commerce-form"><input type="hidden" name="company" value={company.company_id}/>{f.job?<input type="hidden" name="job" value={f.job}/>:null}{f.shortlist?<input type="hidden" name="shortlist" value="1"/>:null}<label>Match against<select name="match" defaultValue={f.match}><option value="">No selected job</option>{jobs.results.map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></label><label>Sort<select name="sort" defaultValue={f.sort}><option value="relevance">Relevance</option><option value="score">Match score</option><option value="active">Last activity</option></select></label><label>Headline or experience<input name="q" defaultValue={f.q}/></label><TalentSkillFilters initial={selectedSkills.results}/><label>Skills<select name="skillMode" defaultValue={f.skillMode}><option value="and">All selected skills</option><option value="or">Any selected skill</option></select></label><label>Language<select name="language" defaultValue={f.language}><option value="">Any</option>{languages.results.map(l=><option value={l.code} key={l.code}>{l.name}</option>)}</select></label><label>Minimum language level<select name="level" defaultValue={f.level}>{['A1','A2','B1','B2','C1','C2','Native'].map(l=><option key={l}>{l}</option>)}</select></label><label>Country<select name="country" defaultValue={f.country}><option value="">Any</option>{countries.results.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label><label>Area<select name="region" defaultValue={f.region}><option value="">Any</option>{regions.results.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>UTC from<select name="utcFrom" defaultValue={f.utcFrom}><option value="">Any</option>{UTC_OFFSETS.map(n=><option key={n} value={n}>{formatUtcOffset(n)}</option>)}</select></label><label>UTC to<select name="utcTo" defaultValue={f.utcTo}><option value="">Any</option>{UTC_OFFSETS.map(n=><option key={n} value={n}>{formatUtcOffset(n)}</option>)}</select></label><label>Availability<select name="availability" defaultValue={f.availability}><option value="">Any</option><option value="open_to_work">Open to work</option><option value="open_to_contracts">Open to contracts</option></select></label><label>Work arrangement<select name="arrangement" defaultValue={f.arrangement}><option value="">Any</option>{['remote','hybrid','onsite'].map(x=><option key={x}>{x}</option>)}</select></label><label>Minimum completeness<input name="completeness" type="number" min={0} max={100} defaultValue={f.completeness}/></label>{f.job?<label>Minimum match score<input name="score" type="number" min={0} max={100} defaultValue={f.score}/></label>:null}{[['crypto','Open to crypto pay'],['verified','Verified'],['premium','Premium'],['recent','Active in the last 30 days'],['featured','Featured today']].map(([key,label])=><label key={key}><input type="checkbox" name={key} value="1" defaultChecked={f[key]==='1'}/>{label}</label>)}<button>Search</button></form>
 <p>{result.rows[0]?.total??0} matching candidates</p>{result.rows.map(p=><article className="panel stack" key={p.user_id}><h2><Link href={'/talent/'+(p.handle??p.user_id)}>{publicCandidateText(p.display_name)||'Candidate'}</Link></h2><p>{publicCandidateText(p.headline)} · {p.location}</p><p>{p.skills}</p><p>{p.languages}</p>{p.photo_url?<img src={p.photo_url} alt="" width={64} height={64}/>:null}<p>{p.featured?'Featured today · ':''}{p.premium?'Premium · ':''}{p.verified_at?'Verified · ':''}{f.job||f.match?`Match ${p.match_score}%`:''}</p><form method="post" action="/api/product/invitations"><input type="hidden" name="candidateId" value={p.user_id}/><input type="hidden" name="companyId" value={company.company_id}/><input type="hidden" name="source" value={f.shortlist==='1'?'shortlist':'talent_search'}/><label>Invite to job<select name="jobId" required defaultValue={f.job}>{jobs.results.filter(j=>!f.job||j.id===f.job).map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></label><label>Personal message<textarea name="message" maxLength={2000}/></label><button disabled={!jobs.results.length}>Invite to apply</button></form>{invites.results.filter(i=>i.candidate_id===p.user_id).map(i=><p key={i.job_id}>Invitation {i.status} · {i.sent_at.slice(0,10)}</p>)}</article>)}<nav>{result.page>1?<Link href={path(result.page-1)}>Previous</Link>:null}{result.rows[0]?.total>result.page*25?<Link href={path(result.page+1)}>Next</Link>:null}</nav></EmployerShell>;
}
