import {loadProductFlags} from '../../../../lib/product/flags';
import {requireTenantId} from '../../../../lib/tenant';
import {recoverMarketCheckouts} from '../../../../lib/billing/marketplace-recovery';
import {platform,currentUser,sameOrigin,appOrigin} from '../../../../lib/platform';
import {createMarketOrder,parseSponsor} from '../../../../lib/billing/marketplace';
export async function POST(request:Request){if(!sameOrigin(request))return new Response('Forbidden',{status:403});const env=await platform(),user=await currentUser(env,request);if(!user)return Response.json({error:'Sign in before checkout'},{status:401});if(env.STRIPE_ENABLED!=='true'||!env.STRIPE_SECRET_KEY)return Response.json({error:'Checkout is not configured yet'},{status:503});await recoverMarketCheckouts(env.DB,env.STRIPE_SECRET_KEY);let order;try{const r=await request.json();if(!r||typeof r.id!=='string'||!/^[a-f0-9-]{36}$/i.test(r.id)||!['sponsor','recruiter'].includes(r.kind))throw new Error('Invalid order');if(r.kind==='recruiter'&&(await loadProductFlags(env.DB,await requireTenantId(env.DB),env)).PRODUCT_TALENT_SEARCH)throw Error('Recruiter access is included in the Platinum company plan. Use Plans to subscribe.');order=await createMarketOrder(env.DB,{id:r.id,userId:user.id,kind:r.kind,sponsor:r.kind==='sponsor'?parseSponsor(r.sponsor):undefined});}catch(e){return Response.json({error:e instanceof Error?e.message:'Invalid order',retryWithNewId:e instanceof Error&&e.message.startsWith('Checkout expired.')},{status:400});}
 if(!order.stripe_session_id&&Date.now()-Date.parse(order.created_at)>10*60000)return Response.json({error:"This checkout attempt is too old. Start a new order.",retryWithNewId:true},{status:410});
 const origin=appOrigin(env);const body=new URLSearchParams({mode:'payment',customer_creation:'always',customer_email:user.email,'metadata[purchaseId]':order.id,'payment_intent_data[metadata][purchaseId]':order.id,'payment_method_types[0]':'card',success_url:`${origin}/${order.kind==='sponsor'?'advertiser':'recruiter'}?paid=1`,cancel_url:`${origin}/${order.kind==='sponsor'?'ads':'recruiter'}?cancelled=1`,'line_items[0][quantity]':'1','line_items[0][price_data][currency]':'usd','line_items[0][price_data][unit_amount]':String(order.total_cents),'line_items[0][price_data][product_data][name]':order.kind==='sponsor'?'Nodework advertising — 30 days':'Nodework recruiter access — 30 days'});
 const r=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',signal:AbortSignal.timeout(15000),headers:{Authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,'Content-Type':'application/x-www-form-urlencoded','Idempotency-Key':`market:${order.id}`},body});if(!r.ok)return Response.json({error:'Checkout could not be created. Retry this order.'},{status:502});const s=await r.json() as {id:string;url:string};if(!s.id||!s.url?.startsWith('https://checkout.stripe.com/'))return new Response('Invalid payment provider response',{status:502});await env.DB.prepare('UPDATE marketplace_orders SET stripe_session_id=? WHERE id=? AND stripe_session_id IS NULL').bind(s.id,order.id).run();return Response.json({url:s.url});}
