export const JOB_TAGS = [
  "3d",
  "4-day-work-week",
  "401k",
  "a16z",
  "abap",
  "account-manager",
  "accounting",
  "actionscript",
  "admin",
  "ads",
  "adult",
  "affiliate",
  "after-effects",
  "agile",
  "ai",
  "amazon",
  "amazon-fba",
  "ambassador",
  "analyst",
  "android",
  "angular",
  "ansible",
  "api",
  "applescript",
  "arabic",
  "architecture",
  "art-direction",
  "artist",
  "assembly",
  "async",
  "attorney",
  "aws",
  "backend",
  "big-data",
  "biotech",
  "bitcoin",
  "blockchain",
  "blockchain-engineer",
  "bnbchain",
  "bootstrap",
  "brand",
  "brand-designer",
  "brand-marketing",
  "business-development",
  "c",
  "c-plus-plus",
  "c-sharp",
  "casino",
  "cassandra",
  "cfo",
  "chatbot",
  "china",
  "ci-cd",
  "clojure",
  "cloud-engineer",
  "cmo",
  "co-founder",
  "cobol",
  "coldfusion",
  "communication",
  "communications",
  "community-manager",
  "company-retreats",
  "compiler",
  "compliance",
  "computer-science",
  "consulting",
  "content-marketing",
  "content-writer",
  "contracting",
  "contractor",
  "copywriting",
  "cosmos",
  "couch",
  "couchbase",
  "coworking-budget",
  "creative-director",
  "crm",
  "crypto",
  "cryptography",
  "css",
  "cto",
  "cuda",
  "customer-service",
  "customer-success",
  "customer-support",
  "dao",
  "dapp",
  "dart",
  "data-entry",
  "data-science",
  "data-viz",
  "dataops",
  "dba",
  "decentralize",
  "defi",
  "dental-insurance",
  "depin",
  "design",
  "design-manager",
  "dev",
  "developer-advocate",
  "developer-relations",
  "devops",
  "digital-marketing",
  "discord",
  "distributed-team",
  "docker",
  "dot-net",
  "drizzle",
  "drupal",
  "ecommerce",
  "economy-designer",
  "education",
  "elasticsearch",
  "elixir",
  "email-marketing",
  "embedded",
  "ember",
  "engineer",
  "engineering-manager",
  "english",
  "english-teacher",
  "entry-level",
  "eos",
  "equity-compensation",
  "erc",
  "erc-1155",
  "erc-165",
  "erc-20",
  "erc-223",
  "erc-4626",
  "erc-621",
  "erc-721",
  "erc-777",
  "erc-827",
  "erc-865",
  "erc-884",
  "erlang",
  "esports",
  "ethereum",
  "ethereumjs",
  "event-manager",
  "events-manager",
  "evm",
  "executive",
  "f-sharp",
  "finance",
  "fintech",
  "firebase",
  "flutter",
  "fortran",
  "founding-engineer",
  "founding-member",
  "france",
  "free-gym-membership",
  "freelance",
  "front-end",
  "fsa",
  "full-stack",
  "full-time",
  "func-developer",
  "gambling",
  "game-dev",
  "gaming",
  "ganache",
  "gcp",
  "git",
  "gnosis",
  "golang",
  "gpt",
  "gpu",
  "grafana",
  "graphic-designer",
  "graphql",
  "groovy",
  "growth",
  "growth-hacker",
  "growth-marketing",
  "gtm",
  "hadoop",
  "hardhat",
  "hardware",
  "haskell",
  "head-of-design",
  "head-of-marketing",
  "head-of-sales",
  "heroku",
  "home-office-budget",
  "hr",
  "hsa",
  "html",
  "hyperledger-fabric",
  "iam-engineer",
  "illustrator",
  "india",
  "influencer-marketing",
  "infrastructure",
  "integration",
  "intern",
  "io",
  "ios",
  "japan",
  "java",
  "javascript",
  "jira",
  "jquery",
  "junior",
  "kol",
  "komodo",
  "kotlin",
  "kubernetes",
  "kyb",
  "kyc",
  "lamp",
  "laravel",
  "layer-2",
  "lead",
  "lead-designer",
  "legal",
  "libp2p",
  "linguistics",
  "linode",
  "linux",
  "lisp",
  "machine-learning",
  "macos",
  "marketing",
  "marketing-analyst",
  "marketing-communication",
  "marketing-lead",
  "marketing-manager",
  "marketing-specialist",
  "marketing-strategist",
  "math",
  "matlab",
  "medical",
  "medical-insurance",
  "meme",
  "men-in-web3",
  "mental-wellness-budget",
  "mern",
  "metaverse",
  "meteor",
  "mev",
  "microsoft",
  "mobile",
  "mobile-designer",
  "moderator",
  "mongo",
  "motion-designer",
  "move",
  "music",
  "nestjs",
  "network-engineer",
  "nextjs",
  "nft",
  "nginx",
  "nlp",
  "node",
  "non-tech",
  "nosql",
  "nuxtjs",
  "objective-c",
  "office",
  "open-source",
  "open-stack",
  "openzeppelin",
  "operations",
  "others-in-web3",
  "part-time",
  "partnership",
  "pascal",
  "pay-in-bitcoin",
  "pay-in-crypto",
  "perl",
  "phd",
  "phonegap",
  "photoshop",
  "php",
  "polkadot",
  "polygon",
  "postgres",
  "pr",
  "producer",
  "product-designer",
  "product-lead",
  "product-manager",
  "product-marketing",
  "profit-sharing",
  "project-manager",
  "prompt",
  "protocol",
  "protocol-engineer",
  "pseudonymous",
  "pto",
  "python",
  "pytorch",
  "quality-assurance",
  "quantitative",
  "quantitative-analyst",
  "quantitative-developer",
  "quantitative-researcher",
  "quantitative-trader",
  "r3-corda",
  "rabbitmq",
  "react",
  "react-native",
  "recruiter",
  "redis",
  "refi",
  "reliability",
  "remix",
  "remove",
  "research",
  "retention-marketing",
  "robotics",
  "ruby",
  "rust",
  "saas",
  "sales",
  "sales-engineer",
  "salesforce",
  "sanctions",
  "scala",
  "scheme",
  "scientist",
  "scikit-learn",
  "scrum",
  "security",
  "security-guard",
  "senior",
  "seo",
  "serverless",
  "smart-contract",
  "social-media",
  "solana",
  "solidity",
  "solution",
  "spain",
  "speech",
  "sql",
  "stats",
  "strategy",
  "swift",
  "symfony",
  "sys-admin",
  "system-engineer",
  "tailwind",
  "teaching",
  "tech-lead",
  "technical-writer",
  "telecom",
  "telecommuting",
  "tensorflow",
  "terraform",
  "tezos",
  "tiktok",
  "tokenization",
  "tokenomics",
  "ton-developer",
  "trader",
  "transcribing",
  "translator",
  "treasury",
  "truffle",
  "typescript",
  "ui-ux-designer",
  "unity",
  "unlimited-vacation",
  "unpaid",
  "unreal-engine",
  "user-acquisition",
  "ux-researcher",
  "vc",
  "vfx",
  "video",
  "video-creator",
  "virtual-assistant",
  "virtual-reality",
  "vision-insurance",
  "visual-basic",
  "visual-designer",
  "voip",
  "vp-of-marketing",
  "vue",
  "wax",
  "web-designer",
  "web-dev",
  "web3",
  "web3-py",
  "web3js",
  "webmaster",
  "win-phone",
  "women-in-web3",
  "wordpress",
  "work-from-home",
  "writer",
  "xamarin",
  "ycombinator",
  "zero-knowledge",
  "zk-evm",
  "zk-rollup",
  "zk-snark",
] as const;

export type JobTag = (typeof JOB_TAGS)[number];

export const FEATURED_TAG_CHIPS = [
  "ai",
  "analyst",
  "backend",
  "bitcoin",
  "blockchain",
  "community-manager",
  "crypto",
  "cryptography",
  "cto",
  "customer-support",
  "dao",
  "data-science",
  "defi",
  "design",
  "developer-relations",
  "devops",
  "discord",
  "economy-designer",
  "entry-level",
  "erc",
  "erc-20",
  "evm",
  "front-end",
  "full-stack",
  "gaming",
  "ganache",
  "golang",
  "hardhat",
  "intern",
  "java",
  "javascript",
  "layer-2",
  "marketing",
  "mobile",
  "moderator",
  "nft",
  "node",
  "non-tech",
  "open-source",
  "openzeppelin",
  "pay-in-crypto",
  "product-manager",
  "project-manager",
  "react",
  "refi",
  "research",
  "ruby",
  "rust",
  "sales",
  "smart-contract",
  "solana",
  "solidity",
  "truffle",
  "web3-py",
  "web3js",
  "zero-knowledge",
] as const;

export const SALARY_ROLES = [
  "ai-engineer",
  "android-developer",
  "angular-developer",
  "architecture-developer",
  "backend-developer",
  "blockchain-developer",
  "c-developer",
  "c-plus-plus-developer",
  "c-sharp-developer",
  "community-manager",
  "crypto",
  "cryptography",
  "cto",
  "dart-developer",
  "design",
  "devops-engineer",
  "ethereum-developer",
  "finance",
  "flutter-developer",
  "front-end-developer",
  "full-stack-developer",
  "golang-developer",
  "hr",
  "ios-developer",
  "java-developer",
  "javascript-developer",
  "junior-developer",
  "kotlin-developer",
  "lead-developer",
  "legal",
  "machine-learning-engineer",
  "marketing",
  "mobile-developer",
  "nft",
  "node-developer",
  "php-developer",
  "product-manager",
  "python-developer",
  "qa-engineer",
  "quantitative-developer",
  "react-developer",
  "recruiter",
  "ruby-developer",
  "rust-developer",
  "sales",
  "scala-developer",
  "senior-developer",
  "smart-contract-developer",
  "solana-developer",
  "solidity-developer",
  "swift-developer",
  "typescript-developer",
  "unity-developer",
  "vue-developer",
] as const;

export type SalaryRole = (typeof SALARY_ROLES)[number];

/**
 * Short salary-page slugs that are still linked and still indexed but are not roles
 * of their own. They are deliberately kept out of SALARY_ROLES: only the canonical
 * long slug may reach the sitemap, the footer and the salary comparison tables, so
 * every salary page keeps exactly one 200 URL. parseSalaryPageSlug folds an alias
 * onto its canonical role, and the page's rel=canonical follows the parsed role, so
 * /web3-salaries/solidity serves the page and points at /web3-salaries/solidity-developer.
 */
export const SALARY_ROLE_ALIASES: Readonly<Record<string, SalaryRole>> = {
  quantitative: "quantitative-developer",
  solidity: "solidity-developer",
};

const salaryRoleAliases = new Map<string, SalaryRole>(
  Object.entries(SALARY_ROLE_ALIASES),
);

/** The canonical SALARY_ROLES member for a slug, resolving aliases; null if neither. */
export function canonicalSalaryRole(slug: string): SalaryRole | null {
  if (isSalaryRole(slug)) return slug;
  return salaryRoleAliases.get(slug) ?? null;
}

export const NON_TECH_SALARY_ROLES = [
  "community-manager",
  "design",
  "finance",
  "hr",
  "junior",
  "lead",
  "legal",
  "marketing",
  "product-manager",
  "project-manager",
  "recruiter",
  "sales",
  "senior",
  "social-media",
] as const;

export type NonTechSalaryRole = (typeof NON_TECH_SALARY_ROLES)[number];

export const SENIORITY_SLUGS = [
  "intern",
  "junior",
  "senior",
  "lead",
  "cto",
] as const;

export type SenioritySlug = (typeof SENIORITY_SLUGS)[number];

/** Lowest to highest. A combo landing shows only the lowest seniority present. */
export const SENIORITY_RANK: Record<SenioritySlug, number> = {
  intern: 0,
  junior: 1,
  senior: 2,
  lead: 3,
  cto: 4,
};

/**
 * Role tags whose bare term is saturated outside Web3, so their landings read
 * "{Role} Jobs in Web3" instead of competing on "{Role} Jobs".
 */
export const GENERIC_ROLE_TAGS = [
  "analyst",
  "community-manager",
  "copywriting",
  "customer-support",
  "design",
  "developer-relations",
  "devops",
  "engineer",
  "event-manager",
  "executive",
  "finance",
  "hr",
  "legal",
  "marketing",
  "moderator",
  "operations",
  "product-manager",
  "project-manager",
  "quality-assurance",
  "recruiter",
  "research",
  "sales",
  "scientist",
  "seo",
  "social-media",
  "tech-lead",
  "trader",
  "ux-researcher",
] as const;

const GENERIC_ROLE_TAG_SET = new Set<string>(GENERIC_ROLE_TAGS);

export function isGenericRoleTag(slug: string): boolean {
  return GENERIC_ROLE_TAG_SET.has(slug);
}

export const REGIONS = [
  "africa",
  "asia",
  "europe",
  "north-america",
  "oceania",
  "south-america",
] as const;

export type RegionSlug = (typeof REGIONS)[number];

export const COUNTRIES = [
  "argentina",
  "armenia",
  "australia",
  "austria",
  "azerbaijan",
  "bangladesh",
  "belarus",
  "belgium",
  "bolivia",
  "brazil",
  "bulgaria",
  "cameroon",
  "canada",
  "cayman-islands",
  "chile",
  "china",
  "colombia",
  "costa-rica",
  "croatia",
  "czech-republic",
  "denmark",
  "djibouti",
  "dominican-republic",
  "ecuador",
  "egypt",
  "estonia",
  "finland",
  "france",
  "georgia",
  "germany",
  "greece",
  "guatemala",
  "hong-kong",
  "hungary",
  "iceland",
  "india",
  "indonesia",
  "ireland",
  "israel",
  "italy",
  "ivory-coast",
  "japan",
  "kazakhstan",
  "kenya",
  "kuwait",
  "kyrgyzstan",
  "latvia",
  "lebanon",
  "lithuania",
  "luxembourg",
  "malaysia",
  "mexico",
  "morocco",
  "netherlands",
  "new-zealand",
  "nicaragua",
  "nigeria",
  "norway",
  "pakistan",
  "panama",
  "peru",
  "philippines",
  "poland",
  "portugal",
  "puerto-rico",
  "romania",
  "serbia",
  "singapore",
  "south-africa",
  "south-korea",
  "spain",
  "sweden",
  "switzerland",
  "taiwan",
  "thailand",
  "tunisia",
  "turkey",
  "uganda",
  "ukraine",
  "united-arab-emirates",
  "united-kingdom",
  "united-states",
  "uruguay",
  "uzbekistan",
  "venezuela",
  "vietnam",
  "yemen",
] as const;

export type CountrySlug = (typeof COUNTRIES)[number];

export const CITIES = [
  "aba",
  "abakaliki",
  "abeokuta",
  "abidjan",
  "abomey-calavi",
  "abu-dhabi",
  "abuja",
  "acapulco-de-juarez",
  "accra",
  "ad-dammam",
  "adana",
  "addis-ababa",
  "adelaide",
  "aden",
  "agadir",
  "agartala",
  "agra",
  "aguascalientes",
  "ahmedabad",
  "ahvaz",
  "ajmer",
  "akure",
  "al-ain",
  "al-hudaydah",
  "al-mahallah-al-kubra",
  "al-mansurah",
  "al-mukalla",
  "al-raqqa",
  "albuquerque",
  "aleppo",
  "alexandria",
  "algiers",
  "aligarh",
  "allahabad",
  "almaty",
  "amara",
  "ambon",
  "amman",
  "amravati",
  "amritsar",
  "amsterdam",
  "angeles-city",
  "ankang",
  "ankara",
  "anqing",
  "anqiu",
  "ansan",
  "anshan",
  "anshun",
  "antalya",
  "antananarivo",
  "antipolo",
  "antwerp",
  "anyang",
  "ar-rayyan",
  "ar-rusayfah",
  "aracaju",
  "arak",
  "ardabil",
  "arequipa",
  "arizona",
  "arusha",
  "as-suways",
  "asansol",
  "ashgabat",
  "asmara",
  "astana",
  "astrakhan",
  "asuncion",
  "athens",
  "atlanta",
  "auckland",
  "aurangabad",
  "austin",
  "bacolod",
  "bacoor",
  "baghdad",
  "bahawalpur",
  "baishan",
  "baixada-santista",
  "baku",
  "balashikha",
  "bali",
  "baltimore",
  "bamako",
  "bamenda",
  "bandar-abbas",
  "bandar-lampung",
  "bandung",
  "bangalore",
  "banghazi",
  "bangkok",
  "bangui",
  "banjarmasin",
  "baoding",
  "baoji",
  "baotou",
  "barcelona",
  "barcelona-puerto-la-cruz",
  "bareilly",
  "bari",
  "barnaul",
  "barquisimeto",
  "barranquilla",
  "basel",
  "basilan-city",
  "basra",
  "batam",
  "bauchi",
  "bazhong",
  "be-er-sheva",
  "beaverton",
  "beijing",
  "beira",
  "beirut",
  "bekasi",
  "belem",
  "belfast",
  "belgaum",
  "belgrade",
  "bellary",
  "bellevue",
  "belo-horizonte",
  "bengaluru",
  "bengbu",
  "benguela",
  "benin-city",
  "benxi",
  "berbera",
  "bergamo",
  "berlin",
  "bhavnagar",
  "bhiwandi",
  "bhopal",
  "bhubaneswar",
  "bien-hoa",
  "bijie",
  "bikaner",
  "bilaspur",
  "binzhou",
  "birmingham",
  "bishkek",
  "bissau",
  "blantyre-limbe",
  "bloemfontein",
  "bobo-dioulasso",
  "bogor",
  "bogota",
  "bogra",
  "bokaro-steel-city",
  "bologna",
  "bordeaux",
  "boston",
  "bouake",
  "bournemouth",
  "bozeman",
  "bozhou",
  "brasilia",
  "brazzaville",
  "bremen",
  "brighton",
  "brisbane",
  "bristol",
  "brussels",
  "bucaramanga",
  "bucharest",
  "bucheon",
  "budapest",
  "buenos-aires",
  "buffalo-city",
  "bujumbura",
  "bukavu",
  "bulawayo",
  "bunia",
  "bur-sa-id",
  "buraydah",
  "bursa",
  "busan",
  "busto-arsizio",
  "cabimas",
  "cabinda",
  "cagayan-de-oro-city",
  "cairo",
  "calabar",
  "calamba",
  "calgary",
  "california",
  "campinas",
  "campo-grande",
  "can-tho",
  "cancun",
  "cangzhou",
  "cape-town",
  "caracas",
  "cartagena",
  "casablanca",
  "catania",
  "cebu-city",
  "celaya",
  "cenxi",
  "chandigarh",
  "changchun",
  "changde",
  "changge",
  "changning",
  "changsha",
  "changshu",
  "changwon",
  "changyi",
  "changzhi",
  "changzhou",
  "chaoyang",
  "chaozhou",
  "charlotte",
  "cheboksary",
  "chelyabinsk",
  "chengde",
  "chengdu",
  "chennai",
  "chenzhou",
  "cheonan",
  "cheongju",
  "cherthala",
  "chiang-mai",
  "chiang-rai",
  "chicago",
  "chiclayo",
  "chifeng",
  "chihuahua",
  "chittagong",
  "chon-buri",
  "chongjin",
  "chongqing",
  "chuxiong",
  "chuzhou",
  "ciudad-guayana",
  "ciudad-juarez",
  "cixi",
  "cochabamba",
  "coimbatore",
  "cologne",
  "colombo",
  "colorado",
  "columbus",
  "comilla",
  "conakry",
  "concepcion",
  "connecticut",
  "copenhagen",
  "cordoba",
  "cotonou",
  "cuautla-morelos",
  "cucuta",
  "cuernavaca",
  "cuiaba",
  "cuito",
  "culiacan",
  "cupertino",
  "curitiba",
  "cuttack",
  "da-nang",
  "daegu",
  "daejon",
  "dakar",
  "dali",
  "dalian",
  "dallas",
  "damascus",
  "dandong",
  "danyang",
  "daqing",
  "dar-es-salaam",
  "dasmarinas",
  "datong",
  "davanagere",
  "davao-city",
  "daye",
  "dazhou",
  "dehradun",
  "delaware",
  "delhi",
  "dengfeng",
  "dengzhou",
  "denizli",
  "denpasar",
  "denver",
  "depok",
  "detroit",
  "deyang",
  "dezhou",
  "dhaka",
  "dhanbad",
  "diwaniyah",
  "diyarbakir",
  "dnipro",
  "doha",
  "donetsk",
  "dongguan",
  "dongtai",
  "dongyang",
  "dongying",
  "dortmund",
  "douai-lens",
  "douala",
  "downers-grove",
  "dresden",
  "dubai",
  "dublin",
  "duesseldorf",
  "duisburg",
  "durango",
  "durban",
  "durg-bhilainagar",
  "durgapur",
  "dushanbe",
  "edinburgh",
  "edmonton",
  "ekurhuleni",
  "el-djelfa",
  "el-paso",
  "enshi",
  "enugu",
  "erbil",
  "erduosi-ordoss",
  "erode",
  "esfahan",
  "eskisehir",
  "eslamshahr",
  "essen",
  "ezhou",
  "fairfax",
  "faisalabad",
  "feicheng",
  "feira-de-santana",
  "fes",
  "firozabad",
  "florence",
  "florianopolis",
  "florida",
  "fort-lee",
  "fort-worth",
  "fortaleza",
  "foshan",
  "frankfurt",
  "freetown",
  "fresno",
  "fukuoka",
  "fuqing",
  "fushun-liaoning",
  "fuxin",
  "fuyang",
  "fuzhou-fujian",
  "fuzhou-jiangxi",
  "ganzhou",
  "gaomi",
  "gaoxiong",
  "gaoyou",
  "gaozhou",
  "gaya",
  "gaza",
  "gaziantep",
  "gebze",
  "general-santos-city",
  "geneva",
  "genoa",
  "glasgow",
  "goiania",
  "gold-coast",
  "goma",
  "gombe",
  "gomel",
  "gongyi",
  "gorakhpur",
  "gothenburg",
  "goyang",
  "grande-sao-luis",
  "grande-vitoria",
  "grenoble",
  "guadalajara",
  "guang-an",
  "guangyuan",
  "guangzhou",
  "guatemala-city",
  "guayaquil",
  "guigang",
  "guilin",
  "guiping",
  "guiyang",
  "gujranwala",
  "gulbarga",
  "guntur",
  "gurgaon",
  "gurugram",
  "guwahati",
  "gwalior",
  "gwangju",
  "haerbin",
  "hai-phong",
  "haicheng",
  "haifa",
  "haikou",
  "haimen",
  "haining",
  "hallandale-beach",
  "hamadan",
  "hamah",
  "hamburg",
  "hamhung",
  "hamilton",
  "hanchuan",
  "handan",
  "hangzhou",
  "hannover",
  "hanoi",
  "hanzhong",
  "harare",
  "hargeysa",
  "havana",
  "hawaii",
  "hebi",
  "hefei",
  "hegang",
  "helena",
  "helsinki",
  "hengshui",
  "hengyang",
  "herat",
  "hermosillo",
  "herndon",
  "heyuan",
  "heze",
  "hezhou",
  "hillah",
  "hiroshima",
  "ho-chi-minh-city",
  "hohhot",
  "homs",
  "hong-kong",
  "honolulu",
  "hosur",
  "houston",
  "huaian",
  "huaibei",
  "huaihua",
  "huainan",
  "huambo",
  "huangshi",
  "hubli-dharwad",
  "hufuf-mubarraz",
  "huizhou",
  "huludao",
  "huzhou",
  "hyderabad",
  "ibadan",
  "ibague",
  "ibb",
  "ikorodu",
  "illinois",
  "ilorin",
  "imphal",
  "imus",
  "incheon",
  "indiana",
  "indianapolis",
  "indore",
  "ipoh",
  "irbid",
  "irkutsk",
  "irvine",
  "islamabad",
  "istanbul",
  "izhevsk",
  "izmir",
  "jabalpur",
  "jacksonville",
  "jaipur",
  "jakarta",
  "jalandhar",
  "jalgaon",
  "jambi",
  "jammu",
  "jamnagar",
  "jamshedpur",
  "jeonju",
  "jersey-city",
  "jerusalem",
  "jhansi",
  "ji-nan-shandong",
  "jiamusi",
  "jiangmen",
  "jiangyin",
  "jianyang",
  "jiaozhou",
  "jiaozuo",
  "jiaxing",
  "jiddah",
  "jieyang",
  "jilin",
  "jincheng",
  "jingjiang",
  "jingzhou-hubei",
  "jinhua",
  "jining-shandong",
  "jinjiang",
  "jinzhong",
  "jinzhou",
  "jiujiang",
  "jixi-heilongjiang",
  "joao-pessoa",
  "jodhpur",
  "johannesburg",
  "johor-bahru",
  "joinville",
  "jos",
  "jubayl",
  "juiz-de-fora",
  "jundiai",
  "kabinda",
  "kabul",
  "kaduna",
  "kagoshima",
  "kahramanmaras",
  "kaifeng",
  "kakinada",
  "kalasin",
  "kampala",
  "kananga",
  "kandahar",
  "kannur",
  "kano",
  "kanpur",
  "kansas-city",
  "karachi",
  "karaganda",
  "karaj",
  "karbala",
  "kathmandu",
  "kayamkulam",
  "kayseri",
  "kazan",
  "kemerovo",
  "kentucky",
  "kerman",
  "kermanshah",
  "khabarovsk",
  "khamis-mushayt",
  "kharkiv",
  "khartoum",
  "khon-kaen",
  "khulna",
  "kiev",
  "kigali",
  "kikwit",
  "kingston",
  "kinshasa",
  "kirkuk",
  "kirov",
  "kisangani",
  "kitchener",
  "kitwe",
  "kochi",
  "kolhapur",
  "kolkata",
  "kollam",
  "kolwezi",
  "konya",
  "kota-kinabalu",
  "kottayam",
  "kozhikode",
  "krakow",
  "krasnodar",
  "krasnoyarsk",
  "kryvyi-rih",
  "kuala-lumpur",
  "kuantan",
  "kuching",
  "kuerle",
  "kumamoto",
  "kumasi",
  "kunming",
  "kunshan",
  "kurnool",
  "kuwait-city",
  "kyiv",
  "la-laguna",
  "la-paz",
  "la-plata",
  "lagos",
  "lahore",
  "laiwu",
  "laixi",
  "langfang",
  "lanzhou",
  "larkana",
  "las-vegas",
  "lattakia",
  "lausanne",
  "leicester",
  "leipzig",
  "leiyang",
  "leon-de-los-aldamas",
  "leshan",
  "lianyungang",
  "liaocheng",
  "liaoyang",
  "libreville",
  "liege",
  "likasi",
  "liling",
  "lille",
  "lilongwe",
  "lima",
  "linfen",
  "linhai",
  "linyi-shandong",
  "lipetsk",
  "lisboa",
  "lisbon",
  "liuan",
  "liupanshui",
  "liuyang",
  "liuzhou",
  "liverpool",
  "ljubljana",
  "lodz",
  "lokoja",
  "lome",
  "london",
  "london-ca",
  "londrina",
  "longhai",
  "longkou",
  "longyan",
  "los-angeles",
  "loudi",
  "louisville",
  "loum",
  "luanda",
  "lubango",
  "lubumbashi",
  "lucknow",
  "ludhiana",
  "luohe",
  "luoyang",
  "lusaka",
  "luzhou",
  "lviv",
  "lyon",
  "ma-anshan",
  "macao",
  "maceio",
  "madrid",
  "madurai",
  "maiduguri",
  "makassar",
  "makhachkala",
  "malaga",
  "malang",
  "malanje",
  "malappuram",
  "malatya",
  "malegaon",
  "managua",
  "manama",
  "manaus",
  "manchester",
  "mandalay",
  "mangalore",
  "manila",
  "maoming",
  "maputo",
  "mar-del-plata",
  "maracaibo",
  "maracay",
  "marrakech",
  "marseille",
  "maryland",
  "mashhad",
  "massachusetts",
  "matamoros",
  "mataram",
  "mathura",
  "matola",
  "matsuyama",
  "maturin",
  "mazar-e-sharif",
  "mbeya",
  "mbouda",
  "mbuji-mayi",
  "mecca",
  "medan",
  "medellin",
  "medina",
  "meerut",
  "meishan",
  "mekele",
  "meknes",
  "melbourne",
  "memphis",
  "mendoza",
  "menlo-park",
  "merca",
  "merida",
  "mersin",
  "mesa",
  "mexicali",
  "mexico-city",
  "miami",
  "mianyang-sichuan",
  "michigan",
  "milan",
  "miluo",
  "milwaukee",
  "minneapolis",
  "minnesota",
  "minsk",
  "misratah",
  "missouri",
  "mogadishu",
  "mombasa",
  "monrovia",
  "montana",
  "monterrey",
  "montevideo",
  "montreal",
  "moradabad",
  "morelia",
  "moscow",
  "mosul",
  "mountain-view",
  "mudanjiang",
  "multan",
  "mumbai",
  "munich",
  "murcia",
  "muscat",
  "muzaffarnagar",
  "muzaffarpur",
  "mwanza",
  "mysore",
  "n-djamena",
  "naberezhnye-tchelny",
  "nagoya",
  "nagpur",
  "nairobi",
  "najaf",
  "nakhon-pathom",
  "nakhon-ratchasima",
  "namangan",
  "nampula",
  "nanchang",
  "nanchong",
  "nanded-waghala",
  "nanjing",
  "nanning",
  "nanping",
  "nantes",
  "nantong",
  "nanyang-henan",
  "naples",
  "nashik",
  "nashville",
  "nasiriyah",
  "natal",
  "nay-pyi-taw",
  "ndola",
  "neijiang",
  "nellore",
  "nevada",
  "new-jersey",
  "new-mexico",
  "new-york",
  "newcastle-upon-tyne",
  "niamey",
  "nice",
  "niigata",
  "ningbo",
  "nizhniy-novgorod",
  "nnewi",
  "noida",
  "nonthaburi",
  "north-carolina",
  "north-sioux-city",
  "nottingham",
  "nouakchott",
  "novokuznetsk",
  "novosibirsk",
  "nurenberg",
  "ny",
  "nyala",
  "nyc",
  "oakland",
  "oaxaca-de-juarez",
  "odesa",
  "ogbomosho",
  "ohio",
  "okayama",
  "oklahoma",
  "oklahoma-city",
  "omsk",
  "onitsha",
  "oran",
  "oregon",
  "orenburg",
  "orumiyeh",
  "osaka",
  "oshogbo",
  "oslo",
  "ottawa",
  "ouagadougou",
  "oujda",
  "owerri",
  "pachuca-de-soto",
  "padang",
  "padova",
  "palembang",
  "palermo",
  "palo-alto",
  "panama-city",
  "panipat",
  "panjin",
  "panzhihua",
  "paris",
  "pathum-thani",
  "patiala",
  "patna",
  "pekan-baru",
  "pennsylvania",
  "penza",
  "pereira",
  "perm",
  "perth",
  "peshawar",
  "philadelphia",
  "phnom-penh",
  "phoenix",
  "pietermaritzburg",
  "pingdingshan-henan",
  "pingdu",
  "pingxiang-jiangxi",
  "pizhou",
  "plantation",
  "pleasanton",
  "pointe-noire",
  "pontianak",
  "port-au-prince",
  "port-elizabeth",
  "port-harcourt",
  "port-of-spain",
  "portland",
  "porto",
  "porto-alegre",
  "porto-velho",
  "poza-rica-de-hidalgo",
  "poznan",
  "prague",
  "pretoria",
  "princeton",
  "puducherry",
  "puebla",
  "puerto-vallarta",
  "pune",
  "puning",
  "putian",
  "puyang",
  "pyongyang",
  "qianjiang",
  "qingdao",
  "qingyuan",
  "qingzhou",
  "qinhuangdao",
  "qinzhou",
  "qiqihaer",
  "qitaihe",
  "qom",
  "quanzhou",
  "quebec-city",
  "queretaro",
  "quetta",
  "quito",
  "qujing",
  "quzhou",
  "rabat",
  "raipur",
  "rajahmundry",
  "rajkot",
  "rajshahi",
  "ranchi",
  "rasht",
  "raurkela",
  "rawalpindi",
  "rayong",
  "recife",
  "redmond",
  "remote",
  "reno",
  "renqiu",
  "reykjavik",
  "reynosa",
  "ribeirao-preto",
  "riga",
  "rio-de-janeiro",
  "riyadh",
  "rizhao",
  "rocklin",
  "rome",
  "rosario",
  "rostov-on-don",
  "rotterdam",
  "ruian",
  "rupganj",
  "rustenburg",
  "ryazan",
  "sacramento",
  "safaqis",
  "saharanpur",
  "saint-paul",
  "saint-petersburg",
  "sakarya",
  "salem",
  "salt-lake-city",
  "salta",
  "saltillo",
  "salvador",
  "salzburg",
  "samara",
  "samarinda",
  "samarkand",
  "samsun",
  "samut-prakan",
  "samut-sakhon",
  "san-antonio",
  "san-diego",
  "san-francisco",
  "san-jose",
  "san-jose-del-monte",
  "san-juan",
  "san-luis-potosi",
  "san-mateo",
  "san-miguel-de-tucuman",
  "san-pedro-sula",
  "san-salvador",
  "sanaa",
  "sangli",
  "sanhe",
  "sanliurfa",
  "sanmenxia",
  "santa-clara",
  "santa-cruz",
  "santa-fe",
  "santa-marta",
  "santa-monica",
  "santiago",
  "santo-domingo",
  "sanya",
  "sao-jose-dos-campos",
  "sao-paulo",
  "sapporo",
  "saratov",
  "sargodha",
  "scottsdale",
  "seattle",
  "sekondi-takoradi",
  "selangor",
  "semarang",
  "sendai",
  "seongnam",
  "seoul",
  "seregno",
  "setiabudi",
  "seville",
  "shah-alam",
  "shanghai",
  "shangqiu",
  "shangrao",
  "shangyu",
  "shantou",
  "shaoguan",
  "shaoxing",
  "shaoyang",
  "sharjah",
  "sheffield",
  "sheikhupura",
  "shenyang",
  "shenzhen",
  "sheridan",
  "shijiazhuang",
  "shimkent",
  "shiraz",
  "shishi",
  "shiyan",
  "shizuishan",
  "shizuoka",
  "shouguang",
  "shuangyashan",
  "shuozhou",
  "sialkot",
  "sihui",
  "siliguri",
  "singapore",
  "sioux-falls",
  "siping",
  "skopje",
  "sofia",
  "sokoto",
  "solapur",
  "somerville",
  "songkhla",
  "songyuan",
  "sorocaba",
  "soshanguve",
  "south-dakota",
  "southampton",
  "srinagar",
  "st-louis",
  "stamford",
  "stockholm",
  "stuttgart",
  "suining-sichuan",
  "sukkur",
  "sulaimaniya",
  "suqian",
  "surabaya",
  "surakarta",
  "surat",
  "surat-thani",
  "suweon",
  "suzhou",
  "sydney",
  "sylhet",
  "tabriz",
  "tabuk",
  "taian-shandong",
  "taicang",
  "taif",
  "tainan",
  "taipei",
  "taishan",
  "taixing",
  "taiyuan-shanxi",
  "taiz",
  "taizhong",
  "taizhou-jiangsu",
  "taizhou-zhejiang",
  "tallinn",
  "tamale",
  "tampa",
  "tampico",
  "tanger",
  "tangerang",
  "tangshan-hebei",
  "tanta",
  "taoyuan",
  "tashkent",
  "tasikmalaya",
  "tbilisi",
  "tegucigalpa",
  "tehran",
  "tel-aviv",
  "tengzhou",
  "tennessee",
  "tepic",
  "teresina",
  "texas",
  "the-hague",
  "thessaloniki",
  "thiruvananthapuram",
  "thoothukkudi",
  "thrissur",
  "tianjin",
  "tianmen",
  "tianshui",
  "tijuana",
  "tirana",
  "tiruchirappalli",
  "tirunelveli",
  "tirupati",
  "tiruppur",
  "tlaxcala",
  "tokyo",
  "toluca-de-lerdo",
  "tolyatti",
  "tomsk",
  "tongchuan",
  "tonghua",
  "tongliao",
  "tongling",
  "tongxiang",
  "toronto",
  "toulon",
  "toulouse",
  "tripoli",
  "trujillo",
  "tshikapa",
  "tucson",
  "tunis",
  "turin",
  "tuxtla-gutierrez",
  "tyumen",
  "uberlandia",
  "ubon-ratchathani",
  "udaipur",
  "udon-thani",
  "ufa",
  "uige",
  "ujjain",
  "ulaanbaatar",
  "ulsan",
  "ulyanovsk",
  "umuahia",
  "urumqi",
  "utah",
  "utrecht",
  "utsunomiya",
  "uvira",
  "uyo",
  "vadodara",
  "vale-do-aco",
  "valencia",
  "valledupar",
  "valparaiso",
  "van",
  "vancouver",
  "varanasi",
  "vellore",
  "venezia",
  "veracruz",
  "vereeniging",
  "verona",
  "vienna",
  "vientiane",
  "vijayawada",
  "villahermosa",
  "villavicencio",
  "vilnius",
  "virginia",
  "visakhapatnam",
  "vladivostok",
  "volgograd",
  "voronezh",
  "warangal",
  "warri",
  "warsaw",
  "washington",
  "weifang",
  "weihai",
  "weinan",
  "wenling",
  "wenzhou",
  "west-rand",
  "west-yorkshire",
  "wilmington",
  "winnipeg",
  "wisconsin",
  "wroclaw",
  "wuhai",
  "wuhan",
  "wuhu-anhui",
  "wuxi",
  "wuzhou",
  "wyoming",
  "xalapa",
  "xi-an-shaanxi",
  "xiamen",
  "xiangtan-hunan",
  "xiangyang",
  "xiantao",
  "xianyang-shaanxi",
  "xiaogan",
  "xinbei",
  "xinghua",
  "xingning",
  "xingtai",
  "xining",
  "xinmi",
  "xintai",
  "xinxiang",
  "xinyang",
  "xinyi",
  "xinyu",
  "xiongan",
  "xuchang",
  "xuzhou",
  "yan-an",
  "yancheng-jiangsu",
  "yangjiang",
  "yangon",
  "yangquan",
  "yangzhou",
  "yanji",
  "yanshi",
  "yantai",
  "yaounde",
  "yaroslavl",
  "yazd",
  "yekaterinburg",
  "yerevan",
  "yibin",
  "yichang",
  "yichun-heilongjiang",
  "yichun-jiangxi",
  "yinchuan",
  "yingkou",
  "yiwu",
  "yiyang-hunan",
  "yongin",
  "yongkang",
  "yongzhou",
  "yueqing",
  "yueyang",
  "yulin-guangxi",
  "yulin-shaanxi",
  "yuncheng",
  "yuxi",
  "yuyao",
  "zagreb",
  "zahedan",
  "zamboanga-city",
  "zanzibar",
  "zaoyang",
  "zaozhuang",
  "zaporizhzhya",
  "zaragoza",
  "zaria",
  "zarqa",
  "zhangjiagang",
  "zhangjiakou",
  "zhangzhou",
  "zhanjiang",
  "zhaodong",
  "zhaoqing",
  "zhengzhou",
  "zhenjiang-jiangsu",
  "zhongshan",
  "zhoukou",
  "zhoushan",
  "zhucheng",
  "zhuhai",
  "zhuji",
  "zhumadian",
  "zhuzhou",
  "zibo",
  "zigong",
  "zinder",
  "ziyang",
  "zug",
  "zunyi",
  "zurich",
] as const;

export type CitySlug = (typeof CITIES)[number];

/** Maps every country slug to the region it belongs to. Covers all of COUNTRIES. */
export const COUNTRY_REGION: Record<CountrySlug, RegionSlug> = {
  argentina: "south-america",
  armenia: "asia",
  australia: "oceania",
  austria: "europe",
  azerbaijan: "asia",
  bangladesh: "asia",
  belarus: "europe",
  belgium: "europe",
  bolivia: "south-america",
  brazil: "south-america",
  bulgaria: "europe",
  cameroon: "africa",
  canada: "north-america",
  "cayman-islands": "north-america",
  chile: "south-america",
  china: "asia",
  colombia: "south-america",
  "costa-rica": "north-america",
  croatia: "europe",
  "czech-republic": "europe",
  denmark: "europe",
  djibouti: "africa",
  "dominican-republic": "north-america",
  ecuador: "south-america",
  egypt: "africa",
  estonia: "europe",
  finland: "europe",
  france: "europe",
  georgia: "asia",
  germany: "europe",
  greece: "europe",
  guatemala: "north-america",
  "hong-kong": "asia",
  hungary: "europe",
  iceland: "europe",
  india: "asia",
  indonesia: "asia",
  ireland: "europe",
  israel: "asia",
  italy: "europe",
  "ivory-coast": "africa",
  japan: "asia",
  kazakhstan: "asia",
  kenya: "africa",
  kuwait: "asia",
  kyrgyzstan: "asia",
  latvia: "europe",
  lebanon: "asia",
  lithuania: "europe",
  luxembourg: "europe",
  malaysia: "asia",
  mexico: "north-america",
  morocco: "africa",
  netherlands: "europe",
  "new-zealand": "oceania",
  nicaragua: "north-america",
  nigeria: "africa",
  norway: "europe",
  pakistan: "asia",
  panama: "north-america",
  peru: "south-america",
  philippines: "asia",
  poland: "europe",
  portugal: "europe",
  "puerto-rico": "north-america",
  romania: "europe",
  serbia: "europe",
  singapore: "asia",
  "south-africa": "africa",
  "south-korea": "asia",
  spain: "europe",
  sweden: "europe",
  switzerland: "europe",
  taiwan: "asia",
  thailand: "asia",
  tunisia: "africa",
  turkey: "asia",
  uganda: "africa",
  ukraine: "europe",
  "united-arab-emirates": "asia",
  "united-kingdom": "europe",
  "united-states": "north-america",
  uruguay: "south-america",
  uzbekistan: "asia",
  venezuela: "south-america",
  vietnam: "asia",
  yemen: "asia",
};

/**
 * Maps the major tech/finance-hub cities (and every city linked from site navigation) to
 * their country. Not every entry in CITIES has a mapping here - only cities verified to
 * matter for landing pages are covered.
 */
export const CITY_COUNTRY: Partial<Record<CitySlug, CountrySlug>> = {
  amsterdam: "netherlands",
  atlanta: "united-states",
  austin: "united-states",
  bangkok: "thailand",
  berlin: "germany",
  boston: "united-states",
  chicago: "united-states",
  dubai: "united-arab-emirates",
  dublin: "ireland",
  "hong-kong": "hong-kong",
  lisbon: "portugal",
  london: "united-kingdom",
  "los-angeles": "united-states",
  "new-york": "united-states",
  "san-francisco": "united-states",
  singapore: "singapore",
  sydney: "australia",
  "tel-aviv": "israel",
  toronto: "canada",
  vancouver: "canada",
  paris: "france",
  madrid: "spain",
  barcelona: "spain",
  milan: "italy",
  rome: "italy",
  zurich: "switzerland",
  geneva: "switzerland",
  munich: "germany",
  frankfurt: "germany",
  warsaw: "poland",
  prague: "czech-republic",
  budapest: "hungary",
  bucharest: "romania",
  kyiv: "ukraine",
  istanbul: "turkey",
  seoul: "south-korea",
  tokyo: "japan",
  osaka: "japan",
  shanghai: "china",
  beijing: "china",
  shenzhen: "china",
  taipei: "taiwan",
  bangalore: "india",
  mumbai: "india",
  delhi: "india",
  hyderabad: "india",
  jakarta: "indonesia",
  manila: "philippines",
  "kuala-lumpur": "malaysia",
  "ho-chi-minh-city": "vietnam",
  hanoi: "vietnam",
  "sao-paulo": "brazil",
  "rio-de-janeiro": "brazil",
  "buenos-aires": "argentina",
  santiago: "chile",
  bogota: "colombia",
  lima: "peru",
  "mexico-city": "mexico",
  montreal: "canada",
  seattle: "united-states",
  denver: "united-states",
  miami: "united-states",
  dallas: "united-states",
  houston: "united-states",
  phoenix: "united-states",
  philadelphia: "united-states",
  "san-diego": "united-states",
  washington: "united-states",
  portland: "united-states",
  nashville: "united-states",
  "cape-town": "south-africa",
  johannesburg: "south-africa",
  lagos: "nigeria",
  nairobi: "kenya",
  cairo: "egypt",
  casablanca: "morocco",
  melbourne: "australia",
  brisbane: "australia",
  perth: "australia",
  auckland: "new-zealand",
  stockholm: "sweden",
  oslo: "norway",
  copenhagen: "denmark",
  helsinki: "finland",
  vienna: "austria",
  brussels: "belgium",
  tallinn: "estonia",
  riga: "latvia",
  vilnius: "lithuania",
  sofia: "bulgaria",
  belgrade: "serbia",
  zagreb: "croatia",
  athens: "greece",
  porto: "portugal",
  tbilisi: "georgia",
  yerevan: "armenia",
  baku: "azerbaijan",
  almaty: "kazakhstan",
  tashkent: "uzbekistan",
  "abu-dhabi": "united-arab-emirates",
  "kuwait-city": "kuwait",
  beirut: "lebanon",
  karachi: "pakistan",
  lahore: "pakistan",
  dhaka: "bangladesh",
};

export function countryForCity(city: CitySlug): CountrySlug | undefined {
  return CITY_COUNTRY[city];
}

export function regionForCountry(country: CountrySlug): RegionSlug {
  return COUNTRY_REGION[country];
}

export function regionForCity(city: CitySlug): RegionSlug | undefined {
  const country = CITY_COUNTRY[city];
  return country ? COUNTRY_REGION[country] : undefined;
}

const citiesByCountry = new Map<CountrySlug, CitySlug[]>();
for (const [city, country] of Object.entries(CITY_COUNTRY) as [CitySlug, CountrySlug][]) {
  const existing = citiesByCountry.get(country);
  if (existing) {
    existing.push(city);
  } else {
    citiesByCountry.set(country, [city]);
  }
}

export function citiesInCountry(country: CountrySlug): CitySlug[] {
  return citiesByCountry.get(country) ?? [];
}

const countriesByRegion = new Map<RegionSlug, CountrySlug[]>();
for (const [country, region] of Object.entries(COUNTRY_REGION) as [CountrySlug, RegionSlug][]) {
  const existing = countriesByRegion.get(region);
  if (existing) {
    existing.push(country);
  } else {
    countriesByRegion.set(region, [country]);
  }
}

export function countriesInRegion(region: RegionSlug): CountrySlug[] {
  return countriesByRegion.get(region) ?? [];
}

export const BENEFITS = [
  "4-day-work-week",
  "401k",
  "async",
  "company-retreats",
  "coworking-budget",
  "dental-insurance",
  "distributed-team",
  "equity-compensation",
  "free-gym-membership",
  "fsa",
  "home-office-budget",
  "hsa",
  "learning-budget",
  "medical-insurance",
  "mental-wellness-budget",
  "pay-in-crypto",
  "profit-sharing",
  "pseudonymous",
  "pto",
  "unlimited-vacation",
  "vision-insurance",
] as const;

export type BenefitSlug = (typeof BENEFITS)[number];

const tagSet = new Set<string>(JOB_TAGS);
const citySet = new Set<string>(CITIES);
const countrySet = new Set<string>(COUNTRIES);
const regionSet = new Set<string>(REGIONS);
const benefitSet = new Set<string>(BENEFITS);
const salaryRoleSet = new Set<string>(SALARY_ROLES);
const nonTechSalaryRoleSet = new Set<string>(NON_TECH_SALARY_ROLES);
const senioritySet = new Set<string>(SENIORITY_SLUGS);

export function isJobTag(slug: string): slug is JobTag {
  return tagSet.has(slug);
}

export function isCitySlug(slug: string): slug is CitySlug {
  return citySet.has(slug);
}

export function isCountrySlug(slug: string): slug is CountrySlug {
  return countrySet.has(slug);
}

export function isRegionSlug(slug: string): slug is RegionSlug {
  return regionSet.has(slug);
}

export function isBenefitSlug(slug: string): slug is BenefitSlug {
  return benefitSet.has(slug);
}

export function isSalaryRole(slug: string): slug is SalaryRole {
  return salaryRoleSet.has(slug);
}

export function isNonTechSalaryRole(slug: string): slug is NonTechSalaryRole {
  return nonTechSalaryRoleSet.has(slug);
}

export function isSenioritySlug(slug: string): boolean {
  return senioritySet.has(slug);
}

export function tagLabel(slug: string): string {
  if (slug === "non-tech") return "Non-tech";
  if (slug === "cto") return "CTO";
  if (slug === "ai") return "AI";
  if (slug === "nft") return "NFT";
  if (slug === "defi") return "DeFi";
  if (slug === "dao") return "DAO";
  if (slug === "hr") return "HR";
  if (slug === "evm") return "EVM";
  if (slug === "erc") return "ERC";
  if (slug === "pto") return "PTO";
  if (slug === "fsa") return "FSA";
  if (slug === "hsa") return "HSA";
  if (slug === "erc-20") return "ERC-20";
  if (slug === "web3js") return "Web3js";
  if (slug === "web3-py") return "Web3.py";
  return slug
    .split("-")
    .map((word) => word[0]!.toUpperCase() + word.slice(1))
    .join(" ");
}

export function slugifyTag(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function apiTagParam(slug: string): string {
  return slug.replaceAll("-", " ");
}

/** Curated tags for API sweep (one request per tag). Full JOB_TAGS is too large to sweep. */
export const API_SWEEP_TAGS: readonly string[] = [
  "ai",
  "analyst",
  "backend",
  "bitcoin",
  "blockchain",
  "community-manager",
  "crypto",
  "cryptography",
  "cto",
  "customer-support",
  "dao",
  "data-science",
  "defi",
  "design",
  "developer-relations",
  "devops",
  "entry-level",
  "evm",
  "executive",
  "finance",
  "front-end",
  "full-stack",
  "golang",
  "intern",
  "javascript",
  "junior",
  "legal",
  "marketing",
  "mobile",
  "nft",
  "non-tech",
  "product-manager",
  "project-manager",
  "react",
  "research",
  "rust",
  "sales",
  "senior",
  "smart-contract",
  "solana",
  "solidity",
  "trader",
];

export const API_SWEEP_COUNTRIES: readonly string[] = [
  "united-states",
  "united-kingdom",
  "germany",
  "france",
  "canada",
  "singapore",
  "australia",
  "india",
];
