import {DEFAULT_JOB_ADDONS,externalSalary,quoteJob,type JobDraft,type PostingDraft} from '@gaming/shared';
import type {PlatformEnv,Database} from '../platform';
import {editNativeListing} from './native-listings';
import {parsePosting} from './posting-input';
import {createNativeOrder,fulfillNativeOrder} from './native-orders';
import {orderById} from '../billing/employer-orders';
import {companyPlan,companyQuoteContext} from './company-plans';
import {canManageCompany} from './company-claims';
import {loadProductFlags} from './flags';
import {parseGreenhouseBoard} from '../../../crawler/src/sources/greenhouse';
import {parseLeverPostings} from '../../../crawler/src/sources/lever';
import {parseAshbyPostings} from '../../../crawler/src/sources/ashby';
import {fetchPublicText} from '../../../crawler/src/http/public-fetch';
type Integration={id:string;tenant_id:string;company_id:string;provider:'greenhouse'|'lever'|'ashby';board:string;mapping_json:string;confidential:number;enabled:number;name:string;domain:string;owner_user_id:string};
export async function saveAtsIntegration(db:Database,userId:string,tenantId:string,companyId:string,raw:Record<string,unknown>){
 if(!await canManageCompany(db,tenantId,userId,companyId)||(await companyPlan(db,companyId))?.tier!=='platinum')throw Error('Verified company ownership and an active Platinum plan are required.');
 const provider=String(raw.provider),board=String(raw.board??'').trim();if(!['greenhouse','lever','ashby'].includes(provider)||!/^[A-Za-z0-9_-]{1,120}$/.test(board))throw Error('Choose a supported ATS and its public board identifier.');
 const mapping=raw.mapping;if(!mapping||typeof mapping!=='object'||Array.isArray(mapping)||JSON.stringify(mapping).length>20000)throw Error('Review your required-field mapping.');
 await db.prepare(`INSERT INTO company_ats_integrations(id,tenant_id,company_id,provider,board,mapping_json,enabled,confidential,created_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(company_id) DO UPDATE SET provider=excluded.provider,board=excluded.board,mapping_json=excluded.mapping_json,enabled=excluded.enabled,confidential=excluded.confidential,last_success_at=NULL`).bind(crypto.randomUUID(),tenantId,companyId,provider,board,JSON.stringify(mapping),raw.enabled===true?1:0,raw.confidential===true?1:0,new Date().toISOString()).run();
 await db.prepare("UPDATE jobs SET listed=0 WHERE company_id=? AND commercial_origin='aggregated'").bind(companyId).run();
}
async function integrationById(db:Database,id:string){return db.prepare("SELECT i.*,c.name,c.domain,p.owner_user_id FROM company_ats_integrations i JOIN companies c ON c.id=i.company_id JOIN company_plans p ON p.company_id=i.company_id WHERE i.id=? AND i.enabled=1 AND p.tier='platinum' AND p.status IN ('active','trialing') AND p.renews_at>?").bind(id,new Date().toISOString()).first<Integration>();}
function postingFor(draft:JobDraft,i:Integration){const mapping=JSON.parse(i.mapping_json),salary=externalSalary(draft),remote=draft.remote==='unknown'?mapping.workArrangement:draft.remote;return {...mapping,title:draft.title,descriptionHtml:draft.descriptionHtml,companyId:i.company_id,companyName:i.name,companyUrl:'https://'+i.domain,workArrangement:remote,cityIds:remote==='remote'?[]:mapping.cityIds??[],salaryMin:salary?.min??mapping.salaryMin??null,salaryMax:salary?.max??mapping.salaryMax??null,salaryCurrency:salary?.currency??mapping.salaryCurrency??'USD',salaryPeriod:salary?.period??mapping.salaryPeriod??'yearly',applyMode:'redirect',applyUrl:draft.applyUrl,applicationsEmail:'',companyX:mapping.companyX??'',companyLinkedin:mapping.companyLinkedin??'',cryptoPaymentAvailable:mapping.cryptoPaymentAvailable===true,requiredSkillIds:mapping.requiredSkillIds??[],preferredSkillIds:mapping.preferredSkillIds??[],languages:mapping.languages??[],benefitSlugs:mapping.benefitSlugs??[]} as PostingDraft;}
export async function syncCompanyAts(env:Pick<PlatformEnv,'DB'>,id:string,now=new Date()){
 const i=await integrationById(env.DB,id);if(!i||!await canManageCompany(env.DB,i.tenant_id,i.owner_user_id,i.company_id))return;if(!(await loadProductFlags(env.DB,i.tenant_id)).PRODUCT_ATS_INTEGRATIONS)return;
 const token=crypto.randomUUID(),at=now.toISOString(),claim=await env.DB.prepare('UPDATE company_ats_integrations SET lease_token=?,lease_until=?,last_attempt_at=? WHERE id=? AND (lease_until IS NULL OR lease_until<=?)').bind(token,new Date(now.getTime()+300000).toISOString(),at,id,at).run();if(!claim.meta?.changes)return;
 try{const board=encodeURIComponent(i.board),url=i.provider==='greenhouse'?`https://boards-api.greenhouse.io/v1/boards/${board}/jobs?content=true`:i.provider==='lever'?`https://api.lever.co/v0/postings/${board}?mode=json`:`https://api.ashbyhq.com/posting-api/job-board/${board}?includeCompensation=true`;
 const response=await fetchPublicText(url,(url,init)=>fetch(url,{...init,redirect:'error'}),'NodeworkBot/1.0');if(response.status<200||response.status>=300)throw Error('ATS returned HTTP '+response.status);
 const drafts=i.provider==='greenhouse'?parseGreenhouseBoard(response.body,i.name):i.provider==='lever'?parseLeverPostings(response.body,i.name):parseAshbyPostings(response.body,i.name);if(drafts.length>1000)throw Error('Board exceeds 1,000 jobs; use a scoped board. Nothing was closed.');
 const references=cachedReferences(env.DB);for(const d of drafts){let raw:Record<string,any>={};try{raw=JSON.parse(d.rawJson);}catch{}const externalId=String(raw.id??d.applyUrl),posting=postingFor(d,i);let error:string|null=null;try{await parsePosting(references,i.tenant_id,posting);}catch(e){error=e instanceof Error?e.message:'Missing required fields';}
 await env.DB.prepare(`INSERT INTO company_ats_jobs(id,integration_id,external_id,title,source_url,raw_json,posting_json,validation_error,status,seen_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(integration_id,external_id) DO UPDATE SET title=excluded.title,source_url=excluded.source_url,raw_json=excluded.raw_json,posting_json=CASE WHEN company_ats_jobs.job_id IS NULL THEN excluded.posting_json ELSE company_ats_jobs.posting_json END,validation_error=excluded.validation_error,status=CASE WHEN company_ats_jobs.job_id IS NULL AND company_ats_jobs.status<>'checkout' THEN excluded.status ELSE company_ats_jobs.status END,seen_at=excluded.seen_at,updated_at=excluded.updated_at`).bind(crypto.randomUUID(),id,externalId,d.title,d.applyUrl,d.rawJson,JSON.stringify(posting),error,error?'incomplete':'ready',at,at).run();
 if(!error){const published=await env.DB.prepare("SELECT job_id FROM company_ats_jobs WHERE integration_id=? AND external_id=? AND status='published' AND job_id IS NOT NULL").bind(id,externalId).first<{job_id:string}>();if(published)await editNativeListing(env.DB,i.owner_user_id,published.job_id,posting,now);}}

 // Only a fully fetched and parsed board may close missing jobs.
 await env.DB.batch([env.DB.prepare('UPDATE jobs SET listed=0 WHERE id IN(SELECT job_id FROM company_ats_jobs WHERE integration_id=? AND seen_at<? AND job_id IS NOT NULL)').bind(id,at),env.DB.prepare('UPDATE employer_listings SET closed_at=? WHERE job_id IN(SELECT job_id FROM company_ats_jobs WHERE integration_id=? AND seen_at<? AND job_id IS NOT NULL) AND closed_at IS NULL').bind(at,id,at),env.DB.prepare("UPDATE company_ats_jobs SET status='closed' WHERE integration_id=? AND seen_at<?").bind(id,at),env.DB.prepare('UPDATE company_ats_integrations SET last_success_at=?,last_error=NULL,lease_until=NULL WHERE id=? AND lease_token=?').bind(at,id,token)]);
 }catch(error){await env.DB.prepare('UPDATE company_ats_integrations SET last_error=?,lease_until=NULL WHERE id=? AND lease_token=?').bind(error instanceof Error?error.message.slice(0,300):'ATS sync failed',id,token).run();throw error;}
}
export async function publishReadyAtsDrafts(env:Pick<PlatformEnv,'DB'>,tenantId:string,now=new Date()){
 const flags=await loadProductFlags(env.DB,tenantId);if(!flags.PRODUCT_ATS_INTEGRATIONS)return;
 await recoverAtsPublications(env,tenantId,now);
 const drafts=await env.DB.prepare("SELECT a.id,a.posting_json,a.integration_id FROM company_ats_jobs a JOIN company_ats_integrations i ON i.id=a.integration_id WHERE i.tenant_id=? AND i.enabled=1 AND a.job_id IS NULL AND a.status='ready' ORDER BY a.updated_at,a.id LIMIT 10").bind(tenantId).all<{id:string;posting_json:string;integration_id:string}>();
 for(const d of drafts.results){const i=await integrationById(env.DB,d.integration_id);if(!i||!await canManageCompany(env.DB,tenantId,i.owner_user_id,i.company_id))continue;let orderId:string|null=null;try{const context=await companyQuoteContext(env.DB,i.owner_user_id,i.company_id,false,now),addons={...DEFAULT_JOB_ADDONS,confidential:!!i.confidential};const quote=quoteJob(addons,context.context);if(quote.totalCents>0){await env.DB.prepare("UPDATE company_ats_jobs SET status='awaiting_payment',validation_error='Your included allowance is exhausted or this option has an extra charge. Review and pay explicitly to publish.' WHERE id=? AND status='ready'").bind(d.id).run();continue;}
 // Claim before reserving credits; a second scheduled invocation cannot publish the same draft.
 const claimed=await env.DB.prepare("UPDATE company_ats_jobs SET status='publishing',updated_at=? WHERE id=? AND status='ready' AND job_id IS NULL").bind(now.toISOString(),d.id).run();if(!claimed.meta?.changes)continue;
 orderId=crypto.randomUUID();const order=await createNativeOrder(env.DB,{id:orderId,tenantId,userId:i.owner_user_id,listing:JSON.parse(d.posting_json),addons,flags},now);await env.DB.prepare('UPDATE company_ats_jobs SET order_id=? WHERE id=?').bind(orderId,d.id).run();
 await env.DB.prepare('UPDATE employer_orders SET stripe_session_id=? WHERE id=? AND stripe_session_id IS NULL').bind('credit:'+orderId,orderId).run();const stored=await orderById(env.DB,order.id);if(!stored)throw Error('Reserved order not found');await fulfillNativeOrder(env.DB,stored,{id:'credit:'+orderId,payment_status:'no_payment_required',currency:'usd',amount_subtotal:0,amount_total:0,livemode:false},'credit:'+orderId,now);
 }catch(error){if(orderId)await env.DB.batch([env.DB.prepare("UPDATE employer_orders SET status='cancelled' WHERE id=? AND status='pending' AND stripe_session_id IS NULL").bind(orderId),env.DB.prepare("UPDATE plan_credit_reservations SET status='released' WHERE order_id=? AND status='held' AND EXISTS(SELECT 1 FROM employer_orders WHERE id=? AND status='cancelled')").bind(orderId,orderId)]);await env.DB.prepare("UPDATE company_ats_jobs SET status='needs_review',validation_error=? WHERE id=? AND job_id IS NULL").bind(error instanceof Error?error.message:'Publication needs review',d.id).run();}}
}

async function recoverAtsPublications(env:Pick<PlatformEnv,'DB'>,tenantId:string,now:Date){
 const rows=await env.DB.prepare("SELECT a.id,a.order_id FROM company_ats_jobs a JOIN company_ats_integrations i ON i.id=a.integration_id WHERE i.tenant_id=? AND a.status='publishing' AND a.updated_at<? LIMIT 20").bind(tenantId,new Date(now.getTime()-10*60000).toISOString()).all<{id:string;order_id:string|null}>();
 for(const row of rows.results){const order=row.order_id?await orderById(env.DB,row.order_id):null;
 if(order?.status==='paid'){await env.DB.prepare("UPDATE company_ats_jobs SET status='published',job_id=?,validation_error=NULL WHERE id=?").bind('paid:'+order.id,row.id).run();continue;}
 if(order?.status==='pending'&&order.total_cents===0){await env.DB.prepare('UPDATE employer_orders SET stripe_session_id=? WHERE id=? AND stripe_session_id IS NULL').bind('credit:'+order.id,order.id).run();const stored=await orderById(env.DB,order.id);if(stored?.stripe_session_id==='credit:'+order.id){try{await fulfillNativeOrder(env.DB,stored,{id:stored.stripe_session_id,payment_status:'no_payment_required',currency:'usd',amount_subtotal:0,amount_total:0,livemode:false},stored.stripe_session_id,now);continue;}catch{}}}
 await env.DB.prepare("UPDATE company_ats_jobs SET status='needs_review',validation_error='Interrupted publication. Review its linked order before publishing again.' WHERE id=? AND job_id IS NULL").bind(row.id).run();
 }
}

function cachedReferences(db:Database):Database{const cache=new Map<string,Promise<any>>();return {prepare(sql){let values:unknown[]=[];const statement={bind(...args:unknown[]){values=args;return statement;},first<T>(column?:string):Promise<T|null>{const key=sql+JSON.stringify(values)+':first:'+column;if(!cache.has(key))cache.set(key,db.prepare(sql).bind(...values).first<T>(column));return cache.get(key)!;},all<T>():Promise<{results:T[]}>{const key=sql+JSON.stringify(values)+':all';if(!cache.has(key))cache.set(key,db.prepare(sql).bind(...values).all<T>());return cache.get(key)!;},run(){return db.prepare(sql).bind(...values).run();}};return statement;},batch(statements){return db.batch(statements);}};}
