import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {DEFAULT_JOB_ADDONS,PRODUCT_FLAGS,effectiveProductFlags,selectDailyFeatured,rebuildSalaryInsights,enqueueSocialPosts,prepareWeeklyNewsletter} from '@gaming/shared';
import {testDatabase} from '../test-db';
import {saveAtsIntegration,syncCompanyAts,publishReadyAtsDrafts} from './ats';
import {newsletterContent} from '@gaming/shared';
import {createNativeOrder,fulfillNativeOrder} from './native-orders';
import {orderById} from '../billing/employer-orders';
import {approveCompanyClaim} from './company-claims';
import {companyMembership,inviteTeamMember,acceptTeamInvitation,companyQuoteContext} from './company-plans';
import {saveCandidateProfile,candidateDetails,publicCandidate} from './candidates';
import {recordNativeApplication,applicationState} from './applications';
import {updateApplication} from '../jobs/candidate-applications';
import {talentSearch,inviteCandidate,refreshJobShortlist} from './talent';
import {submitCompanyReview,moderateCompanyReview,readableCompanyReviews,respondToReview} from './reviews';
import {listJobs,getJobBySlug} from '../jobs/queries';
import {reversePayment} from '../billing/reversals';
import {createProductOrder,fulfillProductPayment,syncProductSubscription} from './billing';
let state:ReturnType<typeof testDatabase>;
const tenantId='tenant:gaming',flags=effectiveProductFlags(Object.fromEntries(PRODUCT_FLAGS.map(f=>[f,true]))),now=new Date(),future=new Date(now.getTime()+365*86400000).toISOString();
const listing={title:'Protocol Engineer',descriptionHtml:'<p>Build reliable blockchain infrastructure, collaborate with security engineers, document design decisions and improve the reliability of public APIs. You will review code, write meaningful integration checks and support releases.</p>',companyId:null as string|null,companyName:'Workflow Company',companyUrl:'https://workflow.example',salaryMin:100000,salaryMax:150000,salaryCurrency:'USD',salaryPeriod:'yearly',cryptoPaymentAvailable:true,workArrangement:'remote',cityIds:[],eligibility:{mode:'geo',regionIds:['country:IT']},requiredSkillIds:['skill:rust'],preferredSkillIds:['skill:solidity'],languages:[{code:'en',level:'B2',kind:'required'}],benefitSlugs:[],applyMode:'redirect',applyUrl:'https://workflow.example/apply',applicationsEmail:'',companyX:'',companyLinkedin:''};
function addUser(id:string){state.sql.prepare('INSERT INTO users(id,tenant_id,email,email_verified,name,created_at) VALUES(?,?,?,1,?,?)').run(id,tenantId,id+'@personal.example',id,'2020-01-01');}
beforeEach(()=>{state=testDatabase();for(const id of ['owner','candidate','admin','teammate','second'])addUser(id);state.sql.exec(`INSERT INTO skills(id,slug,name,category,created_at) VALUES('skill:rust','rust','Rust','development','2020-01-01'),('skill:solidity','solidity','Solidity','development','2020-01-01'),('skill:typescript','typescript','TypeScript','development','2020-01-01');INSERT INTO reference_languages VALUES('en','English','English');INSERT INTO reference_countries VALUES('IT','Italy','EU');INSERT INTO regions VALUES('country:IT','Italy','country','["IT"]');INSERT INTO job_roles VALUES('role:protocol','Protocol Engineer','protocol-engineer','[]','["protocol engineer"]');`);for(const flag of PRODUCT_FLAGS)state.sql.prepare('INSERT INTO feature_flags(tenant_id,name,enabled,updated_at) VALUES(?,?,1,?)').run(tenantId,flag,now.toISOString());});
afterEach(()=>{state.sql.close();vi.restoreAllMocks();vi.unstubAllGlobals();});
async function publish(id='job',addons={...DEFAULT_JOB_ADDONS},raw=listing){const order=await createNativeOrder(state.db,{id,tenantId,userId:'owner',listing:raw,addons,flags:{...flags,EARLY_ACCESS_FREE_FIRST_POST:false}},now);state.sql.prepare('UPDATE employer_orders SET stripe_session_id=? WHERE id=?').run('cs_test_'+id,id);await fulfillNativeOrder(state.db,(await orderById(state.db,id))!,{id:'cs_test_'+id,payment_status:order.total_cents?'paid':'no_payment_required',currency:'usd',amount_subtotal:order.total_cents,amount_total:order.total_cents,payment_intent:order.total_cents?'pi_'+id:undefined,livemode:false},'event:'+id,now);return state.sql.prepare('SELECT * FROM jobs WHERE id=?').get('paid:'+id);}
async function company(tier='platinum'){const job=await publish();const claim=state.sql.prepare("SELECT id FROM company_claims WHERE status='pending'").get();await approveCompanyClaim(state.db,{claimId:claim.id,tenantId,adminId:'admin',reason:'Domain ownership manually verified'},now);state.sql.prepare('INSERT INTO company_plans VALUES(?,?,?,?,?,?,?,?,?,?)').run(job.company_id,'owner',tier,'sub_company','cus_company','active',now.toISOString(),future,0,now.toISOString());state.sql.prepare('INSERT INTO company_plan_periods(id,company_id,provider_ref,tier,granted,period_start,expires_at,payment_intent_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run('period',job.company_id,'sub_company',tier,tier==='starter'?3:0,now.toISOString(),future,'pi_plan',now.toISOString());return job;}
async function profile(id='candidate',country='IT'){await saveCandidateProfile(state.db,id,{handle:id+'-handle',displayName:'Candidate '+id,headline:'Protocol engineer',bio:'I build distributed systems.',cityId:null,countryCode:country,utcOffset:120,availability:'open_to_work',workArrangement:'remote',openToCrypto:true,publicProfile:false,discoverable:true,featuredOptIn:true,skillIds:['skill:rust','skill:solidity','skill:typescript'],languages:[{code:'en',level:'C1'}],links:[{kind:'github',url:'https://github.com/example'}],experience:[{company:'Example',title:'Engineer',startDate:'2021-01',endDate:'2025-01',description:'Protocol development'}]},now);}
function premium(id='candidate'){state.sql.prepare("INSERT INTO candidate_subscriptions(user_id,plan,status,provider_ref,renews_at,updated_at) VALUES(?,'annual','active',?,?,?)").run(id,'sub_'+id,future,now.toISOString());}
const files={async put(){},async get(){return null;},async delete(){}};
it('reserves plan credits once and bounds verified team seats including pending invitations',async()=>{const j=await company('starter');await inviteTeamMember(state.db,tenantId,'owner',j.company_id,'teammate@personal.example',now);await expect(inviteTeamMember(state.db,tenantId,'owner',j.company_id,'second@personal.example',now)).rejects.toThrow('Seat');const invitation=state.sql.prepare('SELECT id FROM company_team_invitations').get();await acceptTeamInvitation(state.db,{id:'teammate',email:'teammate@personal.example',emailVerified:true},invitation.id,now);expect(await companyMembership(state.db,'teammate',j.company_id)).toMatchObject({role:'member'});const p=await publish('credit',{...DEFAULT_JOB_ADDONS},{...listing,companyId:j.company_id});expect(p.plan_tier).toBe('starter');expect(state.sql.prepare("SELECT total_cents FROM employer_orders WHERE id='credit'").get().total_cents).toBe(0);expect((await companyQuoteContext(state.db,'owner',j.company_id,false,now)).context.availableCredits).toBe(2);state.sql.exec("UPDATE company_plans SET status='canceled'");expect(await companyMembership(state.db,'teammate',j.company_id)).toBeNull();expect(await companyMembership(state.db,'owner',j.company_id)).not.toBeNull();});
it('enforces early access, freezes application snapshots and records a stage change once',async()=>{const j=await publish('early',{...DEFAULT_JOB_ADDONS,earlyAccess:true});await profile();const env={DB:state.db,FILES:files};await expect(recordNativeApplication(env,{tenantId,jobId:j.id,user:{id:'candidate',email:'candidate@personal.example'},mode:'redirect'},now)).rejects.toThrow('Early Access');premium();await recordNativeApplication(env,{tenantId,jobId:j.id,user:{id:'candidate',email:'candidate@personal.example'},mode:'redirect'},now);await recordNativeApplication(env,{tenantId,jobId:j.id,user:{id:'candidate',email:'candidate@personal.example'},mode:'redirect'},now);const a=state.sql.prepare('SELECT * FROM job_applications').get();expect(a.match_score).toBe(100);expect(JSON.parse(a.profile_snapshot_json)).not.toHaveProperty('email');expect(state.sql.prepare('SELECT COUNT(*) n FROM job_applications').get().n).toBe(1);await updateApplication(state.db,'owner',a.id,'interview','Internal note');await updateApplication(state.db,'owner',a.id,'interview','Another note');expect(state.sql.prepare("SELECT COUNT(*) n FROM application_stage_history WHERE stage='interview'").get().n).toBe(1);expect((await applicationState(state.db,tenantId,j.id,'candidate',now))?.application?.status).toBe('interview');});
it('searches canonical skills and eligibility, deduplicates invitations and bypasses early access',async()=>{const base=await company();const j=await publish('early',{...DEFAULT_JOB_ADDONS,earlyAccess:true},{...listing,companyId:base.company_id});await profile();const result=await talentSearch(state.db,{companyId:j.company_id,userId:'owner',jobId:j.id,filters:{skills:'skill:rust,skill:solidity',language:'en',level:'B2'}});expect(result.rows).toHaveLength(1);expect(result.rows[0].match_score).toBe(100);await refreshJobShortlist(state.db,j.id,now);expect(state.sql.prepare('SELECT COUNT(*) n FROM candidate_shortlists').get().n).toBe(1);await inviteCandidate(state.db,'owner',j.id,'candidate','shortlist','A suitable protocol role.',now);expect((await inviteCandidate(state.db,'owner',j.id,'candidate','shortlist','Same role',now)).duplicate).toBe(true);expect((await applicationState(state.db,tenantId,j.id,'candidate',now))?.locked).toBe(false);expect((await talentSearch(state.db,{companyId:j.company_id,userId:'owner',jobId:j.id,filters:{shortlist:'1'}})).rows).toHaveLength(0);});
it('keeps confidential jobs out of public queries and all distribution queues',async()=>{const base=await company();const j=await publish('secret',{...DEFAULT_JOB_ADDONS,confidential:true},{...listing,companyId:base.company_id});expect(await getJobBySlug(state.db,tenantId,j.slug)).toBeNull();expect((await listJobs(state.db,tenantId,{})).jobs.some(row=>row.id===j.id)).toBe(false);await enqueueSocialPosts(state.db,tenantId,now);await prepareWeeklyNewsletter(state.db,tenantId,now);expect(state.sql.prepare('SELECT COUNT(*) n FROM social_outbox WHERE job_id=?').get(j.id).n).toBe(0);expect(state.sql.prepare('SELECT COUNT(*) n FROM newsletter_jobs WHERE job_id=?').get(j.id).n).toBe(0);});
it('requires manually verified work before publishing review text and allows a basic company reply',async()=>{const j=await company();await profile();premium();const form=new FormData();for(const [k,v] of Object.entries({companyId:j.company_id,overall:'5',paid_on_time:'5',transparent_process:'4',would_work_again:'5',relationship:'employee',body:'I worked on protocol infrastructure with this team and was paid on time throughout my contract.'}))form.set(k,v);form.set('evidence',new File(['%PDF-1.7 employment proof'],'proof.pdf',{type:'application/pdf'}));const id=await submitCompanyReview({DB:state.db,FILES:files},{tenantId,userId:'candidate',form},now);expect(await readableCompanyReviews(state.db,j.company_id,true)).toHaveLength(0);await expect(moderateCompanyReview(state.db,{id,tenantId,adminId:'admin',action:'publish',reason:'Reviewed uploaded employment proof',employmentConfirmed:false},now)).rejects.toThrow('Verify');await moderateCompanyReview(state.db,{id,tenantId,adminId:'admin',action:'publish',reason:'Reviewed uploaded employment proof',employmentConfirmed:true},now);expect((await readableCompanyReviews(state.db,j.company_id,false))[0].body).toBeNull();state.sql.exec("UPDATE company_plans SET status='canceled'");await respondToReview(state.db,tenantId,'owner',id,'Thank you for working with our team.',now);expect((await readableCompanyReviews(state.db,j.company_id,true))[0].response).toContain('Thank you');await expect(submitCompanyReview({DB:state.db,FILES:files},{tenantId,userId:'owner',form},now)).rejects.toThrow('Only Premium candidates');});
it('selects an eligible featured member once and does not include native salaries in external cohorts',async()=>{await profile();premium();state.sql.exec("UPDATE profiles SET public_profile=1 WHERE user_id='candidate'");await selectDailyFeatured(state.db,tenantId,now);await selectDailyFeatured(state.db,tenantId,now);expect(state.sql.prepare('SELECT COUNT(*) n FROM featured_members').get().n).toBe(1);for(let i=0;i<6;i++)await publish('salary-'+i);await rebuildSalaryInsights(state.db,tenantId,now);expect(state.sql.prepare('SELECT COUNT(*) n FROM salary_stats').get().n).toBe(0);state.sql.exec("UPDATE jobs SET commercial_origin='aggregated',source='career_page';DELETE FROM product_daily_runs WHERE kind LIKE 'salaries:%'");await rebuildSalaryInsights(state.db,tenantId,now);expect(JSON.parse(state.sql.prepare("SELECT stats_json FROM salary_stats WHERE location_slug='all'").get().stats_json)).toMatchObject({count:6,median:125000});});
it('fulfills and reverses standalone verification and extension purchases idempotently',async()=>{const j=await publish();const order=await createProductOrder(state.db,{id:'extension',tenantId,userId:'owner',kind:'extension',choice:'30-days',payload:{jobId:j.id},flags},now);state.sql.prepare('UPDATE product_orders SET stripe_session_id=? WHERE id=?').run('cs_test_extension',order.id);order.stripe_session_id='cs_test_extension';const paid={id:order.stripe_session_id,metadata:{productOrderId:order.id},livemode:false,currency:'usd',amount_subtotal:order.total_cents,amount_total:order.total_cents,payment_status:'paid',payment_intent:'pi_extension'};await fulfillProductPayment(state.db,order,paid,'extension-event',now);expect(Date.parse(state.sql.prepare('SELECT expires_at FROM jobs WHERE id=?').get(j.id).expires_at)-Date.parse(j.expires_at)).toBe(30*86400000);await reversePayment(state.db,'pi_extension','refund-extension',now);expect(state.sql.prepare('SELECT expires_at FROM jobs WHERE id=?').get(j.id).expires_at).toBe(j.expires_at);});
it('grants a paid subscription once from validated Stripe state and revokes a refunded period',async()=>{const order=await createProductOrder(state.db,{id:'premium',tenantId,userId:'candidate',kind:'candidate_premium',choice:'annual',payload:{},flags},now);state.sql.prepare('UPDATE product_orders SET stripe_session_id=? WHERE id=?').run('cs_test_premium',order.id);const start=Math.floor(now.getTime()/1000),end=start+365*86400;const objects:Record<string,unknown>={subscriptions:{id:'sub_premium',livemode:false,metadata:{productOrderId:'premium'},customer:'cus_premium',latest_invoice:'in_premium',status:'active',items:{data:[{quantity:1,price:{currency:'usd',unit_amount:7900,recurring:{interval:'year',interval_count:1}}}]}},checkout:{id:'cs_test_premium',livemode:false,metadata:{productOrderId:'premium'},subscription:'sub_premium',currency:'usd',amount_subtotal:7900,amount_total:7900},invoices:{id:'in_premium',customer:'cus_premium',subscription:'sub_premium',status:'paid',currency:'usd',subtotal:7900,amount_paid:7900,payment_intent:'pi_premium',lines:{data:[{type:'subscription',period:{start,end}}]}}};vi.stubGlobal('fetch',vi.fn(async (url:string)=>Response.json(objects[url.includes('/subscriptions/')?'subscriptions':url.includes('/checkout/')?'checkout':'invoices'])));await syncProductSubscription(state.db,'sk_test_fixture','sub_premium',now);await syncProductSubscription(state.db,'sk_test_fixture','sub_premium',now);expect(state.sql.prepare('SELECT COUNT(*) n FROM product_subscription_invoices').get().n).toBe(1);await reversePayment(state.db,'pi_premium','refund-premium',now);expect(state.sql.prepare('SELECT status FROM candidate_subscriptions').get().status).toBe('refunded');vi.unstubAllGlobals();});

it('filters structured public requirements without including confidential jobs',async()=>{await publish();expect((await listJobs(state.db,tenantId,{workArrangement:'remote',language:'en',eligibleCountry:'IT',skillIds:['skill:rust']})).total).toBe(1);expect((await listJobs(state.db,tenantId,{eligibleCountry:'FR'})).total).toBe(0);expect((await listJobs(state.db,tenantId,{workArrangement:'hybrid'})).total).toBe(0);});
it('imports, publishes, updates and closes a managed ATS job without charging overages',async()=>{
 const base=await company();await saveAtsIntegration(state.db,'owner',tenantId,base.company_id,{provider:'greenhouse',board:'workflow',mapping:listing,enabled:true});const i=state.sql.prepare('SELECT id FROM company_ats_integrations').get();
 let title='Protocol Engineer',items=1;vi.stubGlobal('fetch',vi.fn(async()=>Response.json({jobs:items?[{id:101,title,absolute_url:'https://boards.greenhouse.io/workflow/jobs/101',content:listing.descriptionHtml,location:{name:'Remote'},updated_at:now.toISOString()}]:[]})));
 await syncCompanyAts({DB:state.db},i.id,now);await publishReadyAtsDrafts({DB:state.db},tenantId,now);const ats=state.sql.prepare('SELECT * FROM company_ats_jobs').get();expect(ats.status).toBe('published');expect(state.sql.prepare('SELECT commercial_origin FROM jobs WHERE id=?').get(ats.job_id).commercial_origin).toBe('native_ats');
 title='Senior Protocol Engineer';await syncCompanyAts({DB:state.db},i.id,new Date(now.getTime()+86400000));expect(state.sql.prepare('SELECT title FROM jobs WHERE id=?').get(ats.job_id).title).toBe(title);
 items=0;await syncCompanyAts({DB:state.db},i.id,new Date(now.getTime()+2*86400000));expect(state.sql.prepare('SELECT listed FROM jobs WHERE id=?').get(ats.job_id).listed).toBe(0);
});
it('composes public weekly newsletter sections without private profiles or confidential jobs',async()=>{const base=await company();await publish('private',{...DEFAULT_JOB_ADDONS,confidential:true},{...listing,companyId:base.company_id,title:'Private protocol opening'});await prepareWeeklyNewsletter(state.db,tenantId,now);const edition=state.sql.prepare('SELECT id FROM newsletter_editions').get();const text=await newsletterContent(state.db,edition.id,'https://nodework.test',now);expect(text).toContain('Protocol Engineer');expect(text).not.toContain('Private protocol opening');expect(text).toContain('utm_source=newsletter');});
