import {pricing,matchScore,containsDirectContact,type CompanyPlanTier} from '@gaming/shared';
import type {Database} from '../platform';
import {companyPlan,companyMembership} from './company-plans';
import {candidateDetails,candidateMatchProfile} from './candidates';
import {JOB_ACCESS_SQL} from './job-access';
import type {CanonicalPosting} from './posting-input';

export async function talentCompany(db:Database,userId:string,companyId?:string){
 const rows=await db.prepare(`SELECT p.company_id,c.name,p.tier FROM company_plans p JOIN companies c ON c.id=p.company_id WHERE p.status IN ('active','trialing') AND julianday(p.renews_at)>julianday('now') AND (? IS NULL OR p.company_id=?) AND EXISTS(SELECT 1 FROM company_members m WHERE m.company_id=p.company_id AND m.user_id=?) ORDER BY CASE p.tier WHEN 'platinum' THEN 0 WHEN 'scale' THEN 1 ELSE 2 END,c.name`).bind(companyId??null,companyId??null,userId).all<{company_id:string;name:string;tier:CompanyPlanTier}>();
 for(const row of rows.results)if(await companyMembership(db,userId,row.company_id))return row;return null;
}
export async function talentProfileAccess(db:Database,viewerId:string,candidateId:string){
 const profile=await db.prepare('SELECT public_profile,talent_pool_opt_in FROM profiles WHERE user_id=?').bind(candidateId).first<{public_profile:number;talent_pool_opt_in:number}>();if(!profile)return false;if(viewerId===candidateId||profile.public_profile)return true;if(!profile.talent_pool_opt_in)return false;
 const company=await talentCompany(db,viewerId);if(company?.tier==='platinum')return true;if(company&&pricing.plans[company.tier].shortlistInvites)return !!await db.prepare("SELECT s.job_id FROM candidate_shortlists s JOIN jobs j ON j.id=s.job_id WHERE s.candidate_id=? AND j.company_id=? AND j.listed=1 AND j.expires_at>? AND s.date>=? LIMIT 1").bind(candidateId,company.company_id,new Date().toISOString(),new Date(Date.now()-2*86400000).toISOString().slice(0,10)).first();return false;
}
export async function talentSearch(db:Database,input:{companyId:string;userId:string;jobId?:string;filters:Record<string,string|undefined>}){
 const plan=await companyPlan(db,input.companyId);if(!plan||!await companyMembership(db,input.userId,input.companyId))throw Error('An active company plan and verified company membership are required.');
 const shortlist=input.filters.shortlist==='1';if(shortlist?!pricing.plans[plan.tier].shortlistInvites:plan.tier!=='platinum')throw Error(shortlist?'Shortlists require Scale or Platinum.':'Talent Search requires Platinum.');
 const job=input.jobId?await db.prepare(`SELECT d.input_json FROM native_listing_details d JOIN jobs j ON j.id=d.job_id JOIN employer_listings l ON l.job_id=j.id WHERE j.id=? AND j.company_id=? AND ${JOB_ACCESS_SQL}`).bind(input.jobId,input.companyId,input.userId,input.userId).first<string>('input_json'):null;
 if(input.jobId&&!job)throw Error('Choose one of your native job posts.');
 const f=input.filters,conditions=['p.talent_pool_opt_in=1','p.product_profile_completed=1',"p.availability<>'not_looking'","NOT EXISTS(SELECT 1 FROM company_purchase_entitlements ce WHERE ce.user_id=p.user_id AND ce.status='active')"],values:unknown[]=[];
 if(f.candidate){conditions.push('p.user_id=?');values.push(f.candidate);}
 if(shortlist){conditions.push('p.completeness>=60',"NOT EXISTS(SELECT 1 FROM product_invitations i WHERE i.job_id=? AND i.candidate_id=p.user_id)","NOT EXISTS(SELECT 1 FROM authenticated_applications a WHERE a.job_id=? AND a.user_id=p.user_id)","CASE WHEN json_extract(r.input,'$.eligibility.mode') IS NULL THEN 1 WHEN json_extract(r.input,'$.eligibility.mode')='geo' THEN p.country_code IN(SELECT value FROM json_each(r.input,'$.eligibility.countryCodes')) ELSE CASE WHEN json_extract(r.input,'$.eligibility.utcFrom')<=json_extract(r.input,'$.eligibility.utcTo') THEN p.utc_offset BETWEEN json_extract(r.input,'$.eligibility.utcFrom') AND json_extract(r.input,'$.eligibility.utcTo') ELSE p.utc_offset>=json_extract(r.input,'$.eligibility.utcFrom') OR p.utc_offset<=json_extract(r.input,'$.eligibility.utcTo') END END");values.push(input.jobId,input.jobId);}
 if(f.snapshot==='1'&&input.jobId){conditions.push('EXISTS(SELECT 1 FROM candidate_shortlists ss WHERE ss.candidate_id=p.user_id AND ss.job_id=? AND ss.date=(SELECT MAX(date) FROM candidate_shortlists WHERE job_id=?))');values.push(input.jobId,input.jobId);}
 if(f.q){conditions.push("(p.headline LIKE ? ESCAPE '\\' OR EXISTS(SELECT 1 FROM experience_entries e WHERE e.user_id=p.user_id AND (e.title LIKE ? ESCAPE '\\' OR e.description LIKE ? ESCAPE '\\')))");const q='%'+f.q.slice(0,120).replace(/[\\%_]/g,'\\$&')+'%';values.push(q,q,q);}
 const skills=(f.skills??'').split(',').filter(Boolean).slice(0,30);if(skills.length){conditions.push(`(SELECT COUNT(*) FROM candidate_skills s WHERE s.user_id=p.user_id AND s.skill_id IN(SELECT value FROM json_each(?)))${f.skillMode==='or'?'>=1':'=?'}`);values.push(JSON.stringify([...new Set(skills)]));if(f.skillMode!=='or')values.push(new Set(skills).size);}
 if(f.language){conditions.push("EXISTS(SELECT 1 FROM candidate_languages lang WHERE lang.user_id=p.user_id AND lang.language_code=? AND instr('A1 A2 B1 B2 C1 C2 Native',lang.level)>=instr('A1 A2 B1 B2 C1 C2 Native',?))");values.push(f.language,['A1','A2','B1','B2','C1','C2','Native'].includes(f.level??'')?f.level:'A1');}
 if(f.country){conditions.push('p.country_code=?');values.push(f.country);}
 if(f.region){conditions.push('p.country_code IN(SELECT value FROM regions r,json_each(r.country_codes_json) WHERE r.id=?)');values.push(f.region);}
 for(const [key,column] of [['availability','availability'],['arrangement','remote_pref']] as const)if(f[key]){conditions.push('p.'+column+'=?');values.push(f[key]);}
 if(f.utcFrom&&f.utcTo){const from=Number(f.utcFrom),to=Number(f.utcTo);if(Number.isFinite(from)&&Number.isFinite(to)){conditions.push(from<=to?'p.utc_offset BETWEEN ? AND ?':'(p.utc_offset>=? OR p.utc_offset<=?)');values.push(from,to);}}
 if(f.crypto==='1')conditions.push('p.open_to_crypto=1');if(f.verified==='1')conditions.push('p.verified_at IS NOT NULL');
 if(f.completeness){conditions.push('p.completeness>=?');values.push(Math.max(0,Math.min(100,Number(f.completeness)||0)));}
 if(f.recent==='1')conditions.push("julianday(p.last_active_at)>=julianday('now','-30 days')");
 const premium="EXISTS(SELECT 1 FROM candidate_subscriptions s WHERE s.user_id=p.user_id AND s.status IN ('active','trialing') AND julianday(s.renews_at)>julianday('now'))";
 if(f.premium==='1')conditions.push(premium);
 const featured="EXISTS(SELECT 1 FROM featured_members fm WHERE fm.user_id=p.user_id AND fm.date=date('now') AND p.public_profile=1 AND p.featured_opt_in=1)";if(f.featured==='1')conditions.push(featured);
 // SQL computes the same weighted score as applications, so pagination never truncates the matching pool.
 let score='NULL';if(job){score=`ROUND(50*CASE WHEN json_array_length(json_extract(r.input,'$.requiredSkillIds'))=0 THEN 1.0 ELSE (SELECT COUNT(*)*1.0 FROM candidate_skills s WHERE s.user_id=p.user_id AND s.skill_id IN(SELECT value FROM json_each(r.input,'$.requiredSkillIds')))/json_array_length(json_extract(r.input,'$.requiredSkillIds')) END
 +20*CASE WHEN json_array_length(json_extract(r.input,'$.preferredSkillIds'))=0 THEN 1.0 ELSE (SELECT COUNT(*)*1.0 FROM candidate_skills s WHERE s.user_id=p.user_id AND s.skill_id IN(SELECT value FROM json_each(r.input,'$.preferredSkillIds')))/json_array_length(json_extract(r.input,'$.preferredSkillIds')) END
 +20*CASE WHEN EXISTS(SELECT 1 FROM json_each(r.input,'$.languages') req WHERE json_extract(req.value,'$.kind')='required' AND NOT EXISTS(SELECT 1 FROM candidate_languages cl WHERE cl.user_id=p.user_id AND cl.language_code=json_extract(req.value,'$.code') AND instr('A1 A2 B1 B2 C1 C2 Native',cl.level)>=instr('A1 A2 B1 B2 C1 C2 Native',json_extract(req.value,'$.level')))) THEN 0 WHEN json_array_length(json_extract(r.input,'$.languages'))=0 THEN 1.0 ELSE (SELECT COUNT(*)*1.0 FROM json_each(r.input,'$.languages') req WHERE EXISTS(SELECT 1 FROM candidate_languages cl WHERE cl.user_id=p.user_id AND cl.language_code=json_extract(req.value,'$.code') AND instr('A1 A2 B1 B2 C1 C2 Native',cl.level)>=instr('A1 A2 B1 B2 C1 C2 Native',json_extract(req.value,'$.level'))))/json_array_length(json_extract(r.input,'$.languages')) END
 +10*COALESCE(CASE WHEN json_extract(r.input,'$.eligibility.mode') IS NULL THEN 1 WHEN json_extract(r.input,'$.eligibility.mode')='geo' THEN p.country_code IN(SELECT value FROM json_each(r.input,'$.eligibility.countryCodes')) ELSE CASE WHEN json_extract(r.input,'$.eligibility.utcFrom')<=json_extract(r.input,'$.eligibility.utcTo') THEN p.utc_offset BETWEEN json_extract(r.input,'$.eligibility.utcFrom') AND json_extract(r.input,'$.eligibility.utcTo') ELSE p.utc_offset>=json_extract(r.input,'$.eligibility.utcFrom') OR p.utc_offset<=json_extract(r.input,'$.eligibility.utcTo') END END,0))`;}
 const page=Math.max(1,Math.min(10000,Number(f.page)||1)),rows=await db.prepare(`WITH r AS(SELECT ? AS input),pool AS(SELECT p.user_id,p.handle,p.display_name,p.headline,p.location,p.photo_url,p.last_active_at,p.availability,p.completeness,p.verified_at,p.open_to_crypto,(SELECT group_concat(l.name||' '||cl.level,', ') FROM candidate_languages cl JOIN reference_languages l ON l.code=cl.language_code WHERE cl.user_id=p.user_id) languages,${premium} AS premium,${featured} AS featured,COALESCE(${score},0) AS match_score,(SELECT group_concat(s.name,', ') FROM candidate_skills cs JOIN skills s ON s.id=cs.skill_id WHERE cs.user_id=p.user_id) AS skills FROM profiles p CROSS JOIN r WHERE ${conditions.join(' AND ')}) SELECT *,COUNT(*) OVER() AS total FROM pool WHERE match_score>=? ORDER BY ${shortlist?'':'featured DESC,'}${f.sort==='active'?'last_active_at DESC,':''}${job?'match_score DESC,':''}premium DESC,user_id LIMIT 25 OFFSET ?`).bind(job??'{}',...values,Math.max(0,Math.min(100,Number(f.score)||0)),(page-1)*25).all<Record<string,any>>();
 return {rows:rows.results,page,plan:plan.tier};
}
export async function inviteCandidate(db:Database,userId:string,jobId:string,candidateId:string,source:'shortlist'|'talent_search',message:string,now=new Date()){
 if(message.length>2000||containsDirectContact(message))throw Error('Use a message up to 2,000 characters without direct contact details.');
 const job=await db.prepare(`SELECT j.id,j.title,j.company_id,j.slug,j.confidential,d.input_json FROM jobs j JOIN employer_listings l ON l.job_id=j.id JOIN native_listing_details d ON d.job_id=j.id WHERE j.id=? AND ${JOB_ACCESS_SQL} AND j.listed=1 AND j.expires_at>?`).bind(jobId,userId,userId,now.toISOString()).first<{id:string;title:string;company_id:string;slug:string;confidential:number;input_json:string}>();if(!job)throw Error('Choose an active company job.');
 const plan=await companyPlan(db,job.company_id,now);if(!await companyMembership(db,userId,job.company_id)||!plan||(source==='talent_search'?plan.tier!=='platinum':!pricing.plans[plan.tier].shortlistInvites))throw Error('Your plan does not include this invitation type.');
 if(await db.prepare('SELECT id FROM product_invitations WHERE job_id=? AND candidate_id=?').bind(jobId,candidateId).first())return {duplicate:true};
 const details=await candidateDetails(db,candidateId);if(!details.profile?.talent_pool_opt_in||details.profile.availability==='not_looking'||!details.profile.product_profile_completed||await db.prepare("SELECT id FROM company_purchase_entitlements WHERE user_id=? AND status='active'").bind(candidateId).first())throw Error('This candidate is not available in Talent Search.');
 const score=matchScore(JSON.parse(job.input_json) as CanonicalPosting,candidateMatchProfile(details));
 if(source==='shortlist'&&(details.profile.completeness<60||!score.breakdown.eligible||!await db.prepare('SELECT job_id FROM candidate_shortlists WHERE job_id=? AND candidate_id=? AND date=?').bind(jobId,candidateId,now.toISOString().slice(0,10)).first()))throw Error('Refresh the shortlist and choose an eligible suggested candidate.');
 const period=now.toISOString().slice(0,7),id=crypto.randomUUID(),at=now.toISOString();
 const used=await db.prepare("SELECT COUNT(*) n FROM product_invitations WHERE company_id=? AND source='talent_search' AND quota_period=? AND pack_id IS NULL").bind(job.company_id,period).first<number>('n')??0;
 const pack=source==='talent_search'&&used>=pricing.plans.platinum.talentInvites?await db.prepare('SELECT id FROM talent_invite_packs WHERE company_id=? AND revoked=0 AND used<quantity ORDER BY created_at,id LIMIT 1').bind(job.company_id).first<{id:string}>():null;
 const allowance=source==='shortlist'?`(SELECT COUNT(*) FROM product_invitations WHERE job_id=? AND source='shortlist')<${pricing.plans[plan.tier].shortlistInvites}`:pack?"EXISTS(SELECT 1 FROM talent_invite_packs WHERE id=? AND revoked=0 AND used<quantity)":`(SELECT COUNT(*) FROM product_invitations WHERE company_id=? AND source='talent_search' AND quota_period=? AND pack_id IS NULL)<${pricing.plans.platinum.talentInvites}`;
 const allowanceValues=source==='shortlist'?[jobId]:pack?[pack.id]:[job.company_id,period];
 await db.batch([
 db.prepare(`INSERT OR IGNORE INTO product_invitations(id,company_id,job_id,candidate_id,sent_by,source,message,sent_at,quota_period,pack_id) SELECT ?,?,?,?,?,?,?,?,?,? WHERE ${allowance} AND EXISTS(SELECT 1 FROM profiles WHERE user_id=? AND talent_pool_opt_in=1 AND availability<>'not_looking') AND NOT EXISTS(SELECT 1 FROM authenticated_applications WHERE job_id=? AND user_id=?)`).bind(id,job.company_id,jobId,candidateId,userId,source,message.trim(),at,period,pack?.id??null,...allowanceValues,candidateId,jobId,candidateId),
 db.prepare('UPDATE talent_invite_packs SET used=used+1 WHERE id=? AND EXISTS(SELECT 1 FROM product_invitations WHERE id=? AND pack_id=talent_invite_packs.id)').bind(pack?.id??null,id),
 db.prepare(`INSERT OR IGNORE INTO notification_outbox(id,user_id,kind,subject,body,destination_path,created_at) SELECT ?,?,'job_invitation',?,?,?,? WHERE EXISTS(SELECT 1 FROM product_invitations WHERE id=?)`).bind('invitation:'+id,candidateId,'You are invited to apply: '+job.title,`Match ${score.score}%. ${message.trim()} Invitations bypass the early-access wait.`, job.confidential?'/private-jobs/'+encodeURIComponent(job.id):'/jobs/'+job.slug,at,id),
 ]);
 if(!await db.prepare('SELECT id FROM product_invitations WHERE id=?').bind(id).first())throw Error('Invitation limit reached, candidate already applied, or this invitation was already sent.');return {duplicate:false};
}

export async function refreshJobShortlist(db:Database,jobId:string,now=new Date()){
 const job=await db.prepare("SELECT j.company_id,p.owner_user_id FROM jobs j JOIN company_plans p ON p.company_id=j.company_id WHERE j.id=? AND j.listed=1 AND j.expires_at>? AND p.tier IN ('scale','platinum') AND p.status IN ('active','trialing') AND p.renews_at>?").bind(jobId,now.toISOString(),now.toISOString()).first<{company_id:string;owner_user_id:string}>();if(!job)return;
 const date=now.toISOString().slice(0,10);if(await db.prepare('SELECT kind FROM product_daily_runs WHERE kind=? AND date=?').bind('shortlist:'+jobId,date).first())return;
 const result=await talentSearch(db,{companyId:job.company_id,userId:job.owner_user_id,jobId,filters:{shortlist:'1'}});
 const statements=result.rows.slice(0,20).map((r,rank)=>db.prepare('INSERT OR REPLACE INTO candidate_shortlists(job_id,candidate_id,date,score,rank) VALUES(?,?,?,?,?)').bind(jobId,r.user_id,date,r.match_score,rank));statements.push(db.prepare('INSERT OR IGNORE INTO product_daily_runs VALUES(?,?,?)').bind('shortlist:'+jobId,date,now.toISOString()));await db.batch(statements);
}
