import {PRODUCT_FLAGS,FEATURED_ELIGIBILITY_SQL} from '@gaming/shared';
import {platform,sameOrigin} from '../../../../lib/platform';
import {adminUser} from '../../../../lib/admin';
import {requireTenantId} from '../../../../lib/tenant';
import {reviewCandidateVerification} from '../../../../lib/product/verification';
import {moderateCompanyReview} from '../../../../lib/product/reviews';
export async function POST(request:Request){if(!sameOrigin(request))return new Response('Forbidden',{status:403});const env=await platform(),admin=await adminUser(env,request);if(!admin)return new Response('Not found',{status:404});const tenantId=await requireTenantId(env.DB),f=await request.formData(),action=String(f.get('action')),id=String(f.get('id')??''),reason=String(f.get('reason')??'').trim(),at=new Date().toISOString();try{
 if(reason.length<10||reason.length>2000)throw Error('Record a reason of 10–2000 characters.');
 if(action==='verification')await reviewCandidateVerification(env.DB,{id,adminId:admin.id,tenantId,approve:f.get('decision')==='approve',reason});
 else if(action==='review'){const decision=f.get('decision');if(!['publish','reject','remove'].includes(String(decision)))throw Error('Invalid decision');await moderateCompanyReview(env.DB,{id,adminId:admin.id,tenantId,action:decision as 'publish'|'reject'|'remove',reason,employmentConfirmed:f.get('employmentConfirmed')==='1'});}
 else if(action==='flag'){if(!(PRODUCT_FLAGS as readonly string[]).includes(id))throw Error('Unknown feature');await env.DB.batch([env.DB.prepare('INSERT INTO feature_flags(tenant_id,name,enabled,updated_at) VALUES(?,?,?,?) ON CONFLICT(tenant_id,name) DO UPDATE SET enabled=excluded.enabled,updated_at=excluded.updated_at').bind(tenantId,id,f.get('enabled')==='1'?1:0,at),env.DB.prepare('INSERT INTO product_admin_audit VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),tenantId,admin.id,'flag',id,reason,at)]);}
 else if(action==='featured'){if(!await env.DB.prepare(`SELECT p.user_id FROM profiles p JOIN users u ON u.id=p.user_id JOIN candidate_subscriptions s ON s.user_id=p.user_id WHERE p.user_id=? AND u.tenant_id=? AND ${FEATURED_ELIGIBILITY_SQL}`).bind(id,tenantId,at).first())throw Error('The candidate must satisfy every featured eligibility requirement.');await env.DB.batch([env.DB.prepare("INSERT INTO featured_members(date,user_id,selected_at,source) VALUES(?,?,?,'admin') ON CONFLICT(date) DO UPDATE SET user_id=excluded.user_id,selected_at=excluded.selected_at,source='admin'").bind(at.slice(0,10),id,at),env.DB.prepare('INSERT INTO product_admin_audit VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),tenantId,admin.id,'featured_override',id,reason,at)]);}
 else if(action==='social'){const decision=String(f.get('decision'));if(!['retry','sent','canceled'].includes(decision))throw Error('Invalid delivery decision');if(f.get('providerChecked')!=='1')throw Error('Check the provider to avoid publishing a duplicate.');await env.DB.batch([env.DB.prepare("UPDATE social_outbox SET status=?,retry_at=NULL,lease_until=NULL,attempts=0,last_error=NULL,provider_id=COALESCE(NULLIF(?,''),provider_id) WHERE id=? AND status IN ('failed','uncertain','unconfigured','retry') AND job_id IN(SELECT id FROM jobs WHERE tenant_id=?)").bind(decision,String(f.get('providerId')??'').slice(0,200),id,tenantId),env.DB.prepare('INSERT INTO product_admin_audit VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),tenantId,admin.id,'social_'+decision,id,reason,at)]);}
 else if(action==='support'){const ticket=await env.DB.prepare('SELECT user_id FROM support_tickets WHERE id=? AND tenant_id=?').bind(id,tenantId).first<{user_id:string|null}>();if(!ticket)throw Error('Ticket not found');const body=String(f.get('reply')??'').trim();if(body.length<5||body.length>10000)throw Error('Write a reply');await env.DB.batch([env.DB.prepare('INSERT INTO support_replies VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,admin.id,body,at),env.DB.prepare("UPDATE support_tickets SET status='answered',first_response_at=COALESCE(first_response_at,?),updated_at=? WHERE id=?").bind(at,at,id),env.DB.prepare("INSERT INTO notification_outbox(id,user_id,kind,subject,body,destination_path,created_at) VALUES(?,?,'support_reply','Support replied to your request','Read the response in your account.',?,?)").bind('support:'+crypto.randomUUID(),ticket.user_id,'/account/support?ticket='+id,at)]);}
 else if(action==='role'){const name=String(f.get('name')??'').trim(),slug=String(f.get('slug')??'').trim(),patterns=String(f.get('patterns')??'').split('\n').map(s=>s.trim()).filter(Boolean),aliases=String(f.get('aliases')??'').split('\n').map(s=>s.trim()).filter(Boolean);if(!/^[a-z0-9-]{2,80}$/.test(slug)||name.length<2||name.length>120||patterns.length>100||aliases.length>100||[...patterns,...aliases].some(s=>s.length>120))throw Error('Use a valid name, slug and one phrase per line.');await env.DB.batch([env.DB.prepare('INSERT INTO job_roles(id,name,slug,aliases_json,patterns_json) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,slug=excluded.slug,aliases_json=excluded.aliases_json,patterns_json=excluded.patterns_json').bind(id||'role:'+crypto.randomUUID(),name,slug,JSON.stringify(aliases),JSON.stringify(patterns)),env.DB.prepare('INSERT INTO product_admin_audit VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),tenantId,admin.id,'job_role',id||slug,reason,at)]);}
 else throw Error('Unknown action');return Response.redirect(new URL('/admin/product',request.url),303);
 }catch(error){return new Response(error instanceof Error?error.message:'Update failed',{status:400});}}
