import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {expect,it,vi} from 'vitest';
import Page from './page';
vi.stubGlobal('React',React);
const flags=vi.hoisted(()=>({enabled:false}));
vi.mock('../../../lib/platform',()=>({platform:async()=>({DB:{}})}));
vi.mock('../../../lib/tenant',()=>({requireTenantId:async()=>'tenant'}));
vi.mock('../../../lib/product/flags',()=>({loadProductFlags:async()=>({PRODUCT_POSTING_V2:flags.enabled})}));
vi.mock('next/navigation',()=>({redirect:(path:string)=>{throw Error('Redirect: '+path);}}));
it('retains legacy bundles when the current offer is disabled',async()=>{const html=renderToStaticMarkup(await Page());expect(html).toContain('24 months');expect(html).toContain('$10,175.00');expect(html).toContain('Continue to payment');expect(html).not.toContain('Automatically renew');});
it('retires new legacy bundle sales when the new posting offer is enabled',async()=>{flags.enabled=true;try{await expect(Page()).rejects.toThrow('Redirect: /post-web3-job');}finally{flags.enabled=false;}});
